//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WFBikePowerConnection;

@protocol _WFBikeTrainerDelegate <NSObject>

@optional
- (void)cpmConnection:(WFBikePowerConnection *)arg1 didReceiveTrainerEnableControlResponse:(unsigned char)arg2;
- (void)cpmConnection:(WFBikePowerConnection *)arg1 didReceiveTrainerResetControlPasscodeResponse:(unsigned char)arg2;
- (void)cpmConnection:(WFBikePowerConnection *)arg1 didReceiveTrainerSetControlPasscodeResponse:(unsigned char)arg2;
- (void)cpmConnection:(WFBikePowerConnection *)arg1 didReceiveTrainerTestOpticalResult:(BOOL)arg2;
@end

