//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFAntControllerDelegate.h"
#import "WFBTLEControllerDelegate.h"
#import "WFHardwareControllerBTLEDelegate.h"
#import "WFHardwareControllerDelegate.h"

@class NSTimer, WFAntController, WFBTLEController, WFConnectorSettings, WFDiscoveryManager, WFFisicaInfo, WFHardwareControllerBTLE, _WFHardwareController;

@interface _WFHardwareConnector : NSObject <WFHardwareControllerDelegate, WFHardwareControllerBTLEDelegate, WFAntControllerDelegate, WFBTLEControllerDelegate>
{
    id <WFHardwareConnectorDelegate> delegate;
    _WFHardwareController *hardwareController;
    WFAntController *antController;
    int currentState;
    WFFisicaInfo *fisicaInfo;
    WFHardwareControllerBTLE *hardwareControllerBTLE;
    WFBTLEController *btleController;
    BOOL btleDidReset;
    id <WFAntFSDeviceDelegate> fsDelegate;
    double sampleRate;
    NSTimer *sampleTimer;
    BOOL bSampleTimerDataCheck;
    BOOL autoReset;
    BOOL allowFirmwareCheck;
    WFConnectorSettings *settings;
    WFDiscoveryManager *discoveryManager;
}

+ (id)notificationCenterNameForConnectorHasDataEvent;
@property(nonatomic) BOOL allowFirmwareCheck; // @synthesize allowFirmwareCheck;
@property(nonatomic) BOOL autoReset; // @synthesize autoReset;
@property(retain, nonatomic) id <WFHardwareConnectorDelegate> delegate; // @synthesize delegate;
- (void)releaseFirmwareUpdater:(id)arg1;
- (id)getFirmwareUpdater;
- (void)setApplicationConnectionRole:(int)arg1;
- (void)disableFirmwareCheck;
- (BOOL)resetConnections;
- (BOOL)enableBTLE:(BOOL)arg1 inBondingMode:(BOOL)arg2;
- (BOOL)disconnectSerialTransferController:(id)arg1;
- (void)delegateStateChanged:(id)arg1;
- (int)currentState;
- (id)controllerForNetworkType:(int)arg1;
- (BOOL)connectSerialTransferController:(id)arg1;
- (void)closeAntFSChannelAndReset:(id)arg1;
- (void)highPrioritySensorData:(id)arg1;
- (void)stopSampleTimer;
- (void)startSampleTimer;
- (void)resetBTLEController:(id)arg1;
- (void)delayBondingModeSwitch:(id)arg1;
- (void)closeAntFSChannel_TM:(id)arg1;
- (void)reset;
- (void)antControllerDidCancelDiscovery:(id)arg1;
- (void)antControllerDidSetNetworkKeys:(id)arg1;
- (void)antController:(id)arg1 receivedFisicaInfo:(id)arg2;
- (void)antController:(id)arg1 disconnectedDevice:(id)arg2;
- (void)antController:(id)arg1 connectedDevice:(id)arg2;
- (void)btleController:(id)arg1 didDiscoverPeripherals:(id)arg2 searchCompleted:(BOOL)arg3;
- (void)btleController:(id)arg1 disconnectedDevice:(id)arg2;
- (void)btleController:(id)arg1 connectedDevice:(id)arg2;
- (void)hardwareControllerHardwareNotSupported:(id)arg1;
- (void)hardwareControllerDidReset:(id)arg1 onMainQueue:(BOOL)arg2;
- (void)hardwareControllerDidDisonnect:(id)arg1;
- (void)hardwareControllerDidConnect:(id)arg1;
- (BOOL)hardwareControllerReset;
- (void)hardwareControllerDeviceDisconnected:(id)arg1;
- (void)hardwareController:(id)arg1 connectedDevice:(id)arg2;
- (void)dealloc;
- (id)init;

@end

