//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBPeripheral.h"

@interface CBPeripheral (WFSuppressWarnings)
@property(readonly, nonatomic) struct __CFUUID *WF_UUID;
@property(readonly, nonatomic) BOOL WF_isConnected;
@end

