//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FullWorkoutPageVC.h"

@class UILabel;

@interface ElevationWorkoutPageVC : FullWorkoutPageVC
{
    UILabel *_altitudeHeaderLabel;
    UILabel *_gradeHeaderLabel;
    UILabel *_totalClimbHeaderLabel;
    UILabel *_climbLapHeaderLabel;
    UILabel *_climbPrevHeaderLabel;
    UILabel *_temperatureHeaderLabel;
    UILabel *_temperatureAvgHeaderLabel;
}

@property(retain, nonatomic) UILabel *temperatureAvgHeaderLabel; // @synthesize temperatureAvgHeaderLabel=_temperatureAvgHeaderLabel;
@property(retain, nonatomic) UILabel *temperatureHeaderLabel; // @synthesize temperatureHeaderLabel=_temperatureHeaderLabel;
@property(retain, nonatomic) UILabel *climbPrevHeaderLabel; // @synthesize climbPrevHeaderLabel=_climbPrevHeaderLabel;
@property(retain, nonatomic) UILabel *climbLapHeaderLabel; // @synthesize climbLapHeaderLabel=_climbLapHeaderLabel;
@property(retain, nonatomic) UILabel *totalClimbHeaderLabel; // @synthesize totalClimbHeaderLabel=_totalClimbHeaderLabel;
@property(retain, nonatomic) UILabel *gradeHeaderLabel; // @synthesize gradeHeaderLabel=_gradeHeaderLabel;
@property(retain, nonatomic) UILabel *altitudeHeaderLabel; // @synthesize altitudeHeaderLabel=_altitudeHeaderLabel;
- (void).cxx_destruct;
- (void)viewDidUnload;
- (void)viewDidLoad;

@end

