//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class FitDeviceViewController, NSArray;

@interface FitFileTableView : UITableViewController
{
    NSArray *fileRecords;
    FitDeviceViewController *fitViewController;
}

@property(retain, nonatomic) FitDeviceViewController *fitViewController; // @synthesize fitViewController;
@property(retain, nonatomic) NSArray *fileRecords; // @synthesize fileRecords;
- (void).cxx_destruct;
- (void)clearFileTable;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

