//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FKHTTPClient.h"

#import "FKActivityFileUploadProtocol.h"
#import "FKAutehnicateWithExternalMethodProtocol.h"

@class FKOAuth2Client;

@interface FKCyclingAnalyticsClient : FKHTTPClient <FKAutehnicateWithExternalMethodProtocol, FKActivityFileUploadProtocol>
{
    FKOAuth2Client *_authClient;
}

+ (id)setupSharedClientOnceWithConsumerKey:(id)arg1 consumerSecret:(id)arg2 redirectURL:(id)arg3;
+ (id)sharedClientOnceWithBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) FKOAuth2Client *authClient; // @synthesize authClient=_authClient;
- (void).cxx_destruct;
- (id)uploadStatusForUploadID:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)uploadStatusForUploadID:(id)arg1 repeat:(int)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)uploadFileAtPath:(id)arg1 parameters:(id)arg2 progress:(CDUnknownBlockType)arg3 uploadSuccess:(CDUnknownBlockType)arg4 processSuccess:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)authenicateSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithConsumerKey:(id)arg1 consumerSecret:(id)arg2 redirectURL:(id)arg3;

@end

