//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FKHTTPClient.h"

#import "FKAutehnicateWithExternalMethodProtocol.h"

@class FKOAuth2Client;

@interface FKDailyMileClient : FKHTTPClient <FKAutehnicateWithExternalMethodProtocol>
{
    FKOAuth2Client *_authClient;
}

+ (id)setupSharedClientOnceWithConsumerKey:(id)arg1 consumerSecret:(id)arg2 redirectURL:(id)arg3;
+ (id)sharedClientOnceWithBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) FKOAuth2Client *authClient; // @synthesize authClient=_authClient;
- (void).cxx_destruct;
- (id)uploadEntry:(id)arg1 gpxFileAtPath:(id)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)authenicateSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithConsumerKey:(id)arg1 consumerSecret:(id)arg2 redirectURL:(id)arg3;

@end

