//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFJSONResponseSerializer.h"

@interface FKGarminResponseSerializer : AFJSONResponseSerializer
{
}

- (id)activityIDFromUploadResponse:(id)arg1 responseObect:(id)arg2 error:(id *)arg3;
- (id)responseObjectForResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;
- (id)init;

@end

