//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FKHTTPClient.h"

#import "FKActivityFileUploadProtocol.h"
#import "FKAutehnicateWithExternalMethodProtocol.h"

@class FKOAuth2Client;

@interface FKMapMyFitnessClient : FKHTTPClient <FKAutehnicateWithExternalMethodProtocol, FKActivityFileUploadProtocol>
{
    FKOAuth2Client *_auth2Client;
}

+ (void)setupSharedClientOnceWithConsumerKey:(id)arg1 consumerSecret:(id)arg2 redirectURL:(id)arg3;
+ (id)sharedClientOnceWithBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) FKOAuth2Client *auth2Client; // @synthesize auth2Client=_auth2Client;
- (void).cxx_destruct;
- (id)uploadFileAtPath:(id)arg1 progress:(CDUnknownBlockType)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)userProfileWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)authenicateSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithBaseURL:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3 redirectURL:(id)arg4;

@end

