//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface FKMyFitnessPalExercise : NSObject
{
    NSString *_exerciseID;
    int _energyExpended;
    NSDate *_startTime;
    int _avgHeartRate;
    int _maxHeartRate;
    int _elevationChange;
    NSString *_statusUpdateMessage;
    double _duration;
    double _distance;
    double _maxSpeed;
}

@property(copy, nonatomic) NSString *statusUpdateMessage; // @synthesize statusUpdateMessage=_statusUpdateMessage;
@property(nonatomic) int elevationChange; // @synthesize elevationChange=_elevationChange;
@property(nonatomic) int maxHeartRate; // @synthesize maxHeartRate=_maxHeartRate;
@property(nonatomic) int avgHeartRate; // @synthesize avgHeartRate=_avgHeartRate;
@property(nonatomic) double maxSpeed; // @synthesize maxSpeed=_maxSpeed;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) int energyExpended; // @synthesize energyExpended=_energyExpended;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) NSString *exerciseID; // @synthesize exerciseID=_exerciseID;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (double)durationMiliSeconds;
- (id)stringFromStartTime;
- (id)dateFormatter;

@end

