//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FKHTTPClient.h"

#import "FKAutehnicateWithExternalMethodProtocol.h"

@class FKOAuth2Client, NSString;

@interface FKMyFitnessPalClient : FKHTTPClient <FKAutehnicateWithExternalMethodProtocol>
{
    BOOL _forceHTTPUserAuthorization;
    FKOAuth2Client *_authClient;
    NSString *_consumerKey;
}

+ (void)setupSharedClientOnceWithConsumerKey:(id)arg1 consumerSecret:(id)arg2 redirectURL:(id)arg3;
+ (id)sharedClientOnceWithBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) NSString *consumerKey; // @synthesize consumerKey=_consumerKey;
@property(retain, nonatomic) FKOAuth2Client *authClient; // @synthesize authClient=_authClient;
@property(nonatomic) BOOL forceHTTPUserAuthorization; // @synthesize forceHTTPUserAuthorization=_forceHTTPUserAuthorization;
- (void).cxx_destruct;
- (id)uploadExercise:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)userProfileWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)dataTaskWithAPIAction:(id)arg1 parameters:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)authenicateSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)userAuthorizationPath;
- (id)initWithBaseURL:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3 redirectURL:(id)arg4;

@end

