//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FKStravaObject.h"

@class FKStravaActivityRef, FKStravaAthleteRef, FKStravaSegment, NSDate, NSString;

@interface FKStravaSegmentEffort : FKStravaObject
{
    unsigned int _uid;
    int _resourceState;
    NSString *_name;
    FKStravaAthleteRef *_athlete;
    NSDate *_startDate;
    NSDate *_startDateLocal;
    int _prRank;
    int _komRank;
    int _startIndex;
    int _endIndex;
    FKStravaActivityRef *_activity;
    FKStravaSegment *_segment;
    double _movingTime;
    double _elapsedTime;
    double _distance;
}

@property(retain, nonatomic) FKStravaSegment *segment; // @synthesize segment=_segment;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(retain, nonatomic) FKStravaActivityRef *activity; // @synthesize activity=_activity;
@property(nonatomic) int endIndex; // @synthesize endIndex=_endIndex;
@property(nonatomic) int startIndex; // @synthesize startIndex=_startIndex;
@property(nonatomic) int komRank; // @synthesize komRank=_komRank;
@property(nonatomic) int prRank; // @synthesize prRank=_prRank;
@property(nonatomic) double elapsedTime; // @synthesize elapsedTime=_elapsedTime;
@property(nonatomic) double movingTime; // @synthesize movingTime=_movingTime;
@property(retain, nonatomic) NSDate *startDateLocal; // @synthesize startDateLocal=_startDateLocal;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) FKStravaAthleteRef *athlete; // @synthesize athlete=_athlete;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int resourceState; // @synthesize resourceState=_resourceState;
@property(nonatomic) unsigned int uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

