//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FKStravaObject.h"

@interface FKStravaDistributionBucket : FKStravaObject
{
    double _max;
    double _min;
    double _time;
}

@property(nonatomic) double time; // @synthesize time=_time;
@property(nonatomic) double min; // @synthesize min=_min;
@property(nonatomic) double max; // @synthesize max=_max;

@end

