//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GANCustomVariable : NSObject
{
    unsigned int index_;
    NSString *name_;
    NSString *value_;
    int scope_;
}

@property(readonly, nonatomic) int scope; // @synthesize scope=scope_;
@property(copy, nonatomic) NSString *value; // @synthesize value=value_;
@property(copy, nonatomic) NSString *name; // @synthesize name=name_;
@property(readonly, nonatomic) unsigned int index; // @synthesize index=index_;
- (void)dealloc;
- (id)initWithIndex:(unsigned int)arg1 name:(id)arg2 value:(id)arg3 scope:(int)arg4;
- (id)init;

@end

