//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GANHTTPResponseParser;

@protocol GANHTTPResponseParserDelegate <NSObject>
- (void)parseError:(GANHTTPResponseParser *)arg1 statusCode:(int)arg2;
- (void)responseParsed:(GANHTTPResponseParser *)arg1 persistentConnection:(BOOL)arg2;
@end

