//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GANHit : NSObject
{
    NSString *hitString_;
    unsigned long long hitId_;
}

@property(readonly, nonatomic) unsigned long long hitId; // @synthesize hitId=hitId_;
@property(copy, nonatomic) NSString *hitString; // @synthesize hitString=hitString_;
- (void)dealloc;
- (id)initWithHitString:(id)arg1 hitId:(unsigned long long)arg2;

@end

