//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GANItem : NSObject
{
    NSString *orderID_;
    NSString *itemSKU_;
    NSString *itemName_;
    NSString *itemCategory_;
    double itemPrice_;
    int itemCount_;
}

@property(readonly, nonatomic) int itemCount; // @synthesize itemCount=itemCount_;
@property(readonly, nonatomic) double itemPrice; // @synthesize itemPrice=itemPrice_;
@property(copy, nonatomic) NSString *itemCategory; // @synthesize itemCategory=itemCategory_;
@property(copy, nonatomic) NSString *itemName; // @synthesize itemName=itemName_;
@property(copy, nonatomic) NSString *itemSKU; // @synthesize itemSKU=itemSKU_;
@property(copy, nonatomic) NSString *orderID; // @synthesize orderID=orderID_;
- (void)dealloc;
- (id)initWithOrderID:(id)arg1 itemSKU:(id)arg2 itemName:(id)arg3 itemCategory:(id)arg4 itemPrice:(double)arg5 itemCount:(int)arg6;
- (id)init;

@end

