//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GANTracker, NSString;

@protocol GANTrackerDelegate <NSObject>

@optional
- (void)trackerDispatchDidComplete:(GANTracker *)arg1 eventsDispatched:(unsigned int)arg2 eventsFailedDispatch:(unsigned int)arg3;
- (void)hitDispatched:(NSString *)arg1;
@end

