//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GANTransaction : NSObject
{
    NSString *orderID_;
    NSString *storeName_;
    double totalCost_;
    double totalTax_;
    double shippingCost_;
}

@property(readonly, nonatomic) double shippingCost; // @synthesize shippingCost=shippingCost_;
@property(readonly, nonatomic) double totalTax; // @synthesize totalTax=totalTax_;
@property(readonly, nonatomic) double totalCost; // @synthesize totalCost=totalCost_;
@property(copy, nonatomic) NSString *storeName; // @synthesize storeName=storeName_;
@property(copy, nonatomic) NSString *orderID; // @synthesize orderID=orderID_;
- (void)dealloc;
- (id)initWithOrderID:(id)arg1 storeName:(id)arg2 totalCost:(double)arg3 totalTax:(double)arg4 shippingCost:(double)arg5;
- (id)init;

@end

