//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FullWorkoutPageVC.h"

@class UILabel, UISlider, UIView;

@interface HeartrateZonesWorkoutPageVC : FullWorkoutPageVC
{
    UIView *_heartrateZoneSliderPlaceholderView;
    UISlider *_heartrateZoneSlider;
    UILabel *_heartRateHeaderLabel;
    UILabel *_workoutTimeHeaderLabel;
    UILabel *_caloriesHeaderLabel;
    UILabel *_burnRateHeaderLabel;
    UILabel *_timeInZoneHeaderLabel;
    UILabel *_speedPowerHeaderLabel;
    UILabel *_anerobicHeaderLabel;
    UILabel *_aerobicHeaderLabel;
    UILabel *_fatBurningHeaderLabel;
    UILabel *_warmupHeaderLabel;
}

@property(retain, nonatomic) UILabel *warmupHeaderLabel; // @synthesize warmupHeaderLabel=_warmupHeaderLabel;
@property(retain, nonatomic) UILabel *fatBurningHeaderLabel; // @synthesize fatBurningHeaderLabel=_fatBurningHeaderLabel;
@property(retain, nonatomic) UILabel *aerobicHeaderLabel; // @synthesize aerobicHeaderLabel=_aerobicHeaderLabel;
@property(retain, nonatomic) UILabel *anerobicHeaderLabel; // @synthesize anerobicHeaderLabel=_anerobicHeaderLabel;
@property(retain, nonatomic) UILabel *speedPowerHeaderLabel; // @synthesize speedPowerHeaderLabel=_speedPowerHeaderLabel;
@property(retain, nonatomic) UILabel *timeInZoneHeaderLabel; // @synthesize timeInZoneHeaderLabel=_timeInZoneHeaderLabel;
@property(retain, nonatomic) UILabel *burnRateHeaderLabel; // @synthesize burnRateHeaderLabel=_burnRateHeaderLabel;
@property(retain, nonatomic) UILabel *caloriesHeaderLabel; // @synthesize caloriesHeaderLabel=_caloriesHeaderLabel;
@property(retain, nonatomic) UILabel *workoutTimeHeaderLabel; // @synthesize workoutTimeHeaderLabel=_workoutTimeHeaderLabel;
@property(retain, nonatomic) UILabel *heartRateHeaderLabel; // @synthesize heartRateHeaderLabel=_heartRateHeaderLabel;
@property(readonly, nonatomic) UISlider *heartrateZoneSlider; // @synthesize heartrateZoneSlider=_heartrateZoneSlider;
@property(retain, nonatomic) UIView *heartrateZoneSliderPlaceholderView; // @synthesize heartrateZoneSliderPlaceholderView=_heartrateZoneSliderPlaceholderView;
- (void).cxx_destruct;
- (void)updateWorkoutPageGUI;
- (void)setLabel:(id)arg1 glowing:(BOOL)arg2;
- (void)setupGlowLabel:(id)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;

@end

