//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FullWorkoutPageVC.h"

@class UIImageView, UILabel, UIView;

@interface HeartrateBurnBurstWorkoutPageVC : FullWorkoutPageVC
{
    UILabel *_heartRateHeaderLabel;
    UILabel *_workoutTimeHeaderLabel;
    UILabel *_caloriesHeaderLabel;
    UILabel *_burnRateHeaderLabel;
    UILabel *_burnHeaderLabel;
    UILabel *_burstHeaderLabel;
    UIImageView *_burnIcon;
    UIImageView *_burstIcon;
    UILabel *_averageHeartRateHeaderLabel;
    UIView *_burnBurstBackgroundView;
    UIImageView *_burnBurstBackgroundImage;
    int _lastZone;
    double _pulseDuration;
}

@property(nonatomic) double pulseDuration; // @synthesize pulseDuration=_pulseDuration;
@property(nonatomic) int lastZone; // @synthesize lastZone=_lastZone;
@property(retain, nonatomic) UIImageView *burnBurstBackgroundImage; // @synthesize burnBurstBackgroundImage=_burnBurstBackgroundImage;
@property(retain, nonatomic) UIView *burnBurstBackgroundView; // @synthesize burnBurstBackgroundView=_burnBurstBackgroundView;
@property(retain, nonatomic) UILabel *averageHeartRateHeaderLabel; // @synthesize averageHeartRateHeaderLabel=_averageHeartRateHeaderLabel;
@property(retain, nonatomic) UIImageView *burstIcon; // @synthesize burstIcon=_burstIcon;
@property(retain, nonatomic) UIImageView *burnIcon; // @synthesize burnIcon=_burnIcon;
@property(retain, nonatomic) UILabel *burstHeaderLabel; // @synthesize burstHeaderLabel=_burstHeaderLabel;
@property(retain, nonatomic) UILabel *burnHeaderLabel; // @synthesize burnHeaderLabel=_burnHeaderLabel;
@property(retain, nonatomic) UILabel *burnRateHeaderLabel; // @synthesize burnRateHeaderLabel=_burnRateHeaderLabel;
@property(retain, nonatomic) UILabel *caloriesHeaderLabel; // @synthesize caloriesHeaderLabel=_caloriesHeaderLabel;
@property(retain, nonatomic) UILabel *workoutTimeHeaderLabel; // @synthesize workoutTimeHeaderLabel=_workoutTimeHeaderLabel;
@property(retain, nonatomic) UILabel *heartRateHeaderLabel; // @synthesize heartRateHeaderLabel=_heartRateHeaderLabel;
- (void).cxx_destruct;
- (void)restoreIcon:(id)arg1;
- (void)stopPulsingIcon:(id)arg1;
- (void)growIcon:(id)arg1;
- (void)shrinkIcon:(id)arg1;
- (void)pulseIconDown:(id)arg1;
- (void)pulseIconUp:(id)arg1;
- (void)updateWorkoutPageGUI;
- (void)viewDidUnload;
- (void)viewDidLoad;

@end

