//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IFTTTTransform3D, UIColor;

@interface IFTTTAnimationFrame : NSObject
{
    BOOL _hidden;
    float _alpha;
    UIColor *_color;
    float _angle;
    IFTTTTransform3D *_transform;
    float _scale;
    struct CGRect _frame;
}

@property(nonatomic) float scale; // @synthesize scale=_scale;
@property(retain, nonatomic) IFTTTTransform3D *transform; // @synthesize transform=_transform;
@property(nonatomic) float angle; // @synthesize angle=_angle;
@property(copy, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(nonatomic) float alpha; // @synthesize alpha=_alpha;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (void).cxx_destruct;

@end

