//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"
#import "CBPeripheralDelegate.h"

@class CBCentralManager, CBPeripheral, NSMutableArray;

@interface MIO_GLOBAL_SDK : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate>
{
    BOOL isMIOGlobalDevice;
    CBPeripheral *CurrentP;
    id <MIO_GLOBAL_SDKDelegate> delegate;
    CBCentralManager *CM;
    NSMutableArray *peripherals;
    CBPeripheral *activePeripheral;
}

@property(retain, nonatomic) CBPeripheral *activePeripheral; // @synthesize activePeripheral;
@property(retain, nonatomic) NSMutableArray *peripherals; // @synthesize peripherals;
@property(retain, nonatomic) CBCentralManager *CM; // @synthesize CM;
@property(nonatomic) id <MIO_GLOBAL_SDKDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (id)getVersionNo;
- (BOOL)getMIOGlobalStatus;
- (void)peripheralDidUpdateRSSI:(id)arg1 error:(id)arg2;
- (void)peripheral:(id)arg1 didWriteValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)CancelConnection;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheral:(id)arg1 didDiscoverIncludedServicesForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManagerDidUpdateState:(id)arg1;
- (id)findCharacteristicFromUUID:(id)arg1 service:(id)arg2;
- (id)findServiceFromUUID:(id)arg1 p:(id)arg2;
- (id)IntToCBUUID:(unsigned short)arg1;
- (unsigned short)CBUUIDToInt:(id)arg1;
- (int)compareCBUUIDToInt:(id)arg1 UUID2:(unsigned short)arg2;
- (int)compareCBUUID:(id)arg1 UUID2:(id)arg2;
- (const char *)UUIDToString:(struct __CFUUID *)arg1;
- (const char *)CBUUIDToString:(id)arg1;
- (void)getAllCharacteristicsFromWatch:(id)arg1;
- (int)UUIDSAreEqual:(struct __CFUUID *)arg1 u2:(struct __CFUUID *)arg2;
- (void)printPeripheralInfo:(id)arg1;
- (void)printKnownPeripherals;
- (void)scanTimer:(id)arg1;
- (const char *)centralManagerStateToString:(int)arg1;
- (void)connectPeripheral:(id)arg1;
- (int)findBLEPeripherals:(int)arg1;
- (void)initSetup;
- (unsigned short)swap:(unsigned short)arg1;
- (void)notification:(int)arg1 characteristicUUID:(int)arg2 p:(id)arg3 on:(BOOL)arg4;
- (void)readValue:(int)arg1 characteristicUUID:(int)arg2 p:(id)arg3;
- (void)writeValue:(int)arg1 characteristicUUID:(int)arg2 p:(id)arg3 data:(id)arg4;
- (void)UnlockMIOGlobalBLEHR:(id)arg1;

@end

