//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplicationDelegate.h"

@class UIApplication;

@protocol NMApplicationNotificaionListener <UIApplicationDelegate>

@optional
- (void)nm_applicaitonDidTakeScreenShot:(UIApplication *)arg1;
@end

