//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (WFCommonDigest)
- (id)wf_sha512;
- (id)wf_sha384;
- (id)wf_sha256;
- (id)wf_sha224;
- (id)wf_sha1;
- (id)wf_md5;
- (id)wf_md4;
- (id)wf_md2;
@end

