//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (WFUnpackBytes)
- (unsigned char)takeNextByteUsingOffsetVariable:(unsigned int *)arg1;
- (float)unpackFloatAsIEEE754UsingOffsetVariable:(unsigned int *)arg1;
- (unsigned long)unpackUInt32UsingOffsetVariable:(unsigned int *)arg1;
- (unsigned short)unpackUInt16UsingOffsetVariable:(unsigned int *)arg1;
- (unsigned char)unpackUInt8UsingOffsetVariable:(unsigned int *)arg1;
@end

