//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (CRC)
- (unsigned short)crc16;
- (unsigned long)crc32FromDefaultTable:(unsigned long)arg1;
- (unsigned long)crc32WithSeed:(unsigned long)arg1 usingPolynomial:(unsigned long)arg2;
- (unsigned long)crc32UsingPolynomial:(unsigned long)arg1;
- (unsigned long)crc32WithSeed:(unsigned long)arg1;
- (unsigned long)crc32;
@end

