//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (WFJSONCoding)
+ (id)WF_arrayOfObjectWithJSONObject:(id)arg1;
+ (id)WF_objectWithJSONObject:(id)arg1;
+ (id)WF_objectWithJSONString:(id)arg1;
+ (id)WF_objectWithJSONData:(id)arg1;
+ (id)WF_objectWithContentsOfJSONFile:(id)arg1;
- (id)WF_JSONObject;
- (BOOL)WF_writeToJSONFile:(id)arg1;
- (id)WF_JSONString;
- (id)WF_JSONData;
@end

