//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, UITableViewCell;

@interface OriginalRow : NSObject
{
    BOOL _hiddenReal;
    BOOL _hiddenPlanned;
    int _batchOperation;
    UITableViewCell *_cell;
    NSIndexPath *_originalIndexPath;
}

@property(retain, nonatomic) NSIndexPath *originalIndexPath; // @synthesize originalIndexPath=_originalIndexPath;
@property(nonatomic) __weak UITableViewCell *cell; // @synthesize cell=_cell;
@property(nonatomic) int batchOperation; // @synthesize batchOperation=_batchOperation;
@property(nonatomic) BOOL hiddenPlanned; // @synthesize hiddenPlanned=_hiddenPlanned;
@property(nonatomic) BOOL hiddenReal; // @synthesize hiddenReal=_hiddenReal;
- (void).cxx_destruct;
- (void)update;
@property(nonatomic) BOOL hidden;

@end

