//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface QuadraticCurveFitter : NSObject
{
    NSMutableArray *_points;
}

@property(retain, nonatomic) NSMutableArray *points; // @synthesize points=_points;
- (double)getPredictedYForX:(double)arg1 withCurveParamsA:(double)arg2 b:(double)arg3 c:(double)arg4;
- (double)getSSerrWithCurveParamsA:(double)arg1 b:(double)arg2 c:(double)arg3;
- (double)getSStot;
- (double)getYMean;
- (double)getSx2y;
- (double)getSxy;
- (double)getSx4;
- (double)getSx3;
- (double)getSx2;
- (double)getSy;
- (double)getSx;
- (double)computeCurveParameterC;
- (double)computeCurveParameterB;
- (double)computeCurveParameterA;
- (void)computeCurveParameterAOut:(double *)arg1 parameterBOut:(double *)arg2 parameterCOut:(double *)arg3 parameterRsqOut:(double *)arg4;
- (void)addPointWithXValue:(double)arg1 yValue:(double)arg2;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

