//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate, NSNumber, NSString, NSURL;

@interface RSSItem : NSObject <NSCoding>
{
    NSString *_title;
    NSString *_itemDescription;
    NSString *_content;
    NSURL *_link;
    NSURL *_commentsLink;
    NSURL *_commentsFeed;
    NSNumber *_commentsCount;
    NSDate *_pubDate;
    NSString *_author;
    NSString *_guid;
}

@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSDate *pubDate; // @synthesize pubDate=_pubDate;
@property(retain, nonatomic) NSNumber *commentsCount; // @synthesize commentsCount=_commentsCount;
@property(retain, nonatomic) NSURL *commentsFeed; // @synthesize commentsFeed=_commentsFeed;
@property(retain, nonatomic) NSURL *commentsLink; // @synthesize commentsLink=_commentsLink;
@property(retain, nonatomic) NSURL *link; // @synthesize link=_link;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)imagesFromHTMLString:(id)arg1;
- (id)imagesFromContent;
- (id)imagesFromItemDescription;

@end

