//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SChartRenderPoints : NSObject
{
    float *_points;
    float *_lowPoints;
    int _numBaselineCrosses;
    int _size;
    int _lowPointsSize;
}

+ (id)calculatedRenderPointsForDataBin:(id)arg1 glBaseline:(float)arg2 fillDirection:(int)arg3 series:(id)arg4 isStepLine:(BOOL)arg5;
+ (void)populateRenderPoints:(id)arg1 fromDataPoints:(id)arg2 lowDataPoints:(id)arg3 pointParams:(CDStruct_ab94678c *)arg4;
+ (void)addFloats:(float [2])arg1 forPoints:(id)arg2 atIndex:(int *)arg3 fillDirection:(int)arg4 lowDP:(id)arg5 pointParams:(CDStruct_ab94678c *)arg6;
+ (void)addFloatsForStackedPoints:(float *)arg1 atIndex:(int)arg2 fromDataPoint:(id)arg3;
+ (void)addFloatsForStepLine:(id)arg1 atIndex:(int *)arg2 fillDirection:(int)arg3 lowDP:(id)arg4 pointXY:(float [2])arg5;
+ (void)addPointsForPossibleBaselineCrossAtIndex:(int *)arg1 renderPoints:(id)arg2 pointXY:(float [2])arg3 pointParams:(CDStruct_ab94678c *)arg4;
+ (int)calculateBaselineCrosses:(id)arg1 updatingPointParams:(CDStruct_ab94678c *)arg2;
+ (BOOL)doesCrossBaseline:(float [2])arg1 updatingPointParams:(CDStruct_ab94678c *)arg2 atIndex:(int)arg3;
+ (void)linkPoints:(id)arg1 lowPoints:(id)arg2 toBinPriorTo:(unsigned int)arg3 inSeries:(id)arg4;
@property(nonatomic) int lowPointsSize; // @synthesize lowPointsSize=_lowPointsSize;
@property(nonatomic) int size; // @synthesize size=_size;
@property(nonatomic) int numBaselineCrosses; // @synthesize numBaselineCrosses=_numBaselineCrosses;
@property(nonatomic) float *lowPoints; // @synthesize lowPoints=_lowPoints;
@property(nonatomic) float *points; // @synthesize points=_points;
- (void)dealloc;
- (id)initWithNumPoints:(int)arg1 numLowPoints:(int)arg2 baselineCrosses:(int)arg3;

@end

