//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartRadialBaseAxisView.h"

@class NSArray, UIColor;

@interface SChartRadialAxisRadialView : SChartRadialBaseAxisView
{
    NSArray *_dashStyle;
    float _startAngle;
    float _endAngle;
}

@property float endAngle; // @synthesize endAngle=_endAngle;
@property float startAngle; // @synthesize startAngle=_startAngle;
@property(retain, nonatomic) NSArray *dashStyle; // @synthesize dashStyle=_dashStyle;
@property(readonly, nonatomic) float lineWidth;
@property(readonly, nonatomic) UIColor *lineColor;
- (void)addLinearSectionWithContext:(struct CGContext *)arg1 center:(struct CGPoint)arg2 radius:(float)arg3 startAngle:(float)arg4 endAngle:(float)arg5;
- (void)addLinearLineWithContext:(struct CGContext *)arg1 center:(struct CGPoint)arg2 radius:(float)arg3 startAngle:(float)arg4 endAngle:(float)arg5;
- (void)addCircularLineWithContext:(struct CGContext *)arg1 center:(struct CGPoint)arg2 radius:(float)arg3 startAngle:(float)arg4 endAngle:(float)arg5;
- (void)drawRect:(struct CGRect)arg1;
- (float *)convertArrayForDashedLines;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 axisSource:(id)arg2;

@end

