//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@protocol SChartAxisViewSource <NSObject>
@property(readonly, nonatomic) float radialSectionSpan;
@property(readonly, nonatomic) unsigned int renderMode;
@property(readonly, nonatomic) UIColor *gridLineColor;
@property(readonly, nonatomic) float axisLineWidth;
@property(readonly, nonatomic) UIColor *axisLineColor;
- (float)stripeWidthForTickValue:(float)arg1;
- (UIColor *)stripeColor:(BOOL)arg1;
- (float)gridLineWidthAtRadius:(float)arg1;
@end

