//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSNumber, UIColor, UIFont;

@interface SChartLegendStyle : NSObject <NSCopying>
{
    BOOL textAlignmentSet;
    BOOL showSymbolsSet;
    BOOL symbolAlignmentSet;
    BOOL orientationSet;
    BOOL showSymbols;
    UIFont *font;
    UIColor *fontColor;
    int textAlignment;
    UIFont *titleFont;
    UIColor *titleFontColor;
    NSNumber *marginWidth;
    UIColor *borderColor;
    NSNumber *cornerRadius;
    int symbolAlignment;
    int orientation;
    UIColor *areaColor;
    NSNumber *horizontalPadding;
    NSNumber *verticalPadding;
    NSNumber *borderWidth;
    NSNumber *_symbolCornerRadius;
}

@property(retain, nonatomic) NSNumber *symbolCornerRadius; // @synthesize symbolCornerRadius=_symbolCornerRadius;
@property(retain, nonatomic) NSNumber *borderWidth; // @synthesize borderWidth;
@property(retain, nonatomic) NSNumber *verticalPadding; // @synthesize verticalPadding;
@property(retain, nonatomic) NSNumber *horizontalPadding; // @synthesize horizontalPadding;
@property(retain, nonatomic) UIColor *areaColor; // @synthesize areaColor;
@property(nonatomic) int orientation; // @synthesize orientation;
@property(nonatomic) int symbolAlignment; // @synthesize symbolAlignment;
@property(nonatomic) BOOL showSymbols; // @synthesize showSymbols;
@property(retain, nonatomic) NSNumber *cornerRadius; // @synthesize cornerRadius;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor;
@property(retain, nonatomic) NSNumber *marginWidth; // @synthesize marginWidth;
@property(retain, nonatomic) UIColor *titleFontColor; // @synthesize titleFontColor;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont;
@property(nonatomic) int textAlignment; // @synthesize textAlignment;
@property(retain, nonatomic) UIColor *fontColor; // @synthesize fontColor;
@property(retain, nonatomic) UIFont *font; // @synthesize font;
- (void)supplementStyleFromStyle:(id)arg1;
- (BOOL)textAlignmentSet;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

