//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SChartDataPointLabelManager : NSObject
{
    NSMutableDictionary *dataPointLabels;
}

- (struct CGPoint)offsetFromDataPoint:(struct CGPoint)arg1 label:(id)arg2 flippedOffset:(BOOL)arg3 seriesOrientation:(int)arg4;
- (void)rotateLabel:(id)arg1 orientation:(unsigned int)arg2;
- (void)generateTextForLabel:(id)arg1 displayValues:(unsigned int)arg2 xAxis:(id)arg3 yAxis:(id)arg4;
- (void)styleDataPointLabel:(id)arg1 style:(id)arg2 xAxis:(id)arg3 yAxis:(id)arg4;
- (struct CGPoint)positionOfDataPointLabel:(id)arg1 series:(id)arg2 xAxis:(id)arg3 yAxis:(id)arg4 parentView:(id)arg5;
- (void)unmanageInvalidDataPointLabels:(id)arg1;
- (void)unmanageAllDataPointLabels;
- (void)addLabelsForDataPoints:(id)arg1 style:(id)arg2 series:(id)arg3 xAxis:(id)arg4 yAxis:(id)arg5 chart:(id)arg6 parentView:(id)arg7;
- (void)dealloc;
- (id)init;

@end

