//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartBarColumnSeries.h"

@interface SChartBarSeries : SChartBarColumnSeries
{
}

- (SEL)themeStyleSelector;
- (id)blockSymbolForSeriesInLegend;
- (id)symbolForSeriesInLegend;
- (void)mapInvalidBins:(id)arg1 withStackedSeries:(id)arg2 onXAxis:(id)arg3 andYAxis:(id)arg4;
- (void)mapWithStackedSeries:(id)arg1 onXAxis:(id)arg2 andYAxis:(id)arg3;
- (void)setStackIndex:(id)arg1;
- (void)setSelectedStyle:(id)arg1;
- (id)selectedStyle;
- (void)setStyle:(id)arg1;
- (id)style;
- (id)init;

@end

