//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SChartHitDetection.h"

@class SChartSeries;

@interface SChartPointHitDetection : NSObject <SChartHitDetection>
{
    SChartSeries *_series;
}

+ (void)setResolvedPointFromDataPoint:(struct SChartSeriesDistanceInfo *)arg1;
@property(nonatomic) SChartSeries *series; // @synthesize series=_series;
- (int)distanceComparisonModeForPoint;
- (int)distanceComparisonModeForSeries;
- (double)distanceToCoord:(struct SChartPoint)arg1 fromCoord:(struct SChartPoint)arg2 inChart:(id)arg3 withDistanceMode:(int)arg4;
- (struct SChartSeriesDistanceInfo)distanceInfoToPoint:(struct SChartPoint)arg1 isOnlySeries:(BOOL)arg2 chart:(id)arg3;
- (void)dealloc;
- (id)initWithSeries:(id)arg1;
- (id)init;

@end

