//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SChartPointPair : NSObject
{
    struct CGPoint pair[2];
}

+ (id)pairWithPointA:(struct CGPoint)arg1 andB:(struct CGPoint)arg2;
- (void)retrievePairTo:(struct CGPoint *)arg1 and:(struct CGPoint *)arg2;

@end

