//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartTheme.h"

@interface SChartLightTheme : SChartTheme
{
}

- (void)configureScatterSeriesStyle:(id)arg1;
- (void)configureColumnSeriesStyle:(id)arg1;
- (void)configureBarSeriesStyle:(id)arg1;
- (void)configureRadialLineSeriesStyle:(id)arg1;
- (void)configureLineSeriesStyle:(id)arg1;
- (void)setColors;
- (void)setFonts;

@end

