//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartLineSeriesBaseStyle.h"

@class SChartBasePointStyle;

@interface SChartRadialLineSeriesStyle : SChartLineSeriesBaseStyle
{
}

@property(retain, nonatomic) SChartBasePointStyle *selectedPointStyle;
@property(retain, nonatomic) SChartBasePointStyle *pointStyle;
- (void)supplementStyleFromStyle:(id)arg1;

@end

