//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSNumber, SChartBackedUserSettable, UIColor;

@interface SChartMajorGridlineStyle : NSObject <NSCopying>
{
    SChartBackedUserSettable *_showMajorGridLinesInternal;
    SChartBackedUserSettable *_dashedMajorGridLinesInternal;
    SChartBackedUserSettable *_lineColorInternal;
    SChartBackedUserSettable *_lineWidthInternal;
    SChartBackedUserSettable *_dashStyleInternal;
    SChartBackedUserSettable *_lineRenderModeInternal;
}

@property(retain, nonatomic) SChartBackedUserSettable *lineRenderModeInternal; // @synthesize lineRenderModeInternal=_lineRenderModeInternal;
@property(retain, nonatomic) SChartBackedUserSettable *dashStyleInternal; // @synthesize dashStyleInternal=_dashStyleInternal;
@property(retain, nonatomic) SChartBackedUserSettable *lineWidthInternal; // @synthesize lineWidthInternal=_lineWidthInternal;
@property(retain, nonatomic) SChartBackedUserSettable *lineColorInternal; // @synthesize lineColorInternal=_lineColorInternal;
@property(retain, nonatomic) SChartBackedUserSettable *dashedMajorGridLinesInternal; // @synthesize dashedMajorGridLinesInternal=_dashedMajorGridLinesInternal;
@property(retain, nonatomic) SChartBackedUserSettable *showMajorGridLinesInternal; // @synthesize showMajorGridLinesInternal=_showMajorGridLinesInternal;
@property(nonatomic) BOOL dashedMajorGridLinesSet; // @dynamic dashedMajorGridLinesSet;
@property(nonatomic) BOOL showMajorGridLinesSet; // @dynamic showMajorGridLinesSet;
@property(retain, nonatomic) NSArray *dashStyle; // @dynamic dashStyle;
@property(nonatomic) BOOL dashedMajorGridLines; // @dynamic dashedMajorGridLines;
@property(nonatomic) BOOL showMajorGridLines; // @dynamic showMajorGridLines;
@property(nonatomic) unsigned int lineRenderMode; // @dynamic lineRenderMode;
@property(retain, nonatomic) NSNumber *lineWidth; // @dynamic lineWidth;
@property(retain, nonatomic) UIColor *lineColor; // @dynamic lineColor;
- (void)supplementStyleFromStyle:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

