//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartRadialAxisRadialView.h"

@interface SChartRadialAxisStripeView : SChartRadialAxisRadialView
{
    BOOL _isAlternate;
    float _tickValue;
}

@property(nonatomic) float tickValue; // @synthesize tickValue=_tickValue;
@property(nonatomic) BOOL isAlternate; // @synthesize isAlternate=_isAlternate;
- (id)lineColor;
- (float)lineWidth;

@end

