//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SChartTickFrequencyPair : NSObject
{
    id _majorTickFrequency;
    id _minorTickFrequency;
}

@property(retain, nonatomic) id minorTickFrequency; // @synthesize minorTickFrequency=_minorTickFrequency;
@property(retain, nonatomic) id majorTickFrequency; // @synthesize majorTickFrequency=_majorTickFrequency;
- (void)dealloc;
- (id)initWithMajor:(id)arg1 minor:(id)arg2;

@end

