//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SChartSetupHelper.h"

@interface SChartUnmappedSetupHelper : NSObject <SChartSetupHelper>
{
}

- (id)setupSeriesGroupWithXAxis:(id)arg1 yAxis:(id)arg2 usingErrorHandler:(id)arg3;
- (void)setupAxes:(id)arg1;
- (void)setupChart:(id)arg1;

@end

