//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SChartAxis, UIView;

@protocol SChartAxisDrawer <NSObject>
- (void)removeAxis;
- (void)drawWithFrame:(struct CGRect)arg1 axis:(SChartAxis *)arg2 onCanvas:(UIView *)arg3;
@end

