//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartDonutSeries.h"

@interface SChartPieSeries : SChartDonutSeries
{
}

- (struct CGPoint)getPieCenter;
- (id)symbolForSliceInLegend:(int)arg1;
- (void)setSelectedStyle:(id)arg1;
- (id)selectedStyle;
- (void)setStyle:(id)arg1;
- (id)style;
- (id)init;

@end

