//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartMultiValueDataPoint.h"

@interface SChartBubbleDataPoint : SChartMultiValueDataPoint
{
}

@property(nonatomic) double area; // @dynamic area;
- (id)initWithInternal:(id)arg1 withXAxis:(id)arg2 andYAxis:(id)arg3;

@end

