//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartBasePointStyle.h"

@class UIColor;

@interface SChartBaselinePointStyle : SChartBasePointStyle
{
    UIColor *_colorBelowBaseline;
}

@property(retain, nonatomic) UIColor *colorBelowBaseline; // @synthesize colorBelowBaseline=_colorBelowBaseline;
- (void)supplementStyleFromStyle:(id)arg1;
- (void)dealloc;

@end

