//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SChartInternalDataPoint, SChartSeries, SChartSeriesDataBin;

@interface SChartSeriesDataPointFinder : NSObject
{
    SChartSeries *_series;
    SChartSeriesDataBin *_currentBin;
    SChartInternalDataPoint *_currentDataPoint;
    int _currentDataBinIndex;
    int _currentDataPointIndex;
}

@property(nonatomic) int currentDataPointIndex; // @synthesize currentDataPointIndex=_currentDataPointIndex;
@property(nonatomic) int currentDataBinIndex; // @synthesize currentDataBinIndex=_currentDataBinIndex;
@property(nonatomic) SChartInternalDataPoint *currentDataPoint; // @synthesize currentDataPoint=_currentDataPoint;
@property(nonatomic) SChartSeriesDataBin *currentBin; // @synthesize currentBin=_currentBin;
@property(nonatomic) SChartSeries *series; // @synthesize series=_series;
- (id)matchingDataPointResultsForChangedValue:(id)arg1;
- (void)moveToNextDataPoint;
- (id)resultsForChangedValue:(id)arg1;
- (id)initWithSeries:(id)arg1;

@end

