//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartMappedSeries.h"

@interface SChartRadialLineSeries : SChartMappedSeries
{
    BOOL _pointsWrapAround;
    float _radius;
    float _minX;
    float _minY;
    float _maxX;
    float _maxY;
}

+ (void)addPoint:(id)arg1 toRenderArray:(float *)arg2 atIndex:(int *)arg3 textures:(id *)arg4 style:(id)arg5;
@property float maxY; // @synthesize maxY=_maxY;
@property float maxX; // @synthesize maxX=_maxX;
@property float minY; // @synthesize minY=_minY;
@property float minX; // @synthesize minX=_minX;
@property float radius; // @synthesize radius=_radius;
@property(nonatomic) BOOL pointsWrapAround; // @synthesize pointsWrapAround=_pointsWrapAround;
- (void)setCrosshairEnabled:(BOOL)arg1;
- (SEL)themeStyleSelector;
- (void)drawBin:(id)arg1 withDrawer:(id)arg2 withGLBaseline:(float)arg3 andGLTranslation:(const CDStruct_265c7ca9 *)arg4 currentRenderIndexDict:(id)arg5;
- (CDStruct_4383f448)populatedRenderArrayForBin:(id)arg1 chosenStyle:(id)arg2;
- (id)blockSymbolForSeriesInLegend;
- (id)setupHelper;
- (id)visibleRangeOnAxis:(id)arg1;
- (void)setSelectedStyle:(id)arg1;
- (id)selectedStyle;
- (void)setStyle:(id)arg1;
- (id)style;
- (void)configureSeriesFromChart:(id)arg1 xAxis:(id)arg2 yAxis:(id)arg3;
- (id)init;

@end

