//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartBaseLayoutManager.h"

@interface SChartRadialLayoutManager : SChartBaseLayoutManager
{
}

- (float)labelOriginMultiplierForCentering:(int)arg1;
- (float)labelOriginMultiplierForPosition:(int)arg1;
- (struct CGRect)canvasFrameToFitLegend:(struct CGRect)arg1;
- (struct CGRect)adjustCanvasFrameForLegend:(struct CGRect)arg1;
- (struct CGRect)createCenteredFrameFromRadius:(float)arg1 relativeToView:(id)arg2;
- (float)calculateGLRadius;
- (float)calculateFrameRadiusFromParentView:(id)arg1;
- (struct CGPoint)originForTitleOnYAxis:(id)arg1 titlePosition:(int)arg2 canvas:(id)arg3 labelSize:(struct CGSize)arg4;
- (struct CGPoint)originForTitleOnXAxis:(id)arg1 titlePosition:(int)arg2 canvas:(id)arg3 labelSize:(struct CGSize)arg4;
- (float)spaceRequiredForAxes:(id)arg1 forPosition:(int)arg2;
- (struct CGRect)calculateFrameForAxis:(id)arg1 withGLFrame:(struct CGRect)arg2;
- (struct CGRect)updateCanvasSize:(struct CGRect)arg1;
- (struct CGRect)adjustCanvasHeightForTitleLabel:(struct CGRect)arg1;
- (struct CGRect)calculateCanvasFrame;
- (struct CGRect)calculateGLFrame;
- (id)init;

@end

