//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartBaseLayoutManager.h"

@interface SChartCartesianLayoutManager : SChartBaseLayoutManager
{
}

- (struct CGRect)updateCanvasSize:(struct CGRect)arg1;
- (void)calcAxisOffsetsWithInital:(id)arg1 toSecondary:(id)arg2;
- (struct CGPoint)originForTitleOnYAxis:(id)arg1 titlePosition:(int)arg2 canvas:(id)arg3 labelSize:(struct CGSize)arg4;
- (struct CGPoint)originForTitleOnXAxis:(id)arg1 titlePosition:(int)arg2 canvas:(id)arg3 labelSize:(struct CGSize)arg4;
- (float)spaceRequiredForAxes:(id)arg1 forPosition:(int)arg2;
- (struct CGRect)calculateFrameForAxis:(id)arg1 withGLFrame:(struct CGRect)arg2;
- (struct CGRect)calculateCanvasFrame;
- (struct CGRect)calculateGLFrame;
- (id)init;

@end

