//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SChartDateMath.h"

@interface SChartOptimisedCalendar : NSObject <SChartDateMath>
{
    id <SChartDateMath> _cal;
    struct counted_map<std::__1::pair<SChart::objc_cpp_retain<NSDate>, SChart::objc_cpp_retain<NSDateComponents>>, SChart::objc_cpp_retain<NSDate>> _dateCache;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)resetIncrement:(id)arg1;
- (id)dateByAddingComponents:(id)arg1 toDate:(id)arg2 options:(unsigned int)arg3;
- (void)setCacheCount:(unsigned int)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCalendar:(id)arg1;

@end

