//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAEAGLLayer, EAGLContext, NSMutableArray, NSMutableDictionary, UIColor;

@interface SChartGLView : UIView
{
    CAEAGLLayer *_eaglLayer;
    EAGLContext *_context;
    UIColor *areaColor;
    BOOL needsResize;
    BOOL frameBufferInitialised;
    unsigned int _framebuffer;
    unsigned int _colorRenderBuffer;
    unsigned int _depthStencilRenderBuffer;
    unsigned int _framebufferMSAA;
    unsigned int _colorRenderBufferMSAA;
    double thisFrameTime;
    double lastFrameTime;
    double stepInTime;
    BOOL resetAnimationTimer;
    NSMutableDictionary *userTextures;
    struct Drawer *drawer;
    struct SChartGLErrorHandler *_errorHandler;
    int backingWidth;
    int backingHeight;
    struct SChartGLAnimationManager *_animationManager;
    NSMutableArray *allSeries;
    struct CGRect glBounds;
}

+ (Class)layerClass;
@property(retain, nonatomic) NSMutableDictionary *userTextures; // @synthesize userTextures;
@property(retain, nonatomic) NSMutableArray *allSeries; // @synthesize allSeries;
@property(retain, nonatomic) UIColor *areaColor; // @synthesize areaColor;
@property(nonatomic) BOOL resetAnimationTimer; // @synthesize resetAnimationTimer;
@property(readonly, nonatomic) struct CGRect glBounds; // @synthesize glBounds;
- (id).cxx_construct;
- (CDStruct_818bb265)convertUIColorToColour4f:(id)arg1;
- (float)timeIncrement;
- (void)addSeries:(id)arg1;
- (void)updateRadialSeries:(id)arg1 atSliceIndex:(int)arg2 withDisplacement:(float)arg3 andAngle:(float)arg4 andLineWidth:(float)arg5;
- (void)updateSeries:(id)arg1 withTranslation:(const CDStruct_265c7ca9 *)arg2;
- (BOOL)endRender;
- (void)beginRenderWithReloadedData:(BOOL)arg1;
- (void)reset;
- (void)deleteFrameBuffer;
- (void)setupFrameBuffer;
- (void)setupLayerWithBackgroundColor:(id)arg1;
- (void)resize;
- (BOOL)checkBufferSize:(float)arg1;
- (void)checkResize;
- (void)dealloc;
- (void)resetEAGLContext;
- (void)setEAGLContext;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (float)glHeight;
- (float)glWidth;
- (id)init;
- (void)populateDefaultPieTexture:(char *)arg1 numberOfPixels:(int)arg2 sizePerPixel:(int)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)getEAGLLayer;
- (id)getContext;
- (unsigned int)getColorRenderBuffer;
- (unsigned int)getFramebuffer;
- (struct CGRect)drawerArea;
- (void)drawBandSeriesFill:(float *)arg1 forSeries:(id)arg2 andLowSeries:(float *)arg3 forIndex:(int *)arg4 withSize:(int)arg5 withAreaColorHigh:(id)arg6 withAreaColorLow:(id)arg7 withOrientation:(int)arg8 withNumCrosses:(int)arg9 andTranslation:(const CDStruct_265c7ca9 *)arg10;
- (void)drawRadialSlice:(int)arg1 forSeries:(id)arg2 fromAngle:(float)arg3 toAngle:(float)arg4 fromCentre:(struct CGPoint)arg5 withInnerRadius:(float)arg6 andOuterRadius:(float)arg7 withDisplacement:(float)arg8 withFillColor:(id)arg9 withLineColor:(id)arg10 withLineWidth:(float)arg11 withEffect:(int)arg12;
- (BOOL)createTextureFromUIImage:(id)arg1 textureId:(unsigned int *)arg2;
- (void)drawDataPoints:(float *)arg1 series:(id)arg2 index:(int *)arg3 pointTextures:(id *)arg4 size:(int)arg5 color:(id)arg6 colorBelowBaseline:(id)arg7 radius:(float)arg8 radiusArray:(float *)arg9 baseline:(float)arg10 fillDirection:(int)arg11 translation:(const CDStruct_265c7ca9 *)arg12;
- (void)barColumnLine:(float *)arg1 forSeries:(id)arg2 withBaseSeries:(float *)arg3 forIndex:(int *)arg4 withSize:(unsigned int)arg5 withColor:(id)arg6 withColorBelowBaseline:(id)arg7 withBarColumnWidth:(float)arg8 withLineWidth:(float)arg9 withGLBaseline:(float)arg10 andOrientation:(int)arg11 andTranslation:(const CDStruct_265c7ca9 *)arg12;
- (void)barColumnFill:(float *)arg1 forSeries:(id)arg2 withBaseSeries:(float *)arg3 forIndex:(int *)arg4 withSize:(unsigned int)arg5 withColor:(id)arg6 withColorBelowBaseline:(id)arg7 withColorGradient:(id)arg8 withColorGradientBelowBaseline:(id)arg9 withBarColumnWidth:(float)arg10 withGLBaseline:(float)arg11 andOrientation:(int)arg12 willDrawLinesToo:(BOOL)arg13 andTranslation:(const CDStruct_265c7ca9 *)arg14;
- (void)drawLineStrip:(float *)arg1 forSeries:(id)arg2 forLinesIndex:(int *)arg3 forIndexedOffsetTrianglesIndex:(int *)arg4 forPointsOffset:(int *)arg5 withSize:(int)arg6 withColor:(id)arg7 withColorBelowBaseline:(id)arg8 withWidth:(float)arg9 withBaseline:(float)arg10 withFillDirection:(int)arg11 andTranslation:(const CDStruct_265c7ca9 *)arg12;
- (void)horizontalFill:(float *)arg1 forSeries:(id)arg2 forIndex:(int *)arg3 withSize:(int)arg4 withColor:(id)arg5 withColorBelowBaseline:(id)arg6 withGradientFillColor:(id)arg7 withGradientFillColorBelowBaseline:(id)arg8 withBaseline:(float)arg9 withMaxOffsetAboveBaseline:(float)arg10 withMaxOffsetBelowBaseline:(float)arg11 withFillDirection:(int)arg12 withGradientFill:(BOOL)arg13 andTranslation:(const CDStruct_265c7ca9 *)arg14;
- (void)drawCandlesticks:(float *)arg1 forSeries:(id)arg2 forLinesIndex:(int *)arg3 forTrianglesIndex:(int *)arg4 withSize:(int)arg5 withColors:(id)arg6 withGradientColors:(id)arg7 withOutlineColor:(id)arg8 withStickColor:(id)arg9 withCandleWidth:(float)arg10 withOutlineWidths:(id)arg11 withStickWidths:(id)arg12 drawOutline:(_Bool)arg13 drawSticks:(_Bool)arg14 withOrientation:(int)arg15 andTranslation:(const CDStruct_265c7ca9 *)arg16;
- (void)drawOHLCPoints:(float *)arg1 forSeries:(id)arg2 forLinesIndex:(int *)arg3 forOffsetLinesIndex:(int *)arg4 withSize:(int)arg5 withColors:(id)arg6 withGradientColors:(id)arg7 withOrientation:(int)arg8 withOHLCWidth:(float)arg9 withTrunkWidth:(id)arg10 withArmWidth:(id)arg11 andTranslation:(const CDStruct_265c7ca9 *)arg12;
- (void)setupRadialLineSeries:(float *)arg1 size:(unsigned long)arg2 radius:(float)arg3 glWidth:(float)arg4 glHeight:(float)arg5 minX:(float)arg6 minY:(float)arg7 maxX:(float)arg8 maxY:(float)arg9 maxGradient:(float *)arg10;
- (void)drawRadialLineFill:(float *)arg1 series:(id)arg2 index:(int *)arg3 size:(unsigned long)arg4 maxGradient:(float)arg5 fillInnerColor:(id)arg6 fillOuterColor:(id)arg7;

@end

