//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartThemeDecorator.h"

@interface SChartRadialThemeDecorator : SChartThemeDecorator
{
}

- (void)applyChartStyleToChart:(id)arg1 fromTheme:(id)arg2 preservingSetValues:(BOOL)arg3;
- (void)applyTheme:(id)arg1 toAxesOnChart:(id)arg2 preservingSetValues:(BOOL)arg3;

@end

