//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SChartAxisAdder.h"

@class ShinobiChart;

@interface SChartBaseAxisAdder : NSObject <SChartAxisAdder>
{
    ShinobiChart *_chart;
    id <SChartErrorHandler> _errorHandler;
}

+ (BOOL)axisIsSupported:(id)arg1;
+ (BOOL)supportsMultipleAxes;
@property(retain, nonatomic) id <SChartErrorHandler> errorHandler; // @synthesize errorHandler=_errorHandler;
@property(nonatomic) ShinobiChart *chart; // @synthesize chart=_chart;
- (void)assertAxesArrayContainsSupportedAxes:(id)arg1;
- (void)assertChartContainsSupportedAxes:(id)arg1;
- (BOOL)assertAxisTypeSupported:(id)arg1;
- (BOOL)assertAddingAxis:(id)arg1 toAxesArray:(id)arg2 replacing:(BOOL)arg3;
- (void)moveSeriesOnAxis:(id)arg1 toNewAxis:(id)arg2;
- (void)removeAxis:(id)arg1 fromAxesArray:(id)arg2;
- (void)replaceAxis:(id)arg1 inArray:(id)arg2 withAxis:(id)arg3;
- (void)addAxis:(id)arg1 toAxesArray:(id)arg2;
- (void)dealloc;
- (id)initWithChart:(id)arg1 errorHandler:(id)arg2;

@end

