//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartAxis.h"

@class NSNumber;

@interface SChartDateTimeAxis : SChartAxis
{
    BOOL userHasSetFormatString;
    BOOL formatStringSetInternally;
    BOOL hideMinorTicksOverride;
    double previousFreq;
    BOOL previousFirstMajorTickWasOverAlternate;
    NSNumber *previousFirstMajorTick;
    double refDate;
    BOOL refDateInitialised;
    id <SChartDateMath> _cal;
}

@property(retain, nonatomic) id <SChartDateMath> cal; // @synthesize cal=_cal;
- (void)configureFromFirstDataPointValue:(id)arg1;
- (void)reconfigureFromStubbedAxisCopy:(id)arg1;
- (id)stubCopyOfAxisForDataLoading;
- (BOOL)setRangeWithMinimum:(id)arg1 andMaximum:(id)arg2 withAnimation:(BOOL)arg3 usingBounceLimits:(BOOL)arg4;
- (BOOL)setRangeInternalWithMinimum:(id)arg1 andMaximum:(id)arg2 withAnimation:(BOOL)arg3 usingBounceLimits:(BOOL)arg4;
- (BOOL)refDateInitialised;
- (double)refDate;
- (void)setRefDate:(double)arg1;
- (id)transformValueToExternal:(id)arg1;
- (id)transformValueToInternal:(id)arg1;
- (id)rangeFromRangeWithUserPadding:(id)arg1;
- (id)doubleToData:(double)arg1;
- (void)setLabelFormatString:(id)arg1;
- (void)updateTickLabelConfiguration;
- (id)formatStringForFrequency:(id)arg1;
- (id)stringForValue:(double)arg1;
- (id)stringForId:(id)arg1;
- (double)decrementTickMarkValue:(double)arg1 isMajor:(BOOL)arg2;
- (double)incrementTickMarkValue:(double)arg1 isMajor:(BOOL)arg2;
- (id)dateFromApplyingComponents:(id)arg1 toDate:(id)arg2 goingBackwards:(BOOL)arg3 major:(BOOL)arg4;
- (double)alterInternalTickMarkValue:(double)arg1 isMajor:(BOOL)arg2 negateComponents:(BOOL)arg3;
- (double)alterTickMarkValue:(double)arg1 isMajor:(BOOL)arg2 negateComponents:(BOOL)arg3;
- (id)currentMinorTickFrequency;
- (id)currentMajorTickFrequency;
- (void)setMinorTickFrequency:(id)arg1;
- (void)setMajorTickFrequency:(id)arg1;
- (BOOL)isOverAlternate:(double)arg1;
- (id)firstMinorTick;
- (id)firstMajorTick;
- (id)firstTickIsMajor:(BOOL)arg1;
- (double)putFirstTickValueInBounds:(double)arg1 minimum:(double)arg2 maximum:(double)arg3 major:(BOOL)arg4;
- (double)jumpToFirstTickValueWithMinimum:(double)arg1 alignedToAnchorPoint:(double)arg2;
- (double)roundUpDate:(double)arg1 toMinimum:(double)arg2 usingStep:(double)arg3;
- (int)indexOfFirstLabel:(int)arg1;
- (void)updateInternalTickFrequencies;
- (id)longestLabel;
- (id)manualGenerateTickMarks;
- (BOOL)zoomingIn:(id)arg1 withFrequency:(id)arg2;
- (BOOL)rangePaddingValueIsValid:(id)arg1;
- (id)getNewRangeWithMinimum:(id)arg1 withMaximum:(id)arg2;
- (void)setAnchorPoint:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithRange:(id)arg1;

@end

