//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartSeries.h"

@class NSString;

@interface SChartRadialSeries : SChartSeries
{
    NSString *labelFormatString;
}

@property(retain, nonatomic) NSString *labelFormatString; // @synthesize labelFormatString;
- (id)setupHelper;
- (void)dealloc;

@end

