//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SChartAngler : NSObject
{
}

+ (float)angleBetweenPoint:(struct CGPoint)arg1 andPoint:(struct CGPoint)arg2;
+ (float)wrapHalfPI:(float)arg1;
+ (float)wrap2PI:(float)arg1;
+ (float)wrapAngle:(float)arg1 between:(float)arg2 and:(float)arg3;

@end

