//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIColor;

@interface SChartDashedLineView : UIView
{
    UIColor *color;
    NSArray *dashes;
}

@property(retain, nonatomic) UIColor *color; // @synthesize color;
@property(retain, nonatomic) NSArray *dashes; // @synthesize dashes;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

