//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartTitleStyle.h"

#import "NSCopying.h"

@class SChartBackedUserSettable;

@interface SChartAxisTitleStyle : SChartTitleStyle <NSCopying>
{
    SChartBackedUserSettable *_titleOrientationInternal;
}

@property(retain, nonatomic) SChartBackedUserSettable *titleOrientationInternal; // @synthesize titleOrientationInternal=_titleOrientationInternal;
@property(nonatomic) int titleOrientation; // @dynamic titleOrientation;
- (void)supplementStyleFromStyle:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

