//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartNumberAxis.h"

@class NSNumber;

@interface SChartLogarithmicAxis : SChartNumberAxis
{
    NSNumber *base;
}

@property(retain, nonatomic) NSNumber *base; // @synthesize base;
- (id)rangeFromRangeWithUserPadding:(id)arg1;
- (double)defaultBaseline;
- (id)transformValueToExternal:(id)arg1;
- (id)transformValueToInternal:(id)arg1;
- (double)logValue:(double)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithRange:(id)arg1;

@end

