//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SChartAxis, ShinobiChart;

@protocol SChartSetupHelper <NSObject>
- (id <SChartSeriesGroup>)setupSeriesGroupWithXAxis:(SChartAxis *)arg1 yAxis:(SChartAxis *)arg2 usingErrorHandler:(id <SChartErrorHandler>)arg3;
- (void)setupAxes:(NSArray *)arg1;
- (void)setupChart:(ShinobiChart *)arg1;
@end

