//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartSeriesStyle.h"

@class NSNumber, SChartPointStyle, UIColor;

@interface SChartBandSeriesStyle : SChartSeriesStyle
{
    BOOL showFill;
    BOOL showFillSet;
    UIColor *lineColorHigh;
    UIColor *lineColorLow;
    NSNumber *lineWidth;
    UIColor *areaColorNormal;
    UIColor *areaColorInverted;
    SChartPointStyle *pointStyle;
    SChartPointStyle *selectedPointStyle;
}

@property(retain, nonatomic) SChartPointStyle *selectedPointStyle; // @synthesize selectedPointStyle;
@property(retain, nonatomic) SChartPointStyle *pointStyle; // @synthesize pointStyle;
@property(retain, nonatomic) UIColor *areaColorInverted; // @synthesize areaColorInverted;
@property(retain, nonatomic) UIColor *areaColorNormal; // @synthesize areaColorNormal;
@property(retain, nonatomic) NSNumber *lineWidth; // @synthesize lineWidth;
@property(retain, nonatomic) UIColor *lineColorLow; // @synthesize lineColorLow;
@property(retain, nonatomic) UIColor *lineColorHigh; // @synthesize lineColorHigh;
@property(nonatomic) BOOL showFillSet; // @synthesize showFillSet;
@property(nonatomic) BOOL showFill; // @synthesize showFill;
- (void)supplementStyleFromStyle:(id)arg1;
- (void)dealloc;
- (id)init;

@end

