//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SChartAnimation, SChartAxis, SChartDataPoint, SChartDataPointLabel, SChartRadialDataPoint, SChartRadialSeries, SChartSeries, SChartTickMark, ShinobiChart, UILabel;

@protocol SChartDelegate <NSObject>

@optional
- (void)sChartDidFinishLoadingData:(ShinobiChart *)arg1;
- (void)sChartWillStartLoadingData:(ShinobiChart *)arg1;
- (void)sChartSeries:(SChartSeries *)arg1 animationDidFinish:(SChartAnimation *)arg2;
- (void)sChart:(ShinobiChart *)arg1 alterDataPointLabel:(SChartDataPointLabel *)arg2 forDataPoint:(SChartDataPoint *)arg3 inSeries:(SChartSeries *)arg4;
- (void)sChart:(ShinobiChart *)arg1 setMajorTickFrequency:(id *)arg2 andMinorTickFrequency:(id *)arg3 onGeneratingTickMarksforAxis:(SChartAxis *)arg4;
- (void)sChart:(ShinobiChart *)arg1 alterLabel:(UILabel *)arg2 forDatapoint:(SChartRadialDataPoint *)arg3 atSliceIndex:(int)arg4 inRadialSeries:(SChartRadialSeries *)arg5;
- (NSString *)sChart:(ShinobiChart *)arg1 longestLabelStringOnAxis:(SChartAxis *)arg2;
- (void)sChart:(ShinobiChart *)arg1 alterTickMark:(SChartTickMark *)arg2 beforeAddingToAxis:(SChartAxis *)arg3;
- (void)sChartRenderFinished:(ShinobiChart *)arg1;
- (void)sChartRenderStarted:(ShinobiChart *)arg1 withFullRedraw:(BOOL)arg2;
- (void)sChart:(ShinobiChart *)arg1 crosshairMovedToXValue:(id)arg2 andYValue:(id)arg3;
- (void)sChart:(ShinobiChart *)arg1 toggledSelectionForRadialPoint:(SChartRadialDataPoint *)arg2 inSeries:(SChartRadialSeries *)arg3 atPixelCoordinate:(struct CGPoint)arg4;
- (void)sChart:(ShinobiChart *)arg1 toggledSelectionForPoint:(SChartDataPoint *)arg2 inSeries:(SChartSeries *)arg3 atPixelCoordinate:(struct CGPoint)arg4;
- (void)sChart:(ShinobiChart *)arg1 toggledSelectionForSeries:(SChartSeries *)arg2 nearPoint:(SChartDataPoint *)arg3 atPixelCoordinate:(struct CGPoint)arg4;
- (void)sChart:(ShinobiChart *)arg1 radialSeriesDidEndDecelerating:(SChartRadialSeries *)arg2;
- (void)sChart:(ShinobiChart *)arg1 radialSeriesWillBeginDecelerating:(SChartRadialSeries *)arg2;
- (void)sChart:(ShinobiChart *)arg1 radialSeriesIsPanning:(SChartRadialSeries *)arg2;
- (void)sChart:(ShinobiChart *)arg1 radialSeriesDidStartPanning:(SChartRadialSeries *)arg2;
- (void)sChartIsPanning:(ShinobiChart *)arg1 withChartMovementInformation:(const struct SChartMovementInformation *)arg2;
- (void)sChartIsPanning:(ShinobiChart *)arg1;
- (void)sChartDidFinishPanning:(ShinobiChart *)arg1;
- (void)sChartDidStartPanning:(ShinobiChart *)arg1;
- (void)sChartDidBoxZoom:(ShinobiChart *)arg1;
- (void)sChartIsZooming:(ShinobiChart *)arg1 withChartMovementInformation:(const struct SChartMovementInformation *)arg2;
- (void)sChartIsZooming:(ShinobiChart *)arg1;
- (void)sChartDidResetZoom:(ShinobiChart *)arg1;
- (void)sChartDidFinishZooming:(ShinobiChart *)arg1;
- (void)sChartDidStartZooming:(ShinobiChart *)arg1;
@end

