//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SChartBaseTickManager.h"

@interface SChartCartesianTickManager : SChartBaseTickManager
{
}

- (BOOL)tickValueIsAboveAxisMinimum:(double)arg1;
- (void)updateGridLineViewForTickMark:(id)arg1 glFrame:(struct CGRect)arg2;
- (struct CGRect)frameForGridLineViewWithTickMark:(id)arg1 glFrame:(struct CGRect)arg2;
- (void)updateTickMarkViewForTickMark:(id)arg1;
- (struct CGRect)frameForTickMark:(id)arg1;
- (BOOL)clipLowerLimitWithMode:(int)arg1 withTickPixelValue:(double)arg2;
- (BOOL)clipHigherLimitWithMode:(int)arg1 withTickPixelValue:(double)arg2;
- (int)adjustTickLabelClippingModeLow;
- (int)adjustTickLabelClippingModeHigh;
- (double)getPixelforTick:(double)arg1;
- (void)updateGridStripeViewForTickMark:(id)arg1 glFrame:(struct CGRect)arg2;
- (struct CGRect)gridStripeFrameWithLimits:(struct CGRect)arg1 glFrame:(struct CGRect)arg2;
- (struct CGRect)adjustedTickLabelFrameForTickValue:(double)arg1 isMajor:(BOOL)arg2 originalFrame:(struct CGRect)arg3;
- (float)labelOffsetForStyle:(id)arg1 isMajor:(BOOL)arg2;
- (struct CGPoint)tickAnchorForValue:(double)arg1 isMajor:(BOOL)arg2 tickLabelFrame:(struct CGRect)arg3;
- (struct CGRect)gridStripeLimitsForIndex:(int)arg1 glFrame:(struct CGRect)arg2 tickMark:(id)arg3;
- (float)spaceRequiredForLabels;
- (void)updateTickMarkLabelForTickMark:(id)arg1;
- (void)drawTickMarksWithGLFrame:(struct CGRect)arg1 needToRedrawLabels:(BOOL)arg2;

@end

