//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SChartErrorHandler.h"

@interface ShinobiChartLog : NSObject <SChartErrorHandler>
{
}

+ (id)logStrategy;
+ (void)setLogStrategy:(id)arg1;
+ (BOOL)loggingEnabled;
+ (void)setLoggingEnabled:(BOOL)arg1;
+ (void)fatalLogMessage:(id)arg1 fromSource:(id)arg2;
+ (void)logMessage:(id)arg1 fromSource:(id)arg2;
+ (void)logMessage:(id)arg1;
+ (void)logInfo:(id)arg1 withMessage:(id)arg2 fromSource:(id)arg3;
+ (id)logger;
+ (void)initialize;
- (void)handleErrorWithMessage:(id)arg1 fromSource:(id)arg2;
- (void)handleFatalErrorWithMessage:(id)arg1 fromSource:(id)arg2;

@end

