//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSTimer, UIImageView, UILabel, UISlider;

@interface SlideToCancelViewController : UIViewController
{
    UIImageView *sliderBackground;
    UISlider *slider;
    UILabel *label;
    NSTimer *animationTimer;
    id <SlideToCancelDelegate> delegate;
    BOOL touchIsDown;
    float gradientLocations[3];
    int animationTimerCount;
}

@property(nonatomic) __weak id <SlideToCancelDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)setGradientLocations:(float)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)stopTimer;
- (void)startTimer;
- (void)animationTimerFired:(id)arg1;
- (void)sliderChanged:(id)arg1;
- (void)sliderDown:(id)arg1;
- (void)sliderUp:(id)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)loadView;
@property(readonly, nonatomic) UILabel *label;
@property(nonatomic) BOOL enabled;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;

@end

