//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, WFWahooHRActivitySession, WFWahooMotionAnalysisCalibrationBase;

@protocol TICKRXSensorDelegate <NSObject>
- (void)tickrxSensorDidReceiveTapEvent:(unsigned int)arg1;
- (void)tickrxSensorDidCompleteFinishCalibrationModeRequest:(BOOL)arg1 activityTypeInEffect:(int)arg2 results:(NSDictionary *)arg3;
- (void)tickrxSensorDidCompleteBeginCalibrationModeRequest:(BOOL)arg1 activityTypeInEffect:(int)arg2;
- (void)tickrxSensorDidCompleteSetTapTapVibrationPattern:(BOOL)arg1;
- (void)tickrxSensorDidCompleteSetCalibrationOperation:(BOOL)arg1;
- (void)tickrxSensorDidCompleteGetCalibrationOperation:(WFWahooMotionAnalysisCalibrationBase *)arg1;
- (void)tickrxSensorDidReceiveCurrentSessionTimestamp:(NSDate *)arg1;
- (void)tickrxSensorDidReceiveSetTimeResponseWithSuccess:(BOOL)arg1;
- (void)tickrxSensorDidReceiveCurrentActivityTypeSetting:(int)arg1;
- (void)tickrxSensorDidDetectDeviceIsNewerThanSupported;
- (void)tickrxSensorSessionDownloadWasAborted;
- (void)tickrxSensorDidCompleteSessionDownload:(WFWahooHRActivitySession *)arg1;
- (void)tickrxSensorDidProgressSessionDownloadToPercent:(double)arg1;
- (void)tickrxSensorSessionListFetchWasAborted;
- (void)tickrxSensorDidCompleteSessionListFetch:(NSArray *)arg1;
- (void)tickrxSensorDidProgressSessionListFetchToCount:(unsigned short)arg1 ofTotal:(unsigned short)arg2;
@end

