//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UBERWorkoutDisplay.h"

@class WFDisplayConfiguration, WFDisplayMemoryCalculator;

@interface UBERWorkoutDisplayRFLKT : UBERWorkoutDisplay
{
    BOOL _orientationPortrait;
    WFDisplayConfiguration *_RFLKTDisplayConfig;
    int _visiblePageCount;
    WFDisplayMemoryCalculator *_memoryCalculator;
}

+ (id)templatesFileName;
+ (id)newWorkoutDisplayWithTemplateConfiguration:(id)arg1;
+ (id)displayNameForTriggerWithKey:(id)arg1 fromTriggersArray:(id)arg2;
+ (id)displayNameForTriggerWithKey:(id)arg1;
+ (id)displayNameForButtonActionWithKey:(id)arg1 fromActionsArray:(id)arg2;
+ (id)displayNameForButtonActionWithKey:(id)arg1;
+ (id)dataFieldForKey:(id)arg1 fromGroupsArray:(id)arg2;
+ (id)dataFieldForKey:(id)arg1;
+ (id)triggers;
+ (id)dataFields;
+ (id)arrayWithKey:(id)arg1 inJsonFileNamed:(id)arg2;
+ (id)allTriggers;
+ (id)allButtonActions;
+ (id)templatePages;
+ (id)allPredefinedTemplateDisplayPages;
+ (id)allBlankTemplateDisplayPages;
+ (unsigned int)defaultWorkoutDisplayType;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)defaultRFLKTPlusDisplay;
+ (id)defaultRFLKTDisplay;
+ (id)defaultDisplayForWorkoutType:(int)arg1;
@property(retain, nonatomic) WFDisplayMemoryCalculator *memoryCalculator; // @synthesize memoryCalculator=_memoryCalculator;
@property(readonly, nonatomic) int visiblePageCount; // @synthesize visiblePageCount=_visiblePageCount;
@property(nonatomic) BOOL orientationPortrait; // @synthesize orientationPortrait=_orientationPortrait;
@property(retain, nonatomic) WFDisplayConfiguration *RFLKTDisplayConfig; // @synthesize RFLKTDisplayConfig=_RFLKTDisplayConfig;
- (void).cxx_destruct;
- (id)supportedButtonGestures;
- (double)deviceCapacityForPage:(id)arg1;
- (double)deviceCapacityUsed;
- (void)clearCache;
@property(readonly, nonatomic) int targetSensorType;
- (void)initializeWithTemplateConfiguration:(id)arg1;
- (id)newWorkoutDisplayPageFromTemplate:(id)arg1;
- (void)populateFromV3FileAtPath:(id)arg1;

// Remaining properties
@property(nonatomic) BOOL backlightAlwaysOn;
@property(nonatomic) BOOL invertColors;

@end

