//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFJSONCoding.h"

@class NSArray, NSDictionary, NSString, UBERUser, UIImage;

@interface UBERAccount : NSObject <WFJSONCoding>
{
    BOOL _useWorkoutSubfolder;
    UBERUser *_user;
    NSString *_providerKey;
    NSString *_uid;
    NSString *_name;
    NSString *_credentialUID;
    NSString *_email;
    NSString *_nickname;
    NSString *_description;
    UIImage *_image;
    NSArray *_urls;
    NSDictionary *_extendedInfo;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) BOOL useWorkoutSubfolder; // @synthesize useWorkoutSubfolder=_useWorkoutSubfolder;
@property(retain, nonatomic) NSDictionary *extendedInfo; // @synthesize extendedInfo=_extendedInfo;
@property(retain, nonatomic) NSArray *urls; // @synthesize urls=_urls;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *description; // @synthesize description=_description;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *credentialUID; // @synthesize credentialUID=_credentialUID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *providerKey; // @synthesize providerKey=_providerKey;
@property(nonatomic) __weak UBERUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (id)generateCredentialUID;
- (id)FK_credential;
- (BOOL)FK_setCredential:(id)arg1;

@end

