//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

@interface UIActionSheet (SHActionSheetBlocks)
+ (id)SH_actionSheetWithTitle:(id)arg1 buttonTitles:(id)arg2 cancelTitle:(id)arg3 destructiveTitle:(id)arg4 withBlock:(CDUnknownBlockType)arg5;
+ (id)SH_actionSheetWithTitle:(id)arg1;
- (void)setMapOfBlocks:(id)arg1;
- (id)mapOfBlocks;
- (id)blockForKey:(id)arg1;
- (void)addBlock:(id)arg1 forKey:(id)arg2;
- (void)addBlock:(CDUnknownBlockType)arg1 forIndex:(int)arg2;
@property(readonly, nonatomic) CDUnknownBlockType SH_blockDidDismiss;
@property(readonly, nonatomic) CDUnknownBlockType SH_blockWillDismiss;
@property(readonly, nonatomic) CDUnknownBlockType SH_blockDidShow;
@property(readonly, nonatomic) CDUnknownBlockType SH_blockWillShow;
@property(readonly, nonatomic) CDUnknownBlockType SH_blockForCancelButton;
@property(readonly, nonatomic) CDUnknownBlockType SH_blockForDestructiveButton;
- (CDUnknownBlockType)SH_blockForButtonIndex:(int)arg1;
- (void)SH_setDidDismissBlock:(CDUnknownBlockType)arg1;
- (void)SH_setWillDismissBlock:(CDUnknownBlockType)arg1;
- (void)SH_setDidShowBlock:(CDUnknownBlockType)arg1;
- (void)SH_setWillShowBlock:(CDUnknownBlockType)arg1;
- (void)SH_setButtonCancelBlock:(CDUnknownBlockType)arg1;
- (void)SH_setButtonDestructiveBlock:(CDUnknownBlockType)arg1;
- (void)SH_setButtonBlockForIndex:(int)arg1 withBlock:(CDUnknownBlockType)arg2;
- (int)SH_addButtonCancelWithTitle:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (int)SH_addButtonDestructiveWithTitle:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (int)SH_addButtonWithTitle:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
@end

