//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (WFHelpers)
+ (id)colorWithColor:(id)arg1 alpha:(float)arg2;
+ (id)interpolatedColorForValue:(double)arg1 min:(double)arg2 max:(double)arg3 colors:(id)arg4 atPositions:(id)arg5;
+ (id)wahooLightBurstColor;
+ (id)wahooLightBurnColor;
+ (id)wahooDarkBurstColor;
+ (id)wahooDarkBurnColor;
+ (id)wahooDarkGreyColor;
+ (id)wahooDarkRedColor;
+ (id)wahooRedColor;
+ (id)wahooDarkGreenColor;
+ (id)wahooGreenColor;
+ (id)wahooDiamondsPattern;
+ (id)wahooYellowColor;
+ (id)wahooLightBlueColor;
+ (id)wahooDarkBlueColorAlpha:(float)arg1;
+ (id)wahooDarkBlueColor;
+ (id)colorWithRGBArray:(id)arg1 alpha:(float)arg2;
+ (id)colorWithRGBArray:(id)arg1;
+ (id)colorWithRGB:(unsigned int)arg1;
+ (id)colorWithRGB:(unsigned int)arg1 alpha:(float)arg2;
@end

