//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

#import "V8HorizontalPickerElementState.h"

@class UIColor;

@interface V8HorizontalPickerLabel : UILabel <V8HorizontalPickerElementState>
{
    BOOL _selectedElement;
    UIColor *_selectedStateColor;
    UIColor *_normalStateColor;
}

@property(retain, nonatomic) UIColor *normalStateColor; // @synthesize normalStateColor=_normalStateColor;
@property(retain, nonatomic) UIColor *selectedStateColor; // @synthesize selectedStateColor=_selectedStateColor;
@property(nonatomic) BOOL selectedElement; // @synthesize selectedElement=_selectedElement;
- (void).cxx_destruct;

@end

