//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UBERSettings, UBERUser;

@interface WF35to4SettingsMigrator : NSObject
{
    UBERSettings *_settings4;
    UBERUser *_user4;
}

+ (void)migrateIfNeeded:(id)arg1 currentUser:(id)arg2;
@property(retain, nonatomic) UBERUser *user4; // @synthesize user4=_user4;
@property(retain, nonatomic) UBERSettings *settings4; // @synthesize settings4=_settings4;
- (void).cxx_destruct;
- (BOOL)migrateWorkoutTypes:(id)arg1;
- (void)migrateRFLKTTypePage:(unsigned int)arg1 displayConfig:(id)arg2 uberWorkoutProfile:(id)arg3;
- (BOOL)migrateUserInfo:(id)arg1;
- (BOOL)migrateGarminImport:(id)arg1;
- (BOOL)migrateSettings;
- (id)initWithNewSettings:(id)arg1 currentUser:(id)arg2;

@end

