//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString, WFAnnouncementPrefs;

@interface WF35WorkoutType : NSObject
{
    NSMutableArray *sensorsUsed;
    int type;
    int mode;
    int distanceDataFrom;
    int cadenceDataFrom;
    int powerDataFrom;
    BOOL autoPause;
    unsigned int countdownTime;
    unsigned long activePages;
    WFAnnouncementPrefs *announcementPrefs;
    BOOL iPodPage;
    BOOL _usesGPS;
    NSString *key;
    NSString *displayName;
    NSString *name;
    NSMutableArray *_activePagesKeys;
    NSArray *_validPageKeys;
}

+ (id)mapMyFitnessTypeForType:(int)arg1;
+ (id)stravaTypeForType:(int)arg1;
+ (id)myFitnessPalExerciseIDLookup;
+ (id)myFitnessPalTypeForType:(int)arg1 averageSpeed:(double)arg2;
+ (id)TwoPeakTypeForType:(int)arg1;
+ (id)pwxSportTypeForType:(int)arg1;
+ (id)magellanActiveStringForType:(int)arg1;
+ (id)tcxSportTypeForType:(int)arg1;
+ (id)runkeeperStringForType:(int)arg1;
+ (id)dailymileStringForType:(int)arg1;
+ (id)runkeeperEquipmentForType:(int)arg1;
+ (int)workoutSpeedDisplayTypeForType:(int)arg1;
+ (unsigned long)defaultActivePagesForType:(int)arg1;
+ (int)typeFormFitSessionMessage:(CDStruct_6e3ce741 *)arg1;
+ (int)typeForTypeName:(id)arg1;
+ (id)workoutTypeFromType:(int)arg1;
+ (id)localizedWorkoutNameForType:(int)arg1;
+ (id)workoutTypeNameForType:(int)arg1;
+ (id)imageIconForType:(int)arg1;
+ (id)imageIconWithGarminForWorkoutType:(int)arg1;
+ (id)workoutTypeFromName:(id)arg1;
+ (id)workoutTypesForGroup:(int)arg1;
@property(retain, nonatomic) NSArray *validPageKeys; // @synthesize validPageKeys=_validPageKeys;
@property(retain, nonatomic) NSMutableArray *activePagesKeys; // @synthesize activePagesKeys=_activePagesKeys;
@property(nonatomic) BOOL usesGPS; // @synthesize usesGPS=_usesGPS;
@property(nonatomic) BOOL iPodPage; // @synthesize iPodPage;
@property(nonatomic) unsigned long activePages; // @synthesize activePages;
@property(nonatomic) int powerDataFrom; // @synthesize powerDataFrom;
@property(nonatomic) int cadenceDataFrom; // @synthesize cadenceDataFrom;
@property(nonatomic) int distanceDataFrom; // @synthesize distanceDataFrom;
@property(retain, nonatomic) WFAnnouncementPrefs *announcementPrefs; // @synthesize announcementPrefs;
@property(nonatomic) unsigned int countdownTime; // @synthesize countdownTime;
@property(nonatomic) BOOL autoPause; // @synthesize autoPause;
@property(readonly, nonatomic) int mode; // @synthesize mode;
@property(readonly, nonatomic) int type; // @synthesize type;
@property(copy, nonatomic) NSString *name; // @synthesize name;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName;
@property(copy, nonatomic) NSString *key; // @synthesize key;
- (void).cxx_destruct;
- (BOOL)migrateToUBERWorkoutProfile:(id)arg1;
- (void)displayNameDummy;
- (id)localizedName;
- (void)setType:(int)arg1;
- (void)setMode:(int)arg1;
@property(readonly, nonatomic) unsigned long requiredSensorTypes;
@property(readonly, nonatomic) NSArray *sensorsUsed;
- (BOOL)usesSensorOfType:(int)arg1 withId:(CDStruct_391ccd70)arg2;
- (BOOL)usesSensorOfType:(int)arg1;
- (void)setPageInactive:(unsigned char)arg1;
- (void)setPageWithKeyActive:(id)arg1;
- (void)setPageActive:(unsigned char)arg1;
- (void)setDefaultDataSources;
- (unsigned long)sensorsAvailableForCadence;
- (unsigned long)sensorsAvailableForDistance;
- (unsigned long)sensorsThatMayBeAdded;
- (BOOL)removeSensorsOfType:(int)arg1;
- (BOOL)removeSensor:(id)arg1;
- (unsigned char)pageCount;
- (BOOL)isPageWithKeyActive:(id)arg1;
- (BOOL)isPageActive:(unsigned char)arg1;
- (id)pageKeyForPageNumber:(unsigned char)arg1;
- (BOOL)addSensor:(id)arg1 updateDefaults:(BOOL)arg2;
- (id)init;

@end

