//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WFAtmosPressureCalculatorWorkout, WFSession;

@interface WFAltimeter : NSObject
{
    double lastAtmosPressure;
    double lastElevation;
    double verticalAccuracy;
    double lastGPSElevation;
    BOOL manuallyCalibrated;
    id <WFAltimeterDataSource> _dataSource;
    id <WFAltimeterDelegate> _delegate;
    WFSession *_session;
    WFAtmosPressureCalculatorWorkout *_atmosPressureCalculator;
}

@property(readonly, nonatomic) WFAtmosPressureCalculatorWorkout *atmosPressureCalculator; // @synthesize atmosPressureCalculator=_atmosPressureCalculator;
@property(nonatomic) __weak WFSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <WFAltimeterDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <WFAltimeterDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)formattedClimb:(CDStruct_e25eb2d1 *)arg1 forDuration:(int)arg2;
- (id)formattedGrade:(CDStruct_e25eb2d1 *)arg1;
- (id)formattedAvgTemperature:(CDStruct_e25eb2d1 *)arg1 forDuration:(int)arg2;
- (id)stringFromTemperature:(CDStruct_e25eb2d1 *)arg1 displayCell:(id)arg2;
- (id)formattedTemperature:(CDStruct_e25eb2d1 *)arg1;
- (id)stringFromElevation:(CDStruct_e25eb2d1 *)arg1 displayCell:(id)arg2;
- (id)formattedElevation:(CDStruct_e25eb2d1 *)arg1;
- (void)updateLocation:(id)arg1;
- (void)calibrateFromGPS;
- (void)calibrateFromAltitude:(double)arg1;
- (void)postConnectSetup;
- (void)writeSummaryForWorkout:(id)arg1;
- (void)writeSummaryForSegment:(id)arg1;
- (void)processData:(id)arg1;
- (void)beginWorkout;
- (void)beginSegment;
- (id)init;

@end

