//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface WFAlertNotificationView : UIView
{
    UIButton *_actionButton;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    CDUnknownBlockType _actionTouchedCallbackBlock;
}

+ (id)successNotificationViewWithTitle:(id)arg1 detail:(id)arg2;
+ (id)warningNotificationViewWithTitle:(id)arg1 detail:(id)arg2;
+ (id)errorNotificationViewWithTitle:(id)arg1 detail:(id)arg2;
+ (id)alertNotficationView;
+ (id)colorWithRGBHex:(unsigned int)arg1 alpha:(float)arg2;
@property(copy, nonatomic) CDUnknownBlockType actionTouchedCallbackBlock; // @synthesize actionTouchedCallbackBlock=_actionTouchedCallbackBlock;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak UIButton *actionButton; // @synthesize actionButton=_actionButton;
- (void).cxx_destruct;
- (void)actionButtonTouched:(id)arg1;
- (void)setActionButtonTitle:(id)arg1 touchedCallback:(CDUnknownBlockType)arg2;

@end

