//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFNetworkDiscovery.h"

#import "WFAntScanChannelDelegate.h"

@class WFAntController;

@interface WFANTDiscovery : WFNetworkDiscovery <WFAntScanChannelDelegate>
{
    WFAntController *_antController;
}

@property(retain, nonatomic) WFAntController *antController; // @synthesize antController=_antController;
- (void)antScanChannel:(id)arg1 didDiscoverDevice:(id)arg2;
- (void)statusCheckTimerDidFire:(id)arg1;
- (void)cancelDiscovery;
- (void)discoverSensorTypes:(id)arg1 onNetwork:(int)arg2;

@end

