//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSNumber, NSString;

@interface WFAnnouncement : NSObject
{
    int trigger;
    NSNumber *interval;
    NSNumber *lastValue;
    NSString *stringObject;
    NSString *lastStringObject;
    BOOL enabled;
    BOOL verbose;
    NSMutableArray *elements;
    NSMutableArray *actionElements;
    NSString *displayName;
    BOOL _metric;
}

+ (id)displayNameForSoundElementGroup:(int)arg1;
+ (id)dictionaryOfSupportSoundElementsForTrigger:(int)arg1;
+ (id)arrayOfSupportSoundElementsForTrigger:(int)arg1;
+ (id)arrayOfSoundElementGroups;
+ (id)arrayOfSupportActionElementsForTrigger:(int)arg1;
+ (id)displayNameForTriggerWithoutGroup:(int)arg1;
+ (id)displayNameForTrigger:(int)arg1;
+ (id)displayNameForTriggerGroup:(int)arg1;
+ (id)dictionaryOfGroupedTriggers;
+ (id)arrayOfTriggerGroups;
+ (id)arrayOfTriggers;
+ (int)intervalTypeForTrigger:(int)arg1;
@property(nonatomic, getter=isMetric) BOOL metric; // @synthesize metric=_metric;
@property(copy, nonatomic) NSString *lastStringObject; // @synthesize lastStringObject;
@property(copy, nonatomic) NSString *stringObject; // @synthesize stringObject;
@property(nonatomic) BOOL verbose; // @synthesize verbose;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName;
@property(nonatomic) BOOL enabled; // @synthesize enabled;
@property(readonly, nonatomic) NSArray *actionElements; // @synthesize actionElements;
@property(readonly, nonatomic) NSArray *elements; // @synthesize elements;
@property(retain, nonatomic) NSNumber *lastValue; // @synthesize lastValue;
@property(retain, nonatomic) NSNumber *interval; // @synthesize interval;
@property(nonatomic) int trigger; // @synthesize trigger;
- (void).cxx_destruct;
- (BOOL)announceForSession:(id)arg1 voice:(int)arg2;
- (void)setTriggerNumber:(id)arg1;
- (id)triggerNumber;
- (id)defaultDisplayName;
- (BOOL)hasSoundElementOfType:(int)arg1;
- (void)setSoundElementsWithArray:(id)arg1;
- (void)removeSoundElementWithType:(int)arg1;
- (void)addSoundElementWithType:(int)arg1;
- (BOOL)hasActionElementOfType:(int)arg1;
- (void)setActionElementsWithArray:(id)arg1;
- (void)removeActionElementWithType:(int)arg1;
- (void)addActionElementWithType:(int)arg1;
- (id)description;
- (void)encodeToDictionary:(id)arg1;
- (id)initWithDefaultsDictionary:(id)arg1;
- (id)init;

@end

