//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, WFAntFSDirectory, WFAntFSHostChannel;

@protocol WFAntFSHostChannelDelegate
- (void)antFS:(WFAntFSHostChannel *)arg1 updatePasskey:(char *)arg2 length:(unsigned char)arg3;
- (void)antFS:(WFAntFSHostChannel *)arg1 receivedDirectoryInfo:(WFAntFSDirectory *)arg2;
- (void)antFS:(WFAntFSHostChannel *)arg1 receivedResponse:(int)arg2;
- (void)antFS:(WFAntFSHostChannel *)arg1 downloadProgress:(unsigned long)arg2;
- (void)antFS:(WFAntFSHostChannel *)arg1 downloadFinished:(BOOL)arg2 filePath:(NSString *)arg3;
@end

