//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFAntChannel.h"

@class NSThread;

@interface WFAntFSChannel : WFAntChannel
{
    NSThread *serialThread;
    NSThread *antFSThread;
    BOOL bSerialThreadEnabled;
    BOOL bSerialThreadRunning;
    BOOL bAntFSThreadEnabled;
    BOOL bAntFSThreadRunning;
    BOOL bClosed;
    char *pucTxBuffer;
    unsigned char aucRxBuffer[128];
}

- (id)initWithDelegate:(id)arg1 channelNumber:(unsigned char)arg2;
- (void)close;
- (void)dealloc;

@end

