//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WFAntController, WFAntFSChannel;

@interface WFAntFSDevice : NSObject
{
    id <WFAntFSDeviceDelegate> delegate;
    int deviceType;
    WFAntFSChannel *antFSChannel;
    WFAntController *antController;
}

@property(retain, nonatomic) WFAntFSChannel *antFSChannel; // @synthesize antFSChannel;
@property(nonatomic) __weak id <WFAntFSDeviceDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) WFAntController *antController; // @synthesize antController;
- (void)close;
- (id)init;
- (void)dealloc;

@end

