//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFWirelessController.h"

#import "WFAntChannelDelegate.h"

@class NSTimer, WFANTLib, WFAntChannel, WFAntScanChannel;

@interface WFAntController : WFWirelessController <WFAntChannelDelegate>
{
    id <WFAntControllerDelegate> delegate;
    unsigned char aucAntTxBuffer[16];
    WFANTLib *antLib;
    WFAntChannel *channelPool[8];
    BOOL advancedMode;
    BOOL hasMessage;
    CDStruct_a495ba5a lastAntMessage;
    id <WFAntReceiverDelegate> rxDelegate;
    NSTimer *capsTimer;
    int antChipType;
    unsigned char ucMaxAntChannels;
    BOOL bCapsRequested;
    unsigned char ucNetworkKeysSent;
    WFAntScanChannel *scanChannel;
    int discoverType;
    unsigned char ucANTChannelStart;
    id _perfromSelectorObjectScanChannelDelegate;
}

@property(nonatomic) id perfromSelectorObjectScanChannelDelegate; // @synthesize perfromSelectorObjectScanChannelDelegate=_perfromSelectorObjectScanChannelDelegate;
@property(readonly, nonatomic) int antChipType; // @synthesize antChipType;
@property(readonly, nonatomic) BOOL advancedMode; // @synthesize advancedMode;
- (void)setFirstAvailableANTChannel:(unsigned char)arg1;
- (void)setInterruptedState;
- (BOOL)sendAntMessage:(CDStruct_a495ba5a *)arg1;
- (void)setNetworkKeys;
- (void)requestCapabilities;
- (BOOL)resetAllSensorData;
- (void)reset;
- (BOOL)processResponse:(char *)arg1;
- (void)processAdvancedMode:(id)arg1;
- (BOOL)processEvent:(unsigned char)arg1 antChannel:(unsigned char)arg2 messageBuffer:(char *)arg3;
- (id)initWithDelegate:(id)arg1;
- (BOOL)initializeAdvancedMode:(id)arg1;
@property(readonly, nonatomic) BOOL isInitialized;
@property(readonly, nonatomic) BOOL hasSensorsWithData;
- (BOOL)discoverDevicesOfType:(int)arg1 searchTimeout:(double)arg2;
- (id)cancelDeviceDiscovery;
- (void)cancelDiscovery;
- (void)discoverDevicesWithScanChannelDelegate:(id)arg1;
- (id)getAntFSClientChannel;
- (id)getAntFSHostChannel;
- (unsigned char)availableChannelCount;
- (void)processNetworkKeysResponse:(char *)arg1;
- (void)stopCapsTimer;
- (void)startCapsTimer;
- (void)processCapabilities:(char *)arg1;
- (void)onCapsTick:(id)arg1;
- (void)initChannelPool;
- (BOOL)isInUse;
- (id)getFreeChannel;
@property(readonly, nonatomic) BOOL isAntFSChannelPresent;
@property(retain, nonatomic) WFANTLib *antLib;
- (id)requestSensorConnection:(id)arg1 withProximity:(int)arg2 error:(id *)arg3;
- (id)getConnectionFromParams:(id)arg1;
- (id)getSensorConnections:(int)arg1;
- (void)search:(id)arg1 didDiscoverDevices:(id)arg2 searchCompleted:(BOOL)arg3;
- (void)searchDidClose:(id)arg1;
- (void)antChannel:(id)arg1 connectedDevice:(id)arg2;
- (void)antChannel:(id)arg1 closedChannel:(id)arg2;
- (id)init;
- (void)dealloc;

@end

