//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, WFFitSettingsFileData;

@interface WFAntFSDirectory : NSObject
{
    NSData *dataBuffer;
    unsigned long numberOfEntries;
    WFFitSettingsFileData *settingsFileData;
    BOOL settingsFileRequested;
}

@property(nonatomic) BOOL settingsFileRequested; // @synthesize settingsFileRequested;
@property(retain, nonatomic) WFFitSettingsFileData *settingsFileData; // @synthesize settingsFileData;
@property(readonly, nonatomic) unsigned long numberOfEntries; // @synthesize numberOfEntries;
- (void)adjustTimestamps;
- (id)getActivityEntries;
- (CDStruct_ffca6faa *)entryAtIndex:(unsigned long)arg1;
@property(readonly, nonatomic) CDStruct_0ba1fc72 *pstHeader;
- (id)initWithBuffer:(char *)arg1 bufferLength:(unsigned long)arg2;
- (id)init;
- (void)dealloc;

@end

