//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDynamicTableViewController.h"

@class NSArray, NSDictionary, UIBarButtonItem, UILabel, WFAnnouncement;

@interface WFAnnouncementTriggersTVC : WFDynamicTableViewController
{
    WFAnnouncement *_announcement;
    NSArray *_triggerGroups;
    NSDictionary *_triggerDictionary;
    UIBarButtonItem *_cancelButton;
    UILabel *_headerTitleLabel;
}

@property(nonatomic) __weak UILabel *headerTitleLabel; // @synthesize headerTitleLabel=_headerTitleLabel;
@property(nonatomic) __weak UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) NSDictionary *triggerDictionary; // @synthesize triggerDictionary=_triggerDictionary;
@property(retain, nonatomic) NSArray *triggerGroups; // @synthesize triggerGroups=_triggerGroups;
@property(retain, nonatomic) WFAnnouncement *announcement; // @synthesize announcement=_announcement;
- (void).cxx_destruct;
- (void)cancelButtonTouched:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)isStandaloneVC;
- (void)viewDidLoad;

@end

