//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, WFAntSerialAdapter;

@protocol WFAntSerialAdapterDelegate <NSObject>
- (void)antSerialAdapter:(WFAntSerialAdapter *)arg1 didReceiveResponseFromAntLib:(NSData *)arg2;
- (void)antSerialAdapter:(WFAntSerialAdapter *)arg1 didReceiveChannelEventFromAntLib:(unsigned char)arg2 antChannel:(unsigned char)arg3 messageData:(NSData *)arg4;
- (void)antSerialAdapter:(WFAntSerialAdapter *)arg1 didReceiveMessageForTransmission:(NSData *)arg2;
@end

