//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSSet, WFAntChannel, WFAntScanChannel, WFSensorConnection;

@protocol WFAntChannelDelegate
- (void)search:(WFAntScanChannel *)arg1 didDiscoverDevices:(NSSet *)arg2 searchCompleted:(BOOL)arg3;
- (void)searchDidClose:(WFAntScanChannel *)arg1;
- (void)antChannel:(WFAntChannel *)arg1 connectedDevice:(WFSensorConnection *)arg2;
- (void)antChannel:(WFAntChannel *)arg1 closedChannel:(WFSensorConnection *)arg2;
@end

