//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFGenericDevice.h"

@class WFANTLib, WFResponseQueue;

@interface WFAntDevice : WFGenericDevice
{
    WFANTLib *antLib;
    unsigned char channelNumber;
    unsigned short deviceNumber;
    unsigned long channelId;
    double lastDataTime;
    WFResponseQueue *responseQueue;
    struct {
        unsigned char ucPg80ReserveByte1;
        unsigned char ucPg80ReserveByte2;
        unsigned char ucHwVersion;
        unsigned short usManId;
        unsigned short usModelNumber;
    } stPage80Data;
    struct {
        unsigned char ucPg81ReserveByte1;
        unsigned char ucPg81ReserveByte2;
        unsigned char ucSwVersion;
        unsigned int ulSerialNumber;
    } stPage81Data;
    struct {
        unsigned char ucPg82ReserveByte1;
        unsigned char ucPg82ReserveByte2;
        unsigned int ulCumOperatingTime;
        unsigned char ucBattVoltage256;
        unsigned char ucBattVoltage;
        unsigned char ucBattStatus;
        unsigned char ucCumOperatingTimeRes;
    } stPage82Data;
    unsigned char ucCommandSequenceTx;
    unsigned char ucCommandSequenceRx;
}

+ (id)UUIDForANTDeviceWithDeviceType:(unsigned char)arg1 transmissionType:(unsigned char)arg2 deviceId:(unsigned short)arg3;
+ (int)sensorSubtypeFromTransmissionType:(unsigned char)arg1 sensorType:(int)arg2;
+ (unsigned char)transmissionTypeForSensorSubtype:(int)arg1;
+ (int)sensorTypeFromDeviceType:(unsigned char)arg1;
+ (id)sensorForSensorType:(int)arg1 onNetwork:(int)arg2;
+ (unsigned char)deviceTypeFromSensorType:(int)arg1;
@property(nonatomic) unsigned short deviceNumber; // @synthesize deviceNumber;
@property(nonatomic) unsigned long channelId; // @synthesize channelId;
@property(nonatomic) unsigned char channelNumber; // @synthesize channelNumber;
@property(retain, nonatomic) WFANTLib *antLib; // @synthesize antLib;
- (void)reset;
- (BOOL)processResponse:(char *)arg1;
- (BOOL)processMessage:(char *)arg1;
- (BOOL)processEvent:(unsigned char)arg1 messageBuffer:(char *)arg2;
- (void)configureCommonData:(id)arg1;
- (id)init;
- (void)dealloc;

@end

