//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray, UILabel, UISwitch, WFAnnouncement;

@interface WFAudioAnnouncementCell : UITableViewCell
{
    WFAnnouncement *_announcement;
    UILabel *_triggerLabel;
    UISwitch *_enabledSwitch;
    NSArray *_actionLabels;
}

@property(retain, nonatomic) NSArray *actionLabels; // @synthesize actionLabels=_actionLabels;
@property(nonatomic) __weak UISwitch *enabledSwitch; // @synthesize enabledSwitch=_enabledSwitch;
@property(nonatomic) __weak UILabel *triggerLabel; // @synthesize triggerLabel=_triggerLabel;
@property(retain, nonatomic) WFAnnouncement *announcement; // @synthesize announcement=_announcement;
- (void).cxx_destruct;
- (void)enabledSwitchChanged:(id)arg1;

@end

