//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSingleLineChartVC.h"

#import "WFSingleLineChartDataSource.h"

@interface WFBasicHeartRateLineChartView : WFSingleLineChartVC <WFSingleLineChartDataSource>
{
}

- (void)sChartDidFinishLoadingData:(id)arg1;
- (BOOL)showYAxisForLineChart:(id)arg1;
- (id)colorForLineInlineChart:(id)arg1;
- (id)yAxisMin;
- (id)yAxisMax;
- (id)valueForAverageLine;
- (struct CGPoint)lineChart:(id)arg1 valueForPointAtIndex:(unsigned int)arg2;
- (int)numberOfDataPointsInChart:(id)arg1;
- (int)sampleRate;
- (id)heartRateSamples;
- (void)setWorkout:(id)arg1;

@end

