//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFBikePowerCrankTorqueData : WFSensorData
{
    unsigned char eventCount;
    unsigned char crankTicks;
    unsigned char instantCadence;
    unsigned long accumulatedCrankPeriod;
    float accumulatedTorque;
    unsigned long accumulatedCrankTicks;
    unsigned long averageCadence;
    unsigned long angularVelocity;
    unsigned long averageTorque;
    unsigned long averagePower;
}

@property(nonatomic) unsigned long averagePower; // @synthesize averagePower;
@property(nonatomic) unsigned long averageTorque; // @synthesize averageTorque;
@property(nonatomic) unsigned long angularVelocity; // @synthesize angularVelocity;
@property(nonatomic) unsigned long averageCadence; // @synthesize averageCadence;
@property(nonatomic) unsigned long accumulatedCrankTicks; // @synthesize accumulatedCrankTicks;
@property(nonatomic) float accumulatedTorque; // @synthesize accumulatedTorque;
@property(nonatomic) unsigned long accumulatedCrankPeriod; // @synthesize accumulatedCrankPeriod;
@property(nonatomic) unsigned char instantCadence; // @synthesize instantCadence;
@property(nonatomic) unsigned char crankTicks; // @synthesize crankTicks;
@property(nonatomic) unsigned char eventCount; // @synthesize eventCount;

@end

