//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WFBikeSpeedCadenceConnection, WFOdometerHistory;

@protocol WFBikeSpeedCadenceDelegate <NSObject>
- (void)cscConnection:(WFBikeSpeedCadenceConnection *)arg1 didReceiveSetGearRatioResponse:(BOOL)arg2;
- (void)cscConnection:(WFBikeSpeedCadenceConnection *)arg1 didReceiveGearRatio:(BOOL)arg2 numerator:(unsigned short)arg3 denominator:(unsigned short)arg4;
- (void)cscConnection:(WFBikeSpeedCadenceConnection *)arg1 didResetOdometer:(BOOL)arg2;
- (void)cscConnection:(WFBikeSpeedCadenceConnection *)arg1 didReceiveOdometerHistory:(WFOdometerHistory *)arg2;
@end

