//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSample.h"

@class NSNumber;

@interface WFBikePowerSample : WFSample
{
    float powerInstant;
    float speedInstant;
    float cadenceInstant;
}

+ (id)sampleFromFitnessEquipmentSensor:(id)arg1;
+ (id)sampleFromSensor:(id)arg1;
+ (id)insertNewSampleInManagedObjectContext:(id)arg1;
@property(nonatomic) float cadenceInstant; // @synthesize cadenceInstant;
@property(nonatomic) float speedInstant; // @synthesize speedInstant;
@property(nonatomic) float powerInstant; // @synthesize powerInstant;
- (void)exportCSV:(id)arg1 forSegmentNumber:(int)arg2 workoutStart:(double)arg3;

// Remaining properties
@property(retain, nonatomic) NSNumber *accumPower; // @dynamic accumPower;
@property(retain, nonatomic) NSNumber *accumTorque; // @dynamic accumTorque;
@property(retain, nonatomic) NSNumber *calculatedCrankRevs; // @dynamic calculatedCrankRevs;
@property(retain, nonatomic) NSNumber *crankRevolutions; // @dynamic crankRevolutions;
@property(retain, nonatomic) NSNumber *pedalContribution; // @dynamic pedalContribution;
@property(retain, nonatomic) NSNumber *wheelCircumference; // @dynamic wheelCircumference;
@property(retain, nonatomic) NSNumber *wheelRevolutions; // @dynamic wheelRevolutions;

@end

