//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFBikePowerPowerOnlyData : WFSensorData
{
    unsigned char eventCount;
    unsigned char instantCadence;
    unsigned short accumulatedPower;
    unsigned short instantPower;
    unsigned long averagePower;
    BOOL pedalPowerSupported;
    BOOL pedalDifferentiation;
    float pedalPowerContributionPercent;
}

@property(nonatomic) float pedalPowerContributionPercent; // @synthesize pedalPowerContributionPercent;
@property(nonatomic) BOOL pedalDifferentiation; // @synthesize pedalDifferentiation;
@property(nonatomic) BOOL pedalPowerSupported; // @synthesize pedalPowerSupported;
@property(nonatomic) unsigned long averagePower; // @synthesize averagePower;
@property(nonatomic) unsigned short instantPower; // @synthesize instantPower;
@property(nonatomic) unsigned short accumulatedPower; // @synthesize accumulatedPower;
@property(nonatomic) unsigned char instantCadence; // @synthesize instantCadence;
@property(nonatomic) unsigned char eventCount; // @synthesize eventCount;

@end

