//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFBikePowerWheelTorqueData : WFSensorData
{
    unsigned char eventCount;
    unsigned char wheelTicks;
    unsigned char instantCadence;
    unsigned long accumulatedWheelPeriod;
    float accumulatedTorque;
    unsigned long accumulatedWheelTicks;
    float calculatedCrankTicks;
    unsigned long averageSpeed;
    unsigned long distance;
    unsigned long angularVelocity;
    unsigned long averageTorque;
    unsigned long averagePower;
    unsigned short wheelRPM;
}

@property(nonatomic) unsigned short wheelRPM; // @synthesize wheelRPM;
@property(nonatomic) unsigned long averagePower; // @synthesize averagePower;
@property(nonatomic) unsigned long averageTorque; // @synthesize averageTorque;
@property(nonatomic) unsigned long angularVelocity; // @synthesize angularVelocity;
@property(nonatomic) unsigned long distance; // @synthesize distance;
@property(nonatomic) unsigned long averageSpeed; // @synthesize averageSpeed;
@property(nonatomic) float calculatedCrankTicks; // @synthesize calculatedCrankTicks;
@property(nonatomic) unsigned long accumulatedWheelTicks; // @synthesize accumulatedWheelTicks;
@property(nonatomic) float accumulatedTorque; // @synthesize accumulatedTorque;
@property(nonatomic) unsigned long accumulatedWheelPeriod; // @synthesize accumulatedWheelPeriod;
@property(nonatomic) unsigned char instantCadence; // @synthesize instantCadence;
@property(nonatomic) unsigned char wheelTicks; // @synthesize wheelTicks;
@property(nonatomic) unsigned char eventCount; // @synthesize eventCount;

@end

