//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorConnection.h"

#import "WFBikeSpeedCadenceDelegate.h"

@interface WFBikeSpeedCadenceConnection : WFSensorConnection <WFBikeSpeedCadenceDelegate>
{
    id <WFBikeSpeedCadenceDelegate> cscDelegate;
}

- (BOOL)getDeviceGearRatio;
- (BOOL)setDeviceGearRatioWithNumerator:(unsigned short)arg1 andDenomonator:(unsigned short)arg2;
- (BOOL)setDeviceTime;
- (BOOL)sendRecordCommand:(int)arg1 withOperator:(int)arg2 operands:(id)arg3;
- (BOOL)requestOdometerReset:(float)arg1;
- (BOOL)requestOdometerHistoryFrom:(unsigned char)arg1 to:(unsigned char)arg2;
- (id)getCSCData;
- (id)getBikeSpeedCadenceRawData;
- (id)getBikeSpeedCadenceData;
- (id)cscService;
@property(retain, nonatomic) id <WFBikeSpeedCadenceDelegate> cscDelegate;
- (void)disconnect;
- (void)setConnectionStatus:(int)arg1;
- (void)cscConnection:(id)arg1 didReceiveSetGearRatioResponse:(BOOL)arg2;
- (void)cscConnection:(id)arg1 didReceiveGearRatio:(BOOL)arg2 numerator:(unsigned short)arg3 denominator:(unsigned short)arg4;
- (void)cscConnection:(id)arg1 didResetOdometer:(BOOL)arg2;
- (void)cscConnection:(id)arg1 didReceiveOdometerHistory:(id)arg2;
- (id)init;
- (void)dealloc;

@end

