//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFBikeSpeedCadenceData : WFSensorData
{
    unsigned long accumCrankRevolutions;
    float accumCadenceTime;
    unsigned char instantCrankRPM;
    double cadenceTimestamp;
    BOOL cadenceTimestampOverflow;
    unsigned long accumWheelRevolutions;
    float accumSpeedTime;
    unsigned short instantWheelRPM;
    double speedTimestamp;
    BOOL speedTimestampOverflow;
    double lastWheelDataTime;
    double lastCadenceDataTime;
}

@property(nonatomic) BOOL speedTimestampOverflow; // @synthesize speedTimestampOverflow;
@property(nonatomic) double speedTimestamp; // @synthesize speedTimestamp;
@property(nonatomic) unsigned short instantWheelRPM; // @synthesize instantWheelRPM;
@property(nonatomic) float accumSpeedTime; // @synthesize accumSpeedTime;
@property(nonatomic) unsigned long accumWheelRevolutions; // @synthesize accumWheelRevolutions;
@property(nonatomic) BOOL cadenceTimestampOverflow; // @synthesize cadenceTimestampOverflow;
@property(nonatomic) double cadenceTimestamp; // @synthesize cadenceTimestamp;
@property(nonatomic) unsigned char instantCrankRPM; // @synthesize instantCrankRPM;
@property(nonatomic) float accumCadenceTime; // @synthesize accumCadenceTime;
@property(nonatomic) unsigned long accumCrankRevolutions; // @synthesize accumCrankRevolutions;
- (id)formattedSpeed:(BOOL)arg1;
- (id)formattedDistance:(BOOL)arg1;
- (id)formattedCadence:(BOOL)arg1;
- (id)initWithTime:(double)arg1 wheelTime:(double)arg2 cadenceTime:(double)arg3;

@end

