//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@class WFBTLECommonData;

@interface WFBloodPressureData : WFSensorData
{
    WFBTLECommonData *btleCommonData;
    float systolic;
    float diastolic;
    float meanArterialPressure;
    float heartRate;
    double timestamp;
    unsigned char userId;
    BOOL isStatusPresent;
    CDStruct_0a1bb1e7 stStatus;
    BOOL isMeasurementInProgress;
    float cuffPressure;
}

@property(nonatomic) float cuffPressure; // @synthesize cuffPressure;
@property(nonatomic) BOOL isMeasurementInProgress; // @synthesize isMeasurementInProgress;
@property(readonly, nonatomic) BOOL isStatusPresent; // @synthesize isStatusPresent;
@property(nonatomic) unsigned char userId; // @synthesize userId;
@property(nonatomic) double timestamp; // @synthesize timestamp;
@property(nonatomic) float heartRate; // @synthesize heartRate;
@property(nonatomic) float meanArterialPressure; // @synthesize meanArterialPressure;
@property(nonatomic) float diastolic; // @synthesize diastolic;
@property(nonatomic) float systolic; // @synthesize systolic;
@property(retain, nonatomic) WFBTLECommonData *btleCommonData; // @synthesize btleCommonData;
@property(readonly, nonatomic) CDStruct_0a1bb1e7 *pstStatus;
- (id)initWithTime:(double)arg1 hasStatus:(BOOL)arg2;
- (id)init;
- (void)dealloc;

@end

