//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@interface WFBPMeasurementCh : WFCharacteristicDecoder
{
    BOOL hasTimestamp;
    BOOL hasHeartRate;
    BOOL hasUserId;
    BOOL hasStatus;
    float systolic;
    float diastolic;
    float meanArterialPressure;
    double timestamp;
    float heartRate;
    unsigned char ucUserId;
    unsigned short usStatus;
}

@property(readonly, nonatomic) unsigned short usStatus; // @synthesize usStatus;
@property(readonly, nonatomic) unsigned char ucUserId; // @synthesize ucUserId;
@property(readonly, nonatomic) float heartRate; // @synthesize heartRate;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp;
@property(readonly, nonatomic) float meanArterialPressure; // @synthesize meanArterialPressure;
@property(readonly, nonatomic) float diastolic; // @synthesize diastolic;
@property(readonly, nonatomic) float systolic; // @synthesize systolic;
@property(readonly, nonatomic) BOOL hasStatus; // @synthesize hasStatus;
@property(readonly, nonatomic) BOOL hasUserId; // @synthesize hasUserId;
@property(readonly, nonatomic) BOOL hasHeartRate; // @synthesize hasHeartRate;
@property(readonly, nonatomic) BOOL hasTimestamp; // @synthesize hasTimestamp;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (id)init;

@end

