//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBCentralManager, NSError, WFBTLEPeripheral, WFBTLEPeripheralConnection;

@protocol WFBTLEPeripheralDelegate <NSObject>
- (void)wfPeripheral:(WFBTLEPeripheral *)arg1 didRemoveConnection:(WFBTLEPeripheralConnection *)arg2;
- (void)wfPeripheral:(WFBTLEPeripheral *)arg1 didAddConnection:(WFBTLEPeripheralConnection *)arg2;
- (void)wfPeripheral:(WFBTLEPeripheral *)arg1 didUpdateRSSI:(float)arg2;
- (void)wfPeripheralDidFailCharacteristicDiscovery:(WFBTLEPeripheral *)arg1 withError:(NSError *)arg2;
- (void)wfPeripheralDidFailServiceDiscovery:(WFBTLEPeripheral *)arg1 withError:(NSError *)arg2;
- (void)wfPeripheralDidFinishDiscovery:(WFBTLEPeripheral *)arg1;
- (void)wfPeripheralDidFinishCharacteristicDiscovery:(WFBTLEPeripheral *)arg1;
- (void)wfPeripheralDidFinishServiceDiscovery:(WFBTLEPeripheral *)arg1;
- (void)wfPeripheralDidDisconnect:(WFBTLEPeripheral *)arg1;
- (CBCentralManager *)centralManager;
@end

