//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBTLEServiceProcessor.h"

@class WFCPMControlPointCh, WFCPMPowerMeasurementCh, WFFileLogger, WFWahooCPMControlPointCh;

@interface WFBTLEBikePowerService : WFBTLEServiceProcessor
{
    id <WFBikePowerDelegate> delegate;
    id <WFBikeTrainerDelegate> btDelegate;
    WFCPMPowerMeasurementCh *powerMeasurementCh;
    WFWahooCPMControlPointCh *wahooCPMControlPointCh;
    WFCPMControlPointCh *cpmControlPointCh;
    WFFileLogger *fileLogger;
    unsigned int _kurtSetConfigurationRetryCount;
    int _kurtInitalConfiguartionState;
    int _kurtSetConfiguartionState;
    BOOL _kurtSetFlywheel;
    BOOL _kurtProFlywheel;
    BOOL _kurtSpindownEnabled;
    BOOL bWahooSpecDevice;
}

@property(nonatomic) BOOL kurtSpindownEnabled; // @synthesize kurtSpindownEnabled=_kurtSpindownEnabled;
@property(nonatomic) BOOL kurtSetFlywheel; // @synthesize kurtSetFlywheel=_kurtSetFlywheel;
@property(nonatomic) BOOL kurtProFlywheel; // @synthesize kurtProFlywheel=_kurtProFlywheel;
@property(nonatomic) int kurtInitalConfiguartionState; // @synthesize kurtInitalConfiguartionState=_kurtInitalConfiguartionState;
@property(nonatomic) int kurtSetConfiguartionState; // @synthesize kurtSetConfiguartionState=_kurtSetConfiguartionState;
@property(nonatomic) unsigned int kurtSetConfigurationRetryCount; // @synthesize kurtSetConfigurationRetryCount=_kurtSetConfigurationRetryCount;
@property(retain, nonatomic) id <WFBikeTrainerDelegate> btDelegate; // @synthesize btDelegate;
@property(retain, nonatomic) id <WFBikePowerDelegate> delegate; // @synthesize delegate;
- (BOOL)kurtSetProFlyWheelEnabled:(BOOL)arg1 spindownEnabled:(BOOL)arg2;
- (void)kurtConfigDidTimeout;
- (void)kurtStopConfigTimeout;
- (void)kurtStartConfigTimeout;
- (void)kurtConfigNextState;
- (void)kurtConfigFailed;
- (void)processKurtResponse;
- (BOOL)kurtSetMomentOfInertia:(float)arg1;
- (BOOL)kurtSetDragParams:(float)arg1 offsetYIntercept:(float)arg2;
- (BOOL)kurtSetSpindownParams:(unsigned short)arg1 startPeriod:(unsigned short)arg2 endPeriod:(unsigned short)arg3 debounceThreshold:(unsigned short)arg4;
- (BOOL)kurtSetDriveCircumference:(float)arg1 driveRatio:(unsigned char)arg2;
- (BOOL)trainerEnableControl:(BOOL)arg1 withPasscode:(unsigned long)arg2;
- (BOOL)trainerResetPasscode;
- (BOOL)trainerSetPasscode:(unsigned long)arg1 currentPasscode:(unsigned long)arg2;
- (BOOL)trainerTestOptical;
- (BOOL)trainerRequestAntConnection:(int)arg1 deviceId:(unsigned short)arg2 useForPower:(BOOL)arg3;
- (BOOL)trainerInitSpindown;
- (BOOL)trainerReadMode;
- (BOOL)trainerSetWheelCircumference:(float)arg1;
- (BOOL)trainerSetWindSpeed:(float)arg1;
- (BOOL)trainerSetGrade:(float)arg1;
- (BOOL)trainerSetWindResistance:(float)arg1;
- (BOOL)trainerSetRollingResistance:(double)arg1;
- (BOOL)trainerSetSimMode:(float)arg1 rollingResistance:(float)arg2 windResistance:(float)arg3;
- (BOOL)trainerSetStandardMode:(int)arg1;
- (BOOL)trainerSetResistanceMode:(float)arg1;
- (BOOL)trainerSetFtpMode:(unsigned short)arg1 withPercent:(unsigned short)arg2;
- (BOOL)trainerSetErgMode:(unsigned short)arg1 enableSpeedSimulation:(BOOL)arg2;
- (BOOL)sendSetDeviceCapabilitiesRequest:(unsigned short)arg1;
- (BOOL)sendReadDeviceCapabilitiesRequest;
- (BOOL)sendReadDeviceInfoRequest;
- (BOOL)sendReadCalibrationRequest;
- (BOOL)sendReadCrankLengthRequest;
- (BOOL)sendSetCrankLengthRequest:(float)arg1;
- (BOOL)sendSetTemperatureSlopeRequest:(float)arg1;
- (BOOL)sendSetSlopeRequest:(unsigned short)arg1;
- (BOOL)sendManualZeroRequest;
- (BOOL)sendReadTemperatureRequest;
- (BOOL)sendReadAccelerometerRequest;
- (BOOL)sendFactoryCalibrateRequest:(unsigned char)arg1;
- (BOOL)sendEnableAntRadio:(BOOL)arg1;
- (BOOL)sendAssignDeviceInfo:(unsigned short)arg1 serialNumber:(unsigned long)arg2;
- (void)delegateKurtSetProFlywheel;
- (void)delegateKurtSetProFlywheelFailed;
- (void)delegateKurtResponse;
- (void)delegateKurtSpindownResult;
- (void)delegateTrainerEnableControlResponse;
- (void)delegateTrainerResetControlPasscodeResponse;
- (void)delegateTrainerSetControlPasscodeResponse;
- (void)delegateTrainerTestOpticalResult;
- (void)delegateTrainerSpindownResult;
- (void)delegateTrainerInitSpindownResponse;
- (void)delegateTrainerRequestAntConnectionResponse;
- (void)delegateTrainerReadModeResponse;
- (void)delegateSetTrainerWheelCircumference;
- (void)delegateSetTrainerWindSpeed;
- (void)delegateSetTrainerRollingResistance;
- (void)delegateSetTrainerWindResistance;
- (void)delegateSetTrainerGrade;
- (void)delegateSetTrainerMode;
- (void)delegateReadCrankLengthResponse;
- (void)delegateSetCrankLengthResponse;
- (void)delegateReadDeviceCapabilitiesResponse;
- (void)delegateSetDeviceCapabilitiesResponse;
- (void)delegateReadDeviceInfoResponse;
- (void)delegateReadCalibrationResponse;
- (void)delegateSetTemperatureSlopeResponse;
- (void)delegateSetSlopeResponse;
- (void)delegateReadTemperatureResponse;
- (void)delegateReadAccelerometerResponse;
- (void)delegateFactoryCalibrateResponse;
- (void)delegateCalibrationResponse;
- (void)delegateAntIdResponse;
@property(readonly, nonatomic) BOOL isWahooCPMDevice;
- (id)getData;
- (BOOL)startUpdatingForService:(id)arg1 onPeripheral:(id)arg2;
- (void)reset;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (id)init;

@end

