//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBService, NSMutableDictionary, NSMutableSet, NSString;

@interface WFBTLEService : NSObject
{
    CBService *theService;
    NSString *uuidString;
    NSMutableDictionary *discoveredCharacteristics;
    NSMutableSet *characteristicUUIDStrings;
    BOOL isCharacteristicDiscoveryComplete;
}

@property(readonly, nonatomic) BOOL isCharacteristicDiscoveryComplete; // @synthesize isCharacteristicDiscoveryComplete;
- (id)initWithService:(id)arg1;
- (void)doDiscovery;
@property(readonly, nonatomic) BOOL isCharacteristicDescriptorDiscoveryComplete;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (id)init;

@end

