//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBTLEServiceProcessor.h"

@class WFCSCControlPointCh, WFCSCFeatureCh, WFCSCMeasurementCh, WFSensorLocationCh, WFTemperatureMeasurementCh, WFWahooCSCControlPointCh;

@interface WFBTLEBikeSpeedCadenceService : WFBTLEServiceProcessor
{
    id <WFBikeSpeedCadenceDelegate> delegate;
    WFCSCMeasurementCh *cscMeasurementCh;
    WFTemperatureMeasurementCh *temperatureMeasurementCh;
    WFCSCFeatureCh *cscFeatureCh;
    WFSensorLocationCh *sensorLocationCh;
    WFCSCControlPointCh *cscControlPointCh;
    WFWahooCSCControlPointCh *wfcscControlPointCh;
}

@property(retain, nonatomic) id <WFBikeSpeedCadenceDelegate> delegate; // @synthesize delegate;
- (BOOL)getDeviceGearRatio;
- (BOOL)setDeviceGearRatioWithNumerator:(unsigned short)arg1 andDenomonator:(unsigned short)arg2;
- (BOOL)setDeviceTime;
- (BOOL)sendRecordCommand:(int)arg1 withOperator:(int)arg2 operands:(id)arg3;
- (BOOL)requestOdometerReset:(float)arg1;
- (BOOL)requestHistoryFrom:(unsigned char)arg1 to:(unsigned char)arg2;
- (void)delegateGetGearRatioResponseWithSuccessFlag:(id)arg1;
- (void)delegateSetGearRatioResponseWithSuccessFlag:(id)arg1;
- (void)delegateOdometerReset:(id)arg1;
- (void)delegateOdometerHistory;
- (void)reset;
- (id)getData;
- (BOOL)startUpdatingForService:(id)arg1 onPeripheral:(id)arg2;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (id)init;

@end

