//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBTLEServiceProcessor.h"

@class WFBatteryLevelCh, WFBatteryLevelStateCh, WFBatteryPowerStateCh;

@interface WFBTLEBatteryService : WFBTLEServiceProcessor
{
    WFBatteryLevelCh *battLevelCh;
    WFBatteryLevelStateCh *battLevelStateCh;
    WFBatteryPowerStateCh *battPowerStateCh;
}

- (BOOL)startUpdatingForService:(id)arg1 onPeripheral:(id)arg2;
- (void)configureCommonData:(id)arg1;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (id)init;

@end

