//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSSet;

@interface WFBTLEServiceUUIDInfo : NSObject
{
    NSMutableSet *requiredSet;
    NSMutableSet *atLeastOneSet;
    NSMutableSet *allOrNothingSet;
    NSMutableSet *optionalSet;
}

- (BOOL)doServiceUUIDStringsMatch:(id)arg1;
- (BOOL)doServiceUUIDsMatch:(id)arg1;
- (BOOL)addUUIDToOptionalSet:(id)arg1;
- (BOOL)addUUIDToAllOrNothingSet:(id)arg1;
- (BOOL)addUUIDToAtLeastOneSet:(id)arg1;
- (BOOL)addUUIDToRequiredSet:(id)arg1;
- (BOOL)doServiceUUIDStringsMatchAllOrNothingSet:(id)arg1;
- (BOOL)doServiceUUIDStringsMatchAtLeastOneSet:(id)arg1;
@property(readonly, nonatomic) NSSet *serviceUUIDs;
@property(readonly, nonatomic) NSSet *serviceUUIDStrings;
- (id)init;
- (void)dealloc;

@end

