//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFNetworkDiscovery.h"

#import "CBCentralManagerDelegate.h"
#import "CBPeripheralDelegate.h"

@class CBCentralManager, NSMutableArray, NSTimer;

@interface WFBTLEDiscovery : WFNetworkDiscovery <CBCentralManagerDelegate, CBPeripheralDelegate>
{
    NSMutableArray *_connectedPeripherals;
    NSMutableArray *_misingUUIDPeripherals;
    CBCentralManager *_centralManager;
    struct dispatch_queue_s *_centralManagerQueue;
    NSTimer *_connectedDeviceRetryTimer;
}

@property(retain, nonatomic) NSTimer *connectedDeviceRetryTimer; // @synthesize connectedDeviceRetryTimer=_connectedDeviceRetryTimer;
@property(nonatomic) struct dispatch_queue_s *centralManagerQueue; // @synthesize centralManagerQueue=_centralManagerQueue;
@property(retain, nonatomic) CBCentralManager *centralManager; // @synthesize centralManager=_centralManager;
@property(retain, nonatomic) NSMutableArray *misingUUIDPeripherals; // @synthesize misingUUIDPeripherals=_misingUUIDPeripherals;
@property(retain, nonatomic) NSMutableArray *connectedPeripherals; // @synthesize connectedPeripherals=_connectedPeripherals;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheralDidUpdateRSSI:(id)arg1 error:(id)arg2;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManager:(id)arg1 didRetrieveConnectedPeripherals:(id)arg2;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)updatePeripheral:(id)arg1 advertisementData:(id)arg2 RSSI:(id)arg3;
- (id)discoveredDeviceForPeripheral:(id)arg1;
- (void)statusCheckTimerDidFire:(id)arg1;
- (void)connectedDeviceRetryTimerDidFire:(id)arg1;
- (id)servicesForScan;
- (void)startScanning;
- (void)cancelDiscovery;
- (void)discoverSensorTypes:(id)arg1 onNetwork:(int)arg2;

@end

