//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, WFBTLEPeripheralConnection;

@interface WFBTLEScanInfo : NSObject
{
    WFBTLEPeripheralConnection *peripheralConnection;
    NSSet *serviceUUIDs;
}

@property(readonly, nonatomic) NSSet *serviceUUIDs; // @synthesize serviceUUIDs;
@property(readonly, nonatomic) WFBTLEPeripheralConnection *peripheralConnection; // @synthesize peripheralConnection;
- (id)initWithConnection:(id)arg1 serviceUUIDs:(id)arg2;
- (void)dealloc;

@end

