//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBTLEServiceProcessor.h"

@class NSArray, NSLock, NSString, NSTimer, WFDisplayConfiguration, WFDisplayPage;

@interface WFBTLEDisplayService : WFBTLEServiceProcessor
{
    unsigned char _currentPageBinaryKeyBeforeAlert;
    BOOL _sleepOnDisconnect;
    BOOL _connectionComplete;
    id <WFDisplayConnectionDelegate> _delegate;
    NSArray *_recomendedPageKeysToUpdate;
    NSString *_currentPageKeyBeforeAlert;
    int _sensorSubType;
    WFDisplayPage *_currentPage;
    NSLock *_configurationLock;
    WFDisplayConfiguration *_configuration;
    WFDisplayConfiguration *_pendingConfiguration;
    NSString *_previousPageKey;
    NSTimer *_autoPageScrollTimer;
}

@property(retain, nonatomic) NSTimer *autoPageScrollTimer; // @synthesize autoPageScrollTimer=_autoPageScrollTimer;
@property(copy, nonatomic) NSString *previousPageKey; // @synthesize previousPageKey=_previousPageKey;
@property(nonatomic) BOOL connectionComplete; // @synthesize connectionComplete=_connectionComplete;
@property(retain, nonatomic) WFDisplayConfiguration *pendingConfiguration; // @synthesize pendingConfiguration=_pendingConfiguration;
@property(retain, nonatomic) WFDisplayConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) NSLock *configurationLock; // @synthesize configurationLock=_configurationLock;
@property(retain, nonatomic) WFDisplayPage *currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) int sensorSubType; // @synthesize sensorSubType=_sensorSubType;
@property(nonatomic) BOOL sleepOnDisconnect; // @synthesize sleepOnDisconnect=_sleepOnDisconnect;
@property unsigned char currentPageBinaryKeyBeforeAlert; // @synthesize currentPageBinaryKeyBeforeAlert=_currentPageBinaryKeyBeforeAlert;
@property(copy) NSString *currentPageKeyBeforeAlert; // @synthesize currentPageKeyBeforeAlert=_currentPageKeyBeforeAlert;
@property(copy) NSArray *recomendedPageKeysToUpdate; // @synthesize recomendedPageKeysToUpdate=_recomendedPageKeysToUpdate;
@property(retain, nonatomic) id <WFDisplayConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)setCurrentElevation:(double)arg1;
- (BOOL)setStandardPressure:(double)arg1;
- (BOOL)setShouldSleepOnDisconnect:(BOOL)arg1;
- (BOOL)getDateTimeFormats;
- (BOOL)setDateFormat:(int)arg1 timeFormat:(int)arg2 startDayOfWeek:(int)arg3 watchfaceStyle:(int)arg4;
- (BOOL)setDeviceDate:(id)arg1 timeZone:(id)arg2;
- (BOOL)setHidden:(BOOL)arg1 forElementsWithKey:(id)arg2;
- (BOOL)setFrame:(struct CGRect)arg1 forElementsWithKey:(id)arg2;
- (BOOL)setValue:(id)arg1 forElementsWithKey:(id)arg2;
- (void)updatePendingElements;
- (void)endUpdatesCompletion:(CDUnknownBlockType)arg1;
- (void)endUpdates;
- (void)beginForcedUpdates;
- (void)beginUpdates;
- (BOOL)playSoundWithKey:(id)arg1;
- (BOOL)getDisplayInverted;
- (BOOL)setDisplayInverted:(BOOL)arg1;
- (BOOL)setBacklightOn:(unsigned char)arg1;
- (void)loadConfiguration:(id)arg1;
- (BOOL)showPageWithKey:(id)arg1 timeout:(double)arg2;
- (void)hideAlertPage;
- (void)dispatchPageChangedKey:(id)arg1;
- (void)setCurrentPageWithBinaryKey:(unsigned char)arg1;
- (void)previousPage;
- (void)nextPage;
- (void)autoPageScroll;
- (BOOL)setAutoPageScrollWithDelay:(double)arg1;
- (id)currentPageKey;
- (void)prepareForDisconnect;
- (void)prepareForDelete;
- (void)dealloc;
- (id)init;

@end

