//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBPeripheralDelegate.h"

@class CBPeripheral;

@interface WFBTLEServiceProcessor : NSObject <CBPeripheralDelegate>
{
    id <WFBTLEServiceDelegate> serviceDelegate;
    CBPeripheral *btlePeripheral;
    int sensorType;
    BOOL hasData;
    double lastMessageTime;
    BOOL isConnectionProcessDone;
}

@property(readonly, nonatomic) BOOL isConnectionProcessDone; // @synthesize isConnectionProcessDone;
@property(readonly, nonatomic) BOOL hasData; // @synthesize hasData;
@property(readonly, nonatomic) CBPeripheral *btlePeripheral; // @synthesize btlePeripheral;
@property(retain, nonatomic) id <WFBTLEServiceDelegate> serviceDelegate; // @synthesize serviceDelegate;
- (void)reset;
- (BOOL)startUpdatingForService:(id)arg1 onPeripheral:(id)arg2;
- (void)peripheralConnectionInterrupted;
- (id)getRawData;
- (id)getData;
- (void)configureCommonData:(id)arg1;
- (void)prepareForDelete;
- (void)peripheral:(id)arg1 didWriteValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheralDidUpdateRSSI:(id)arg1 error:(id)arg2;
- (id)init;
- (void)dealloc;

@end

