//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, WFBTLEGlucoseConnection, WFBTLEGlucoseData;

@protocol WFBTLEGlucoseDelegate <NSObject>
- (void)glucoseConnection:(WFBTLEGlucoseConnection *)arg1 didReceiveCommandResponse:(int)arg2 responseData:(NSData *)arg3;
- (void)glucoseConnection:(WFBTLEGlucoseConnection *)arg1 didReceiveRecord:(WFBTLEGlucoseData *)arg2;
@end

