//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBikePowerData.h"

@class WFBTLECommonData;

@interface WFBTLEBikePowerData : WFBikePowerData
{
    WFBTLECommonData *btleCommonData;
}

@property(retain, nonatomic) WFBTLECommonData *btleCommonData; // @synthesize btleCommonData;
- (float)fpAccumulatedTorque;
- (id)initWithTime:(double)arg1 wheelTime:(double)arg2 cadenceTime:(double)arg3;
- (id)init;
- (void)dealloc;

@end

