//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFWirelessController.h"

#import "WFBTLEPeripheralConnectionDelegate.h"
#import "WFBTLEPeripheralPoolDelegate.h"

@class NSDictionary, NSLock, NSMutableArray, NSMutableSet, NSSet, NSTimer, WFBTLEPeripheralPool, WFHardwareControllerBTLE;

@interface WFBTLEController : WFWirelessController <WFBTLEPeripheralConnectionDelegate, WFBTLEPeripheralPoolDelegate>
{
    WFHardwareControllerBTLE *hardwareController;
    BOOL hasSensorsWithData;
    NSMutableSet *peripheralConnections;
    NSMutableSet *pendingPeripheralConnections;
    NSMutableArray *scanningInfo;
    id <WFBTLEControllerDelegate> delegate;
    NSTimer *scanTimer;
    double scanInterval;
    BOOL bScanEnabled;
    BOOL bScanning;
    NSMutableSet *scanUUIDs;
    NSDictionary *scanOptions;
    NSLock *scanLock;
    NSLock *scanTimerLock;
    NSLock *scanInfoLock;
    NSLock *scanUUIDLock;
    NSLock *peripheralConnectionsLock;
    WFBTLEPeripheralPool *peripheralPool;
    NSLock *peripheralPoolLock;
    NSLock *pendingPeripheralLock;
}

+ (int)proxmityRangeForRSSI:(id)arg1;
+ (float)rssiLimitFromProximity:(int)arg1;
@property(retain, nonatomic) NSMutableSet *pendingPeripheralConnections; // @synthesize pendingPeripheralConnections;
@property(nonatomic) id <WFBTLEControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSMutableSet *peripheralConnections; // @synthesize peripheralConnections;
@property(retain, nonatomic) WFHardwareControllerBTLE *hardwareController; // @synthesize hardwareController;
- (void)setInterruptedState;
- (void)processRetrievedPeripherals:(id)arg1;
- (void)processDiscoveredPeripheral:(id)arg1 advertisementData:(id)arg2 RSSI:(id)arg3;
- (void)processConnectedPeripherals:(id)arg1;
- (void)processConnectedPeripheral:(id)arg1;
- (void)processDisconnectedPeripheral:(id)arg1;
- (void)processFailedPeripheralConnection:(id)arg1;
- (BOOL)resetAllSensorData;
@property(readonly, nonatomic) BOOL hasSensorsWithData;
- (void)perpareForDelete;
- (void)stopScanning;
- (void)startScanning;
- (void)stopScanTimer;
- (void)startScanTimer;
- (id)scanInfoForConnection:(id)arg1;
- (BOOL)stopScanningForConnection:(id)arg1;
- (void)scanForPeripherals:(id)arg1;
- (void)retrievePeripheralForConnection:(id)arg1;
- (void)removeScanInfoForConnection:(id)arg1;
- (void)handleScanTimeout:(id)arg1;
- (void)deleteExtraDeviceByUUIDPeripheralsForConnection:(id)arg1 connectedDeviceUUID:(id)arg2;
- (void)checkPeripheralForMatch:(id)arg1;
@property(readonly, nonatomic) NSSet *peripheralsInPool;
- (id)requestSensorConnection:(id)arg1 withProximity:(int)arg2 error:(id *)arg3;
- (id)getConnectionFromParams:(id)arg1;
- (id)getSensorConnections:(int)arg1;
- (void)connectionDidClose:(id)arg1;
- (void)connectionDidDisconnect:(id)arg1;
- (void)connectionDidConnect:(id)arg1;
- (BOOL)peripheralConnection:(id)arg1 retrievePeripheralWithDeviceUUIDs:(id)arg2;
- (BOOL)peripheralConnection:(id)arg1 retrievePeripheralWithServiceUUIDInfo:(id)arg2;
- (BOOL)peripheralConnection:(id)arg1 retrievePeripheralWithSensorType:(int)arg2;
- (void)peripheralPool:(id)arg1 peripheralIsReady:(id)arg2;
- (void)peripheralPool:(id)arg1 didRemoveConnection:(id)arg2 forPeripheral:(id)arg3;
- (void)peripheralPool:(id)arg1 didAddConnection:(id)arg2 forPeripheral:(id)arg3;
- (void)peripheralPool:(id)arg1 didUpdateRSSI:(float)arg2 forPeripheral:(id)arg3;
- (void)peripheralPool:(id)arg1 didDiscoverServicesForPeripheral:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (void)dealloc;

@end

