//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFBTLEWeightScaleUser : NSObject
{
    int _user_id;
    BOOL _c_initial_left;
    BOOL _c_initial_middle;
    BOOL _c_initial_right;
    float _user_range_min_weight_kg;
    float _user_range_max_weight_kg;
    float _user_goal_weight_kg;
    float _tolerance_kg;
    int _height_in_cm;
}

+ (id)userRecordWithInitials:(id)arg1 minWeight:(float)arg2 maxWeight:(float)arg3 height:(float)arg4 goalWeight:(float)arg5 gainLossTolerance:(float)arg6;
@property(nonatomic) int height_in_cm; // @synthesize height_in_cm=_height_in_cm;
@property(nonatomic) float tolerance_kg; // @synthesize tolerance_kg=_tolerance_kg;
@property(nonatomic) float user_goal_weight_kg; // @synthesize user_goal_weight_kg=_user_goal_weight_kg;
@property(nonatomic) float user_range_max_weight_kg; // @synthesize user_range_max_weight_kg=_user_range_max_weight_kg;
@property(nonatomic) float user_range_min_weight_kg; // @synthesize user_range_min_weight_kg=_user_range_min_weight_kg;
@property(nonatomic) BOOL c_initial_right; // @synthesize c_initial_right=_c_initial_right;
@property(nonatomic) BOOL c_initial_middle; // @synthesize c_initial_middle=_c_initial_middle;
@property(nonatomic) BOOL c_initial_left; // @synthesize c_initial_left=_c_initial_left;
@property(nonatomic) int user_id; // @synthesize user_id=_user_id;
- (id)init;
- (void)dealloc;

@end

