//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"
#import "WFHRBurnBurstResultsDelegate.h"

@class UBERUser, UIAlertView;

@interface WFBurnBurstTestBaseVC : UIViewController <WFHRBurnBurstResultsDelegate, UIAlertViewDelegate>
{
    BOOL _initialIdleTimerSetting;
    UBERUser *_user;
    int _burnHR;
    int _burstHR;
    UIAlertView *_doneAlert;
}

@property(nonatomic) BOOL initialIdleTimerSetting; // @synthesize initialIdleTimerSetting=_initialIdleTimerSetting;
@property(retain, nonatomic) UIAlertView *doneAlert; // @synthesize doneAlert=_doneAlert;
@property(nonatomic) int burstHR; // @synthesize burstHR=_burstHR;
@property(nonatomic) int burnHR; // @synthesize burnHR=_burnHR;
@property(retain, nonatomic) UBERUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)resultsVCWillDismiss:(id)arg1;
- (void)exitAnimated:(BOOL)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)saveNumbers;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

