//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCalculator.h"

@class WFDataSet;

@interface WFCadenceCalculator : WFCalculator
{
    unsigned int sampleCount;
    double lastTimestamp;
    double lastDataTime;
    BOOL lastIsWorkoutActive;
    CDStruct_170271e9 currentOffsets;
    CDStruct_170271e9 offsets;
    CDStruct_170271e9 pauseOffsets;
    BOOL isWorkoutActive;
    WFDataSet *dataSet;
}

@property(readonly, nonatomic) BOOL isWorkoutActive; // @synthesize isWorkoutActive;
@property(readonly, nonatomic) WFDataSet *dataSet; // @synthesize dataSet;
- (void).cxx_destruct;
- (void)addBikePowerSample:(id)arg1;
- (void)addBikeCadenceSample:(id)arg1;
- (void)addSample:(id)arg1;
- (void)setAvgDuration:(int)arg1;
- (id)init;

@end

