//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, WFCalculator;

@interface WFCalculatorWorkout : NSObject
{
    WFCalculator *workoutCalculator;
    NSMutableArray *lapCalculators;
}

- (void).cxx_destruct;
- (void)beginSegment;
- (void)beginWorkout;
- (void)addSample:(id)arg1;
- (id)configuredCalculator;
- (id)calculatorForLapNumber:(unsigned int)arg1;
- (id)previousLap;
- (id)lap;
- (id)workout;
- (id)calculator;
- (id)init;

@end

