//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@interface WFCasioBasicSettingsCh : WFCharacteristicDecoder
{
}

- (BOOL)sendAutoLightEnabled:(BOOL)arg1;
- (BOOL)send12hrEnabled:(int)arg1 keySoundEnabled:(int)arg2 autoLightEnabled:(int)arg3 tapKeyEnabled:(int)arg4 powerSavingEnabled:(int)arg5 beepForAlarmEnabled:(int)arg6 vibrateForAlramEnabled:(int)arg7 lightForAlaramEnabled:(int)arg8;
- (BOOL)decodeCharacteristicData;

@end

