//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFCalorieData : WFSensorData
{
    unsigned short usBurnRate;
    unsigned short usTotalCalories;
    unsigned short usElapsedTime;
    int confidence;
    unsigned short usAvgBurnRate;
    unsigned short usSmartCal;
}

@property(nonatomic) unsigned short usSmartCal; // @synthesize usSmartCal;
@property(nonatomic) unsigned short usAvgBurnRate; // @synthesize usAvgBurnRate;
@property(nonatomic) int confidence; // @synthesize confidence;
@property(nonatomic) unsigned short usElapsedTime; // @synthesize usElapsedTime;
@property(nonatomic) unsigned short usTotalCalories; // @synthesize usTotalCalories;
@property(nonatomic) unsigned short usBurnRate; // @synthesize usBurnRate;

@end

