//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface WFConnectorSettings : NSObject
{
    NSString *settingsDirectory;
    NSMutableDictionary *settingsRoot;
}

+ (int)sensorTypeFromKeyString:(id)arg1;
+ (id)keyFromSensorType:(int)arg1;
- (void)setApplicationName:(id)arg1 forSensor:(int)arg2 subType:(int)arg3;
- (BOOL)saveConnectionInfo:(id)arg1;
- (BOOL)removeDeviceParams:(id)arg1 forSensorType:(int)arg2;
- (id)deviceParamsForSensorType:(int)arg1;
- (id)connectionParamsForSensorType:(int)arg1;
@property(nonatomic) BOOL useMetricUnits;
@property(nonatomic) double staleDataTimeout;
@property(nonatomic) NSString *staleDataString;
@property(nonatomic) float bikeWheelCircumference;
@property(nonatomic) double discoveryTimeout;
@property(nonatomic) double searchTimeout;
@property(nonatomic) double bikeCoastingTimeout;
- (id)settings;
- (id)sensorSettings;
- (void)saveSettings;
- (BOOL)isPairedSensorType:(int)arg1;
- (id)applicationLibraryDirectory;
- (id)applicationDocumentsDirectory;
- (id)init;
- (void)dealloc;

@end

