//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFJSONCoding.h"

@class NSData, WFDeviceParams;

@interface WFConnectionParams : NSObject <WFJSONCoding>
{
    int deviceIndex;
    int sensorType;
    int sensorSubType;
    int specifiedNetwork;
    unsigned short searchTimeout;
    WFDeviceParams *device1;
    WFDeviceParams *device2;
    WFDeviceParams *device3;
    WFDeviceParams *device4;
    NSData *conditionalData;
    int conditionalComparisonType;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) int conditionalComparisonType; // @synthesize conditionalComparisonType;
@property(retain, nonatomic) NSData *conditionalData; // @synthesize conditionalData;
@property(retain, nonatomic) WFDeviceParams *device4; // @synthesize device4;
@property(retain, nonatomic) WFDeviceParams *device3; // @synthesize device3;
@property(retain, nonatomic) WFDeviceParams *device2; // @synthesize device2;
@property(retain, nonatomic) WFDeviceParams *device1; // @synthesize device1;
@property(nonatomic) unsigned short searchTimeout; // @synthesize searchTimeout;
@property(nonatomic) int sensorSubType; // @synthesize sensorSubType;
@property(nonatomic) int sensorType; // @synthesize sensorType;
- (BOOL)hasDeviceUUID:(id)arg1;
- (BOOL)hasDeviceNumber:(unsigned short)arg1;
@property(nonatomic) int networkType;
@property(readonly, nonatomic) BOOL isWildcard;
@property(readonly, nonatomic) BOOL isConnectionConditional;
- (id)init;
- (void)dealloc;
- (BOOL)hasBTLEDevice;
- (id)subParamsForNetworkType:(int)arg1;
- (BOOL)hasNetworkType:(int)arg1;
- (BOOL)hasAnotherDevice;
- (id)nextDevice;
- (id)firstDevice;
- (id)devices;
- (unsigned char)deviceCount;
- (int)currentDeviceIndex;

@end

