//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFControlPointDecoder.h"

@class NSString;

@interface WFConnectionControlPointCh : WFControlPointDecoder
{
    BOOL _connectionInProgress;
    unsigned char _connectionID;
    id <WFConnectionControlPointChDelegate> _delegate;
    NSString *_appUUID;
    NSString *_deviceName;
    NSString *_appName;
}

@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(copy, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
@property(copy, nonatomic) NSString *appUUID; // @synthesize appUUID=_appUUID;
@property(nonatomic) unsigned char connectionID; // @synthesize connectionID=_connectionID;
@property(nonatomic) BOOL connectionInProgress; // @synthesize connectionInProgress=_connectionInProgress;
@property(nonatomic) id <WFConnectionControlPointChDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)sendSoftwareReset;
- (BOOL)sendConnectionConfirm;
- (BOOL)setConnectionAppName:(id)arg1;
- (BOOL)setConnectionDeviceName:(id)arg1;
- (BOOL)setConnectionAppUUID:(id)arg1;
- (BOOL)sendConnectionConfirmForRole:(int)arg1 deviceName:(id)arg2 appUUID:(id)arg3 appName:(id)arg4;
- (BOOL)sendResponseToOpCode:(int)arg1 withStatus:(int)arg2;
- (BOOL)decodeOpcodeResponse:(char *)arg1;
- (BOOL)decodeConnectionConfirm:(char *)arg1;
- (BOOL)decodeCharacteristicData;

@end

