//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFControlPointDecoder.h"

@interface WFCPMControlPointCh : WFControlPointDecoder
{
    BOOL bResponseSuccess;
    unsigned char ucResponseStatus;
    int eResponse;
    unsigned short usStrainTicks;
    BOOL scTemperature;
    float reportedCrankLength;
}

@property(readonly, nonatomic) float reportedCrankLength; // @synthesize reportedCrankLength;
@property(readonly, nonatomic) BOOL scTemperature; // @synthesize scTemperature;
@property(readonly, nonatomic) unsigned short usStrainTicks; // @synthesize usStrainTicks;
@property(readonly, nonatomic) int eResponse; // @synthesize eResponse;
@property(readonly, nonatomic) unsigned char ucResponseStatus; // @synthesize ucResponseStatus;
@property(readonly, nonatomic) BOOL bResponseSuccess; // @synthesize bResponseSuccess;
- (BOOL)sendReadCrankLengthRequest;
- (BOOL)sendSetCrankLengthRequest:(float)arg1;
- (BOOL)sendManualZeroRequest;
- (void)didReceivePacketACK;
- (void)processCPMCommandResponse;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (id)init;
- (void)dealloc;

@end

