//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@class WFTimestamp;

@interface WFCPMPowerMeasurementCh : WFCharacteristicDecoder
{
    BOOL dataInitialized;
    BOOL decoderReinitialized;
    BOOL hasPedalPowerBalance;
    BOOL hasTorqueFromCrank;
    BOOL hasExtremeForceMagnitudes;
    BOOL hasExtremeTorqueMagnitudes;
    BOOL hasExtremeAngles;
    BOOL hasTopDeadSpotAngle;
    BOOL hasBottomDeadSpotAngle;
    BOOL hasAccumulatedEnergy;
    BOOL hasOffsetCompensation;
    BOOL hasSpeedData;
    BOOL hasCadenceData;
    BOOL hasLeftPedalPower;
    BOOL hasAccumTorque;
    short ssInstPower;
    unsigned char ucPedalPowerBalance;
    unsigned long ulAccumTorque;
    unsigned short usPreviousAccumTorque;
    CDStruct_340e9e35 stCBSCPage0Data;
    CDStruct_340e9e35 stPrevCBSCPage0Data;
    CDStruct_2929c278 stCalculatedData;
    WFTimestamp *timestampSpeed;
    WFTimestamp *timestampCadence;
    double lastDataTime;
    double lastWheelDataTime;
    double lastCadenceDataTime;
}

@property(readonly, nonatomic) double lastCadenceDataTime; // @synthesize lastCadenceDataTime;
@property(readonly, nonatomic) double lastWheelDataTime; // @synthesize lastWheelDataTime;
@property(readonly, nonatomic) double lastDataTime; // @synthesize lastDataTime;
@property(readonly, nonatomic) WFTimestamp *timestampCadence; // @synthesize timestampCadence;
@property(readonly, nonatomic) WFTimestamp *timestampSpeed; // @synthesize timestampSpeed;
@property(readonly, nonatomic) CDStruct_2929c278 stCalculatedData; // @synthesize stCalculatedData;
@property(readonly, nonatomic) CDStruct_8abe0896 stPrevCBSCPage0Data; // @synthesize stPrevCBSCPage0Data;
@property(readonly, nonatomic) CDStruct_8abe0896 stCBSCPage0Data; // @synthesize stCBSCPage0Data;
@property(readonly, nonatomic) unsigned long ulAccumTorque; // @synthesize ulAccumTorque;
@property(readonly, nonatomic) unsigned char ucPedalPowerBalance; // @synthesize ucPedalPowerBalance;
@property(readonly, nonatomic) short ssInstPower; // @synthesize ssInstPower;
@property(readonly, nonatomic) BOOL hasAccumTorque; // @synthesize hasAccumTorque;
@property(readonly, nonatomic) BOOL hasLeftPedalPower; // @synthesize hasLeftPedalPower;
@property(readonly, nonatomic) BOOL hasCadenceData; // @synthesize hasCadenceData;
@property(readonly, nonatomic) BOOL hasSpeedData; // @synthesize hasSpeedData;
@property(readonly, nonatomic) BOOL hasOffsetCompensation; // @synthesize hasOffsetCompensation;
@property(readonly, nonatomic) BOOL hasAccumulatedEnergy; // @synthesize hasAccumulatedEnergy;
@property(readonly, nonatomic) BOOL hasBottomDeadSpotAngle; // @synthesize hasBottomDeadSpotAngle;
@property(readonly, nonatomic) BOOL hasTopDeadSpotAngle; // @synthesize hasTopDeadSpotAngle;
@property(readonly, nonatomic) BOOL hasExtremeAngles; // @synthesize hasExtremeAngles;
@property(readonly, nonatomic) BOOL hasExtremeTorqueMagnitudes; // @synthesize hasExtremeTorqueMagnitudes;
@property(readonly, nonatomic) BOOL hasExtremeForceMagnitudes; // @synthesize hasExtremeForceMagnitudes;
@property(readonly, nonatomic) BOOL hasTorqueFromCrank; // @synthesize hasTorqueFromCrank;
@property(readonly, nonatomic) BOOL hasPedalPowerBalance; // @synthesize hasPedalPowerBalance;
- (void)updateCalculatedValues:(unsigned short)arg1;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (void)reinitializeWithCharacteristic:(id)arg1 peripheral:(id)arg2 updateType:(int)arg3;
- (id)init;
- (void)dealloc;

@end

