//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDateFormatter, WFWorkout;

@interface WFDataNormalizer2 : NSObject
{
    double workoutStart;
    double workoutEnd;
    int totalSeconds;
    NSArray *normalizeBikeSpeedSamples;
    NSArray *normalizeBikeCadenceSamples;
    NSArray *normalizeBikePowerSamples;
    NSArray *normalizeFootpodSamples;
    NSArray *normalizeHeartrateSamples;
    NSArray *normalizeAtmosPressureSamples;
    NSArray *normalizeMotionAnalysisSamples;
    NSArray *normalizeLocationSamples;
    NSDateFormatter *stravaDateFormatter;
    WFWorkout *workout;
}

@property(readonly, nonatomic) int totalSeconds; // @synthesize totalSeconds;
@property(nonatomic) __weak WFWorkout *workout; // @synthesize workout;
- (void).cxx_destruct;
- (void)normalizeSampelsTest;
- (id)normalizeMotionAnalysisSamples;
- (id)normalizeAtmosPressureSamples;
- (id)normalizeLocationSamples;
- (id)normalizeHeartrateSamples;
- (id)normalizeFootpodSamples;
- (id)normalizeBikePowerSamples;
- (id)normalizeBikeCadenceSamples;
- (id)normalizeBikeSpeedSamples;
- (void)exportNike:(id)arg1;
- (BOOL)exportStravaJSONV3:(id)arg1;
- (id)exportRideWithGPSTrackPointsForWorkout;
- (BOOL)exportStravaJSON_temp:(id)arg1;
- (BOOL)exportStravaJSON:(id)arg1;
- (void)exportDailymileDictionary:(id)arg1 metric:(BOOL)arg2;
- (id)dailyMileTimeString;
- (id)dailyMileDateString;
- (id)dailyMileDateFormatter;
- (id)stravaDateStringFromDate:(id)arg1;
- (id)stravaDateFormatter;
- (void)exportRunkeeper:(id)arg1;
- (void)exportGPX:(id)arg1;
- (void)exportTCX:(id)arg1;
- (void)exportPWX:(id)arg1;
- (void)exportCSV:(id)arg1;
- (id)initWithWorkout:(id)arg1;

@end

