//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, _WFSensorConnection;

@protocol WFDebugDelegate <NSObject>
- (void)connection:(_WFSensorConnection *)arg1 didReceiveStopDebugModeResponse:(BOOL)arg2;
- (void)connection:(_WFSensorConnection *)arg1 didReceiveDebugModeResponse:(BOOL)arg2;
- (void)connection:(_WFSensorConnection *)arg1 didReceiveDebugData:(NSData *)arg2;
@end

