//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSError, NSString, NSTimeZone, WFDisplayConfiguration, WFDisplayConnection;

@protocol WFDisplayConnectionDelegate <NSObject>
- (void)displayConnection:(WFDisplayConnection *)arg1 didFailConfigurationLoadingWithError:(NSError *)arg2;
- (void)displayConnectionDidFinishConfigurationLoading:(WFDisplayConnection *)arg1;
- (void)displayConnection:(WFDisplayConnection *)arg1 didProgressConfigurationLoading:(float)arg2;
- (void)displayConnectionDidStartConfigurationLoading:(WFDisplayConnection *)arg1;
- (void)displayConnection:(WFDisplayConnection *)arg1 visablePageChanged:(NSString *)arg2;
- (void)displayConnection:(WFDisplayConnection *)arg1 didButtonUp:(int)arg2;
- (void)displayConnection:(WFDisplayConnection *)arg1 didButtonDown:(int)arg2;
- (WFDisplayConfiguration *)configurationForDisplayConnection:(WFDisplayConnection *)arg1;

@optional
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondShouldSleepOnDisconnect:(BOOL)arg2 error:(NSError *)arg3;
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondDateFormat:(int)arg2 timeFormat:(int)arg3 startDayOfWeek:(int)arg4 watchfaceStyle:(int)arg5 error:(NSError *)arg6;
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondAutoPageScrollWithDelay:(double)arg2 error:(NSError *)arg3;
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondDate:(NSDate *)arg2 timeZone:(NSTimeZone *)arg3 error:(NSError *)arg4;
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondPageVisableWithKey:(NSString *)arg2 error:(NSError *)arg3;
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondDisplayInverted:(BOOL)arg2 error:(NSError *)arg3;
- (void)displayConnection:(WFDisplayConnection *)arg1 didRespondBacklightOn:(BOOL)arg2 error:(NSError *)arg3;
@end

