//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFDisplayPageRenderProtocol.h"

@class UIImage;

@interface WFDisplayPageCasioRender : NSObject <WFDisplayPageRenderProtocol>
{
    BOOL _inverted;
    int _sensorSubType;
    UIImage *_pageImage;
}

+ (id)displayPageRenderWithSubtype:(int)arg1;
@property(retain, nonatomic) UIImage *pageImage; // @synthesize pageImage=_pageImage;
@property(nonatomic) BOOL inverted; // @synthesize inverted=_inverted;
@property(nonatomic) int sensorSubType; // @synthesize sensorSubType=_sensorSubType;
- (void)drawDisplayElements:(id)arg1;
- (void)clearDisplay;
- (id)image;
- (void)drawDisplayPage:(id)arg1;
- (id)stringForLowerSegmentPart2:(id)arg1;
- (id)stringForLowerSegmentPart1:(id)arg1;
- (id)stringForUpperSegment:(id)arg1;

@end

