//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDisplayElement.h"

@class NSArray, NSMutableArray, NSString;

@interface WFDisplayElementGroup : WFDisplayElement
{
    NSMutableArray *_mutableElements;
    NSString *_groupId;
}

+ (id)instanceFromDictionary:(id)arg1;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(retain, nonatomic) NSMutableArray *mutableElements; // @synthesize mutableElements=_mutableElements;
- (void)removeAllElements;
- (void)removeElement:(id)arg1;
- (void)addElement:(id)arg1;
@property(readonly, nonatomic) NSArray *elements;
- (id)binaryRepresentationForVersion:(int)arg1;
- (id)dictionaryRepresentation;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *errors; // @dynamic errors;

@end

