//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDisplayElement.h"

@class NSMutableArray, NSString;

@interface WFDisplayElementString : WFDisplayElement
{
    int _font;
    int _align;
    NSString *_value;
    BOOL _bold;
    int _color;
    BOOL _constant;
    int _maxLength;
    int _location;
}

+ (id)instanceFromDictionary:(id)arg1;
@property(nonatomic) int location; // @synthesize location=_location;
@property(nonatomic) int maxLength; // @synthesize maxLength=_maxLength;
@property(copy) NSString *value; // @synthesize value=_value;
@property(nonatomic, getter=isConstant) BOOL constant; // @synthesize constant=_constant;
@property(nonatomic) int color; // @synthesize color=_color;
@property(nonatomic, getter=isBold) BOOL bold; // @synthesize bold=_bold;
@property(nonatomic) int align; // @synthesize align=_align;
@property(nonatomic) int font; // @synthesize font=_font;
- (id)binaryRepresentationForVersion:(int)arg1;
- (id)binaryRepresentationForVersion3:(int)arg1;
- (id)binaryRepresentationForVersion1or2:(int)arg1;
- (id)updateDataForProperty:(int)arg1;
- (id)dictionaryRepresentation;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *errors; // @dynamic errors;

@end

