//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@class WFBTLECommonData;

@interface WFDisplayData : WFSensorData
{
    int _visablePageIndex;
    WFBTLECommonData *btleCommonData;
    double temperature;
    BOOL _pressureSupported;
    BOOL _temperatureSupported;
    double _currentPressure;
    double _standardPressure;
    double _elevation;
}

@property(nonatomic) double elevation; // @synthesize elevation=_elevation;
@property(nonatomic) double standardPressure; // @synthesize standardPressure=_standardPressure;
@property(nonatomic) double currentPressure; // @synthesize currentPressure=_currentPressure;
@property(nonatomic, getter=isTemperatureSupported) BOOL temperatureSupported; // @synthesize temperatureSupported=_temperatureSupported;
@property(nonatomic, getter=isPressureSupported) BOOL pressureSupported; // @synthesize pressureSupported=_pressureSupported;
@property(nonatomic) double temperature; // @synthesize temperature;
@property(nonatomic) int visablePageIndex; // @synthesize visablePageIndex=_visablePageIndex;
@property(retain, nonatomic) WFBTLECommonData *btleCommonData; // @synthesize btleCommonData;
- (void)dealloc;
- (id)init;

@end

