//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFEnumLookupEngine.h"

@interface WFDisplaySystemKeys : WFEnumLookupEngine
{
}

+ (id)stringValueForDisplaySystemSoundCasioKey:(int)arg1;
+ (int)integerValueForCaseInsensitiveDisplaySystemSoundCasioKey:(id)arg1;
+ (int)integerValueForDisplaySystemSoundCasioKey:(id)arg1;
+ (id)lowerCaseLookupForKeyDisplaySystemSoundCasioKey;
+ (id)invertedLookupForDisplaySystemSoundCasioKey;
+ (id)lookupForDisplaySystemSoundCasioKey;
+ (id)stringValueForDisplaySystemSoundKey:(int)arg1;
+ (int)integerValueForCaseInsensitiveDisplaySystemSoundKey:(id)arg1;
+ (int)integerValueForDisplaySystemSoundKey:(id)arg1;
+ (id)lowerCaseLookupForKeyDisplaySystemSoundKey;
+ (id)invertedLookupForDisplaySystemSoundKey;
+ (id)lookupForDisplaySystemSoundKey;
+ (id)stringValueForDisplaySystemStringKey:(int)arg1;
+ (int)integerValueForCaseInsensitiveDisplaySystemStringKey:(id)arg1;
+ (int)integerValueForDisplaySystemStringKey:(id)arg1;
+ (id)lowerCaseLookupForKeyDisplaySystemStringKey;
+ (id)invertedLookupForDisplaySystemStringKey;
+ (id)lookupForDisplaySystemStringKey;

@end

