//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDisplayMemoryCalculator.h"

@interface WFDisplayMemoryCalculatorRFLKTv1 : WFDisplayMemoryCalculator
{
}

- (unsigned int)flashSizeForDisplayPage:(id)arg1;
- (unsigned int)flashSizeforDisplayConfiguration:(id)arg1;
- (unsigned int)flashAvailible;
- (unsigned int)ramSizeForDisplayPage:(id)arg1;
- (unsigned int)ramSizeforDisplayConfiguration:(id)arg1;
- (unsigned int)ramAvailible;

@end

