//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSMutableArray, NSString;

@interface WFDisplayPage : NSObject <NSCopying>
{
    NSString *_key;
    BOOL _hidden;
    NSString *_comment;
    NSMutableArray *_mutableElements;
    unsigned char _binaryKey;
    unsigned char _nextPageBinaryKey;
    unsigned char _previousPageBinaryKey;
    NSMutableArray *_errors;
    unsigned char _soundBinaryKey;
    NSString *_soundKey;
    int _soundSource;
}

+ (id)instanceFromDictionary:(id)arg1;
@property(nonatomic) unsigned char soundBinaryKey; // @synthesize soundBinaryKey=_soundBinaryKey;
@property(nonatomic) int soundSource; // @synthesize soundSource=_soundSource;
@property(copy, nonatomic) NSString *soundKey; // @synthesize soundKey=_soundKey;
@property(nonatomic) unsigned char previousPageBinaryKey; // @synthesize previousPageBinaryKey=_previousPageBinaryKey;
@property(nonatomic) unsigned char nextPageBinaryKey; // @synthesize nextPageBinaryKey=_nextPageBinaryKey;
@property(nonatomic, getter=isHidden) BOOL hidden; // @synthesize hidden=_hidden;
@property(retain, nonatomic) NSMutableArray *errors; // @synthesize errors=_errors;
@property(retain, nonatomic) NSMutableArray *mutableElements; // @synthesize mutableElements=_mutableElements;
@property(copy, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(nonatomic) unsigned char binaryKey; // @synthesize binaryKey=_binaryKey;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (id)errorForInvalidObjectKind:(id)arg1 forKey:(id)arg2;
- (id)errorForSetValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)removeAllElements;
- (void)removeElement:(id)arg1;
- (void)addElement:(id)arg1;
@property(readonly, nonatomic) NSArray *elements;
- (id)allElements;
- (id)binaryRepresentationForVersion:(int)arg1;
- (id)dictionaryRepresentation;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

