//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDynamicTableViewController.h"

@class NSArray, UBERSensor;

@interface WFDisplayConfigTVC : WFDynamicTableViewController
{
    NSArray *_workoutProfiles;
    UBERSensor *_sensor;
}

@property(retain, nonatomic) UBERSensor *sensor; // @synthesize sensor=_sensor;
@property(retain, nonatomic) NSArray *workoutProfiles; // @synthesize workoutProfiles=_workoutProfiles;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;

@end

