//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIImage, WFDisplayPage;

@protocol WFDisplayPageRenderProtocol <NSObject>
+ (id)displayPageRenderWithSubtype:(int)arg1;
@property(nonatomic) int sensorSubType;
@property(nonatomic) BOOL inverted;
- (void)drawDisplayPage:(WFDisplayPage *)arg1;
- (void)drawDisplayElements:(NSArray *)arg1;
- (void)clearDisplay;
- (UIImage *)image;
@end

