//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@class WFCommonData;

@interface WFEBikeSpecializedData : WFSensorData
{
    WFCommonData *commonData;
    unsigned short hardwareVersionBattery;
    unsigned short hardwareVersionRemote;
    unsigned short hardwareVersionLight;
    unsigned short hardwareVersionMotor;
    unsigned short firmwareVersionBattery;
    unsigned short firmwareVersionRemote;
    unsigned short firmwareVersionLight;
    unsigned short firmwareVersionMotor;
    unsigned char regenModePercent;
    unsigned char ECOModePercent;
    unsigned char eCOModePercent;
    short motorTemperature;
    short batteryTempature;
    float batteryVoltage;
    unsigned char maxSpeedPedelecFast;
    unsigned char maxSpeedPedelecSlow;
    unsigned char maxSpeedThrottleFast;
    unsigned char maxSpeedThrottleSlow;
    unsigned char maxPedelecSpeed;
    unsigned char maxThrottleSpeed;
    float accelEco;
    float accelPerformance;
    unsigned short motorDriveCommend;
    unsigned char configNibble;
    float powerOutput;
    float batteryCurrent;
    unsigned short remainingRange;
    unsigned char configWord;
    float currentSpeed;
}

@property(nonatomic) float currentSpeed; // @synthesize currentSpeed;
@property(nonatomic) unsigned short remainingRange; // @synthesize remainingRange;
@property(nonatomic) float batteryCurrent; // @synthesize batteryCurrent;
@property(nonatomic) float powerOutput; // @synthesize powerOutput;
@property(nonatomic) unsigned char configWord; // @synthesize configWord;
@property(nonatomic) unsigned short motorDriveCommend; // @synthesize motorDriveCommend;
@property(nonatomic) float accelPerformance; // @synthesize accelPerformance;
@property(nonatomic) float accelEco; // @synthesize accelEco;
@property(nonatomic) unsigned char maxThrottleSpeed; // @synthesize maxThrottleSpeed;
@property(nonatomic) unsigned char maxPedelecSpeed; // @synthesize maxPedelecSpeed;
@property(nonatomic) unsigned char maxSpeedThrottleSlow; // @synthesize maxSpeedThrottleSlow;
@property(nonatomic) unsigned char maxSpeedThrottleFast; // @synthesize maxSpeedThrottleFast;
@property(nonatomic) unsigned char maxSpeedPedelecSlow; // @synthesize maxSpeedPedelecSlow;
@property(nonatomic) unsigned char maxSpeedPedelecFast; // @synthesize maxSpeedPedelecFast;
@property(nonatomic) float batteryVoltage; // @synthesize batteryVoltage;
@property(nonatomic) short batteryTempature; // @synthesize batteryTempature;
@property(nonatomic) short motorTemperature; // @synthesize motorTemperature;
@property(nonatomic) unsigned char ECOModePercent; // @synthesize ECOModePercent;
@property(nonatomic) unsigned char regenModePercent; // @synthesize regenModePercent;
@property(nonatomic) unsigned short firmwareVersionMotor; // @synthesize firmwareVersionMotor;
@property(nonatomic) unsigned short firmwareVersionLight; // @synthesize firmwareVersionLight;
@property(nonatomic) unsigned short firmwareVersionRemote; // @synthesize firmwareVersionRemote;
@property(nonatomic) unsigned short firmwareVersionBattery; // @synthesize firmwareVersionBattery;
@property(nonatomic) unsigned short hardwareVersionMotor; // @synthesize hardwareVersionMotor;
@property(nonatomic) unsigned short hardwareVersionLight; // @synthesize hardwareVersionLight;
@property(nonatomic) unsigned short hardwareVersionRemote; // @synthesize hardwareVersionRemote;
@property(nonatomic) unsigned short hardwareVersionBattery; // @synthesize hardwareVersionBattery;
@property(readonly, nonatomic) WFCommonData *commonData; // @synthesize commonData;
- (void)dealloc;
- (id)init;

@end

