//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@class WFCommonData;

@interface WFEBikeRawData : WFSensorData
{
    WFCommonData *commonData;
    unsigned char assistModesSupported;
    unsigned char regenModesSupported;
    unsigned short wheelCircumference;
}

@property(nonatomic) unsigned short wheelCircumference; // @synthesize wheelCircumference;
@property(nonatomic) unsigned char regenModesSupported; // @synthesize regenModesSupported;
@property(nonatomic) unsigned char assistModesSupported; // @synthesize assistModesSupported;
@property(readonly, nonatomic) WFCommonData *commonData; // @synthesize commonData;
- (id)init;
- (void)dealloc;

@end

