//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorConnection.h"

@interface WFFalcoEBikeConnection : WFSensorConnection
{
}

- (BOOL)setCurrentLimit:(unsigned char)arg1 speedLimit:(unsigned char)arg2 powerLimit:(unsigned char)arg3;
- (BOOL)setLockOn:(BOOL)arg1;
- (BOOL)setCruiseOn:(BOOL)arg1;
- (BOOL)setTurboOn:(BOOL)arg1;
- (BOOL)setRegenLevel:(unsigned char)arg1;
- (BOOL)setPowerLevel:(unsigned char)arg1;
- (id)getFalcoEBikeRawData;
- (id)getFalcoEBikeData;
- (id)falcoEBikeSensor;
- (id)init;

@end

