//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFFalcoEBikeData : WFSensorData
{
    float currentSpeed;
    unsigned char current;
    unsigned char voltage;
    unsigned char power;
    unsigned char torque;
    unsigned char temperature;
    unsigned char powerLevel;
    unsigned char regenLevel;
    BOOL isTurboModeOn;
    BOOL isCruiseModeOn;
    BOOL isLocked;
}

@property(nonatomic) BOOL isLocked; // @synthesize isLocked;
@property(nonatomic) BOOL isCruiseModeOn; // @synthesize isCruiseModeOn;
@property(nonatomic) BOOL isTurboModeOn; // @synthesize isTurboModeOn;
@property(nonatomic) unsigned char regenLevel; // @synthesize regenLevel;
@property(nonatomic) unsigned char powerLevel; // @synthesize powerLevel;
@property(nonatomic) unsigned char temperature; // @synthesize temperature;
@property(nonatomic) unsigned char torque; // @synthesize torque;
@property(nonatomic) unsigned char power; // @synthesize power;
@property(nonatomic) unsigned char voltage; // @synthesize voltage;
@property(nonatomic) unsigned char current; // @synthesize current;
@property(nonatomic) float currentSpeed; // @synthesize currentSpeed;
- (id)init;
- (void)dealloc;

@end

