//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFFitMessageBase.h"

@interface WFFitMessageBloodPressure : WFFitMessageBase
{
    CDStruct_0ea0e030 stBloodPressure;
}

@property(readonly, nonatomic) unsigned short systolicPressure;
@property(readonly, nonatomic) CDStruct_0ea0e030 *pstBloodPressure;
@property(readonly, nonatomic) unsigned short heartRate;
@property(readonly, nonatomic) unsigned short diastolicPressure;
- (id)initWithRecord:(void *)arg1;
- (unsigned long)getTimestampFromStructure;
- (id)init;
- (void)dealloc;

@end

