//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFFitMesgFileId : NSObject
{
    CDStruct_6fa72116 stFileId;
}

@property(readonly, nonatomic) CDStruct_6fa72116 *pstFileId;
- (id)initWithRecord:(void *)arg1;
- (id)init;
- (void)dealloc;

@end

