//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFFitParser : NSObject
{
}

+ (id)parseSettingsFit:(id)arg1;
+ (id)parseActivityFit:(id)arg1 cancelPointer:(char *)arg2 sendProgressToDelegate:(id)arg3;
+ (id)parseFit:(id)arg1 cancelPointer:(char *)arg2 sendProgressToDelegate:(id)arg3;
+ (unsigned long)getTimestampFromDate:(id)arg1;
+ (id)getDateFromTimestamp:(unsigned long)arg1;
+ (id)fitReferenceDate;

@end

