//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFFitMesgDeviceSettings : NSObject
{
    struct {
        unsigned int utc_offset;
    } stDeviceSettings;
}

@property(readonly, nonatomic) CDStruct_6238c8e0 *pstDeviceSettings;
- (id)initWithRecord:(void *)arg1;
- (id)init;
- (void)dealloc;

@end

