//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFFitnessEquipmentData : WFSensorData
{
    int equipmentType;
    int equipmentState;
    float accumTime;
    unsigned long accumDistance;
    float instSpeed;
    unsigned char heartrate;
    unsigned long heartrateAccumBeatCount;
    double heartrateTimestamp;
    unsigned char lapNumber;
    float lastLapAccumTime;
    unsigned char treadmillCadence;
    float treadmillAccumNegVertDist;
    float treadmillAccumPosVertDist;
    float ellipticalAccumPosVertDist;
    unsigned long ellipticalAccumStrides;
    unsigned char ellipticalCadence;
    unsigned short ellipticalInstPower;
    unsigned char bikeCadence;
    double bikeCadenceTimestamp;
    unsigned long bikeAccumCrankRevolutions;
    unsigned short bikeInstPower;
    float bikeAccumTorque;
    double bikeTimestamp;
    unsigned long rowerAccumStrokes;
    unsigned char rowerCadence;
    unsigned short rowerInstPower;
    unsigned char debugRawElapsedTime;
    unsigned char debugNewElapsedTime;
    unsigned char debugRawElapsedDistance;
    unsigned short debugRawSpeed;
}

@property(nonatomic) unsigned short debugRawSpeed; // @synthesize debugRawSpeed;
@property(nonatomic) unsigned char debugRawElapsedDistance; // @synthesize debugRawElapsedDistance;
@property(nonatomic) unsigned char debugNewElapsedTime; // @synthesize debugNewElapsedTime;
@property(nonatomic) unsigned char debugRawElapsedTime; // @synthesize debugRawElapsedTime;
@property(nonatomic) unsigned short rowerInstPower; // @synthesize rowerInstPower;
@property(nonatomic) unsigned char rowerCadence; // @synthesize rowerCadence;
@property(nonatomic) unsigned long rowerAccumStrokes; // @synthesize rowerAccumStrokes;
@property(nonatomic) double bikeTimestamp; // @synthesize bikeTimestamp;
@property(nonatomic) float bikeAccumTorque; // @synthesize bikeAccumTorque;
@property(nonatomic) unsigned short bikeInstPower; // @synthesize bikeInstPower;
@property(nonatomic) unsigned long bikeAccumCrankRevolutions; // @synthesize bikeAccumCrankRevolutions;
@property(nonatomic) double bikeCadenceTimestamp; // @synthesize bikeCadenceTimestamp;
@property(nonatomic) unsigned char bikeCadence; // @synthesize bikeCadence;
@property(nonatomic) unsigned short ellipticalInstPower; // @synthesize ellipticalInstPower;
@property(nonatomic) unsigned char ellipticalCadence; // @synthesize ellipticalCadence;
@property(nonatomic) unsigned long ellipticalAccumStrides; // @synthesize ellipticalAccumStrides;
@property(nonatomic) float ellipticalAccumPosVertDist; // @synthesize ellipticalAccumPosVertDist;
@property(nonatomic) float treadmillAccumPosVertDist; // @synthesize treadmillAccumPosVertDist;
@property(nonatomic) float treadmillAccumNegVertDist; // @synthesize treadmillAccumNegVertDist;
@property(nonatomic) unsigned char treadmillCadence; // @synthesize treadmillCadence;
@property(nonatomic) float lastLapAccumTime; // @synthesize lastLapAccumTime;
@property(nonatomic) unsigned char lapNumber; // @synthesize lapNumber;
@property(nonatomic) double heartrateTimestamp; // @synthesize heartrateTimestamp;
@property(nonatomic) unsigned long heartrateAccumBeatCount; // @synthesize heartrateAccumBeatCount;
@property(nonatomic) unsigned char heartrate; // @synthesize heartrate;
@property(nonatomic) float instSpeed; // @synthesize instSpeed;
@property(nonatomic) unsigned long accumDistance; // @synthesize accumDistance;
@property(nonatomic) float accumTime; // @synthesize accumTime;
@property(nonatomic) int equipmentState; // @synthesize equipmentState;
@property(nonatomic) int equipmentType; // @synthesize equipmentType;

@end

