//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFFitMesgUserProfile : NSObject
{
    CDStruct_9006d996 stUserProfile;
}

@property(readonly, nonatomic) CDStruct_9006d996 *pstUserProfile;
- (id)initWithRecord:(void *)arg1;
- (id)init;
- (void)dealloc;

@end

