//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorConnection.h"

#import "WFTreadmillDelegate.h"

@interface WFFootpodConnection : WFSensorConnection <WFTreadmillDelegate>
{
    id <WFTreadmillDelegate> treadmillDelegate;
}

- (BOOL)treadmillReadWorkoutType;
- (BOOL)treadmillSetWorkoutType:(int)arg1;
- (BOOL)treadmillReadWorkoutTime;
- (BOOL)treadmillSetWorkoutTime:(double)arg1;
- (BOOL)treadmillReadIncline;
- (BOOL)treadmillSetIncline:(float)arg1;
- (BOOL)treadmillReadMode;
- (BOOL)treadmillSetMode:(int)arg1;
- (id)getFootpodRawData;
- (id)getFootpodData;
- (id)rscService;
@property(retain, nonatomic) id <WFTreadmillDelegate> treadmillDelegate;
- (void)disconnect;
- (void)setConnectionStatus:(int)arg1;
- (void)fpConnection:(id)arg1 didReceiveReadWorkoutTypeResponse:(int)arg2 status:(int)arg3;
- (void)fpConnection:(id)arg1 didReceiveReadWorkoutTimeResponse:(double)arg2 status:(int)arg3;
- (void)fpConnection:(id)arg1 didReceiveReadInclineResponse:(float)arg2 status:(int)arg3;
- (void)fpConnection:(id)arg1 didReceiveReadModeResponse:(int)arg2 status:(int)arg3;
- (void)fpConnection:(id)arg1 didReceiveCommandResponse:(int)arg2 status:(int)arg3;
- (id)init;
- (void)dealloc;

@end

