//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFFitDeviceManager.h"

@interface WFGarminFitWatchManager : WFFitDeviceManager
{
}

- (id)deviceName;
- (id)stringFromDeviceType:(int)arg1;
- (int)deviceTypeFromClientDeviceType:(unsigned short)arg1;
- (BOOL)setDeviceParams:(CDStruct_f17dbfdc *)arg1;
- (void)antFS:(id)arg1 receivedResponse:(int)arg2;
- (id)init;

@end

