//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFFitDeviceManager.h"

@interface WFGarminFR405Manager : WFFitDeviceManager
{
}

- (BOOL)setDeviceParams:(CDStruct_f17dbfdc *)arg1;
- (id)init;

@end

