//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFAntDevice.h"

@class WFGeoCacheProgramData;

@interface WFGeoCacheSensor : WFAntDevice
{
    unsigned char ucFirstHintPage;
    unsigned char ucLastHintPage;
    unsigned char ucVisitPageNumber;
    float fpTransferPercent;
    BOOL bReceivedBeacon;
    BOOL bAuthRequestSent;
    BOOL bAuthReceived;
    BOOL bVisitsUpdated;
    BOOL bIsDeviceProgrammed;
    BOOL bIsProgramming;
    BOOL bResetDevice;
    unsigned char aucProgramData[255];
    unsigned char ucProgramPage;
    WFGeoCacheProgramData *programData;
    unsigned char aucDataBuffer[255];
    unsigned char aucPage0Data[10];
    struct {
        unsigned char ucPinLSB;
        unsigned char ucPinByte1;
        unsigned char ucPinByte2;
        unsigned char ucPinMSB;
        unsigned char ucTotalPages;
    } stPage1Data;
    unsigned long ulLatitude;
    unsigned long ulLongitude;
    unsigned long ulTimestamp;
    unsigned short usNumberVisits;
    struct {
        unsigned char ucAuthTokenLSB;
        unsigned char ucAuthTokenByte1;
        unsigned char ucAuthTokenByte2;
        unsigned char ucAuthTokenByte3;
        unsigned char ucAuthTokenByte4;
        unsigned char ucAuthTokenByte5;
        unsigned char ucAuthTokenMSB;
    } stPage32Data;
}

- (BOOL)updateLoggedVisits;
- (float)transferPercent;
- (BOOL)sendAuthenticationRequest;
- (BOOL)requestPIN;
- (BOOL)requestPage:(unsigned char)arg1;
- (BOOL)programNextPage;
- (int)programDevice:(id)arg1;
- (void)reset;
- (BOOL)processEvent:(unsigned char)arg1 messageBuffer:(char *)arg2;
- (BOOL)processMessage:(char *)arg1;
- (id)getRawData;
- (id)getData;
- (void)dealloc;
- (id)init;

@end

