//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@interface WFGlucoseMeasurementCh : WFCharacteristicDecoder
{
    BOOL hasTimeOffset;
    BOOL hasSample;
    BOOL hasStatus;
    BOOL hasContext;
    unsigned short usSequence;
    double baseTime;
    short ssTimeOffset;
    float concentration;
    unsigned char ucSampleType;
    unsigned char ucSampleLocation;
    unsigned short usStatus;
}

@property(readonly, nonatomic) unsigned short usStatus; // @synthesize usStatus;
@property(readonly, nonatomic) unsigned char ucSampleLocation; // @synthesize ucSampleLocation;
@property(readonly, nonatomic) unsigned char ucSampleType; // @synthesize ucSampleType;
@property(readonly, nonatomic) float concentration; // @synthesize concentration;
@property(readonly, nonatomic) short ssTimeOffset; // @synthesize ssTimeOffset;
@property(readonly, nonatomic) double baseTime; // @synthesize baseTime;
@property(readonly, nonatomic) unsigned short usSequence; // @synthesize usSequence;
@property(readonly, nonatomic) BOOL hasContext; // @synthesize hasContext;
@property(readonly, nonatomic) BOOL hasStatus; // @synthesize hasStatus;
@property(readonly, nonatomic) BOOL hasSample; // @synthesize hasSample;
@property(readonly, nonatomic) BOOL hasTimeOffset; // @synthesize hasTimeOffset;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (id)init;

@end

