//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, WFDeviceInformation, WFHardwareConnector, WFSensorConnection;

@protocol WFHardwareConnectorDelegate <NSObject>

@optional
- (void)hardwareConnector:(WFHardwareConnector *)arg1 hasFirmwareUpdateAvailableForConnection:(WFSensorConnection *)arg2 required:(BOOL)arg3 withWahooUtilityAppURL:(NSURL *)arg4;
- (void)hardwareConnectorHasData;
- (void)hardwareConnector:(WFHardwareConnector *)arg1 stateChanged:(int)arg2;
- (void)hardwareConnector:(WFHardwareConnector *)arg1 disconnectedSensor:(WFSensorConnection *)arg2;
- (void)hardwareConnector:(WFHardwareConnector *)arg1 didLooseDiscoveredDevice:(WFDeviceInformation *)arg2;
- (void)hardwareConnector:(WFHardwareConnector *)arg1 didDiscoverDevice:(WFDeviceInformation *)arg2;
- (void)hardwareConnector:(WFHardwareConnector *)arg1 connectedSensor:(WFSensorConnection *)arg2;
@end

