//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class WFFisicaInfo, _WFHardwareController;

@protocol WFHardwareControllerDelegate
- (BOOL)hardwareControllerReset;
- (void)hardwareControllerDeviceDisconnected:(_WFHardwareController *)arg1;
- (void)hardwareController:(_WFHardwareController *)arg1 connectedDevice:(WFFisicaInfo *)arg2;
@end

