//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@interface WFHeartrateData : WFSensorData
{
    unsigned short beatTime;
    unsigned char computedHeartrate;
    unsigned long accumBeatCount;
    double timestamp;
    BOOL timestampOverflow;
}

@property(nonatomic) BOOL timestampOverflow; // @synthesize timestampOverflow;
@property(nonatomic) double timestamp; // @synthesize timestamp;
@property(nonatomic) unsigned long accumBeatCount; // @synthesize accumBeatCount;
@property(nonatomic) unsigned char computedHeartrate; // @synthesize computedHeartrate;
@property(nonatomic) unsigned short beatTime; // @synthesize beatTime;
- (id)formattedHeartrate:(BOOL)arg1;

@end

