//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCalculator.h"

@class WFDataSet, WFZoneCalculator;

@interface WFHeartrateCalculator : WFCalculator
{
    unsigned int sampleCount;
    double lastTimestamp;
    double lastDataTime;
    BOOL lastIsWorkoutActive;
    CDStruct_4b6a4f4b currentOffsets;
    CDStruct_4b6a4f4b offsets;
    CDStruct_4b6a4f4b pauseOffsets;
    BOOL isWorkoutActive;
    BOOL userIsMale;
    WFDataSet *dataSet;
    WFZoneCalculator *zoneCalculator;
    WFZoneCalculator *burnBurstCalculator;
    float calories;
    float calorieBurnRate;
    unsigned int heartrate;
    float userWeight;
    float userAge;
}

@property(nonatomic) BOOL userIsMale; // @synthesize userIsMale;
@property(nonatomic) float userAge; // @synthesize userAge;
@property(nonatomic) float userWeight; // @synthesize userWeight;
@property(readonly, nonatomic) BOOL isWorkoutActive; // @synthesize isWorkoutActive;
@property(nonatomic) unsigned int heartrate; // @synthesize heartrate;
@property(readonly, nonatomic) float calorieBurnRate; // @synthesize calorieBurnRate;
@property(readonly, nonatomic) float calories; // @synthesize calories;
@property(readonly, nonatomic) WFZoneCalculator *burnBurstCalculator; // @synthesize burnBurstCalculator;
@property(readonly, nonatomic) WFZoneCalculator *zoneCalculator; // @synthesize zoneCalculator;
@property(readonly, nonatomic) WFDataSet *dataSet; // @synthesize dataSet;
- (void).cxx_destruct;
- (void)updateCalories:(int)arg1 timestamp:(double)arg2;
- (void)addHeartrateSample:(id)arg1;
- (void)addSample:(id)arg1;
- (void)setAvgDuration:(int)arg1;
- (id)init;
- (id)stringFromHeartrateCaloriesBurnRate:(CDStruct_e25eb2d1 *)arg1 displayCell:(id)arg2;
- (id)formattedHeartrateCaloriesBurnRate:(CDStruct_e25eb2d1 *)arg1;
- (id)stringFromHeartrateCalories:(CDStruct_e25eb2d1 *)arg1 displayCell:(id)arg2;
- (id)formattedHeartrateCalories:(CDStruct_e25eb2d1 *)arg1;
- (BOOL)shouldDisplayData:(id *)arg1 displaysWhenStale:(BOOL)arg2;

@end

