//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorConnection.h"

#import "TICKRXSensorDelegate.h"

@interface WFHeartrateConnection : WFSensorConnection <TICKRXSensorDelegate>
{
    id <WFHeartrateConnectionTICKRXDelegate> _heartrateConnectionTICKRXDelegate;
}

@property(retain, nonatomic) id <WFHeartrateConnectionTICKRXDelegate> heartrateConnectionTICKRXDelegate; // @synthesize heartrateConnectionTICKRXDelegate=_heartrateConnectionTICKRXDelegate;
- (void)tickrxSensorDidReceiveTapEvent:(unsigned int)arg1;
- (void)tickrxSensorDidCompleteFinishCalibrationModeRequest:(BOOL)arg1 activityTypeInEffect:(int)arg2 results:(id)arg3;
- (void)tickrxSensorDidCompleteBeginCalibrationModeRequest:(BOOL)arg1 activityTypeInEffect:(int)arg2;
- (void)tickrxSensorDidCompleteSetTapTapVibrationPattern:(BOOL)arg1;
- (void)tickrxSensorDidCompleteSetCalibrationOperation:(BOOL)arg1;
- (void)tickrxSensorDidCompleteGetCalibrationOperation:(id)arg1;
- (void)tickrxSensorDidReceiveCurrentSessionTimestamp:(id)arg1;
- (void)tickrxSensorDidReceiveSetTimeResponseWithSuccess:(BOOL)arg1;
- (void)tickrxSensorDidReceiveCurrentActivityTypeSetting:(int)arg1;
- (void)tickrxSensorDidDetectDeviceIsNewerThanSupported;
- (void)tickrxSensorSessionDownloadWasAborted;
- (void)tickrxSensorDidCompleteSessionDownload:(id)arg1;
- (void)tickrxSensorDidProgressSessionDownloadToPercent:(double)arg1;
- (void)tickrxSensorSessionListFetchWasAborted;
- (void)tickrxSensorDidCompleteSessionListFetch:(id)arg1;
- (void)tickrxSensorDidProgressSessionListFetchToCount:(unsigned short)arg1 ofTotal:(unsigned short)arg2;
- (BOOL)setTapTapVibrationPatternWithOnPulseDuration:(double)arg1 offPulseDuration:(double)arg2 onPulseCount:(unsigned char)arg3;
- (BOOL)performVibrationWithPattern:(id)arg1;
- (BOOL)requestFinishMotionAnalysisCalibrationMode;
- (BOOL)requestBeginMotionAnalysisCalibrationMode;
- (BOOL)setMotionAnalysisCalibration:(id)arg1;
- (BOOL)getMotionAnalysisCalibrationForActivityType:(int)arg1;
- (BOOL)changeDeviceActivityModeSetting:(int)arg1;
- (BOOL)requestDeviceActivityModeSetting;
- (BOOL)eraseAllActivitySessions;
- (BOOL)downloadSessionMatchingSummary:(id)arg1;
- (BOOL)requestActivitySessionList;
- (BOOL)abortCurrentDownloadOperation;
- (id)getMotionAnalysisData;
- (double)motionAnalysisLastDataTime;
- (id)btleHeartrateService;
- (void)disconnect;
- (void)setConnectionStatus:(int)arg1;
- (id)getHeartrateRawData;
- (id)getHeartrateData;
- (id)heartrateService;
- (id)init;

@end

