//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFWahooActivitySessionManagementDelegate.h"

@class NSDate, NSDictionary, WFHeartrateConnection, WFWahooMotionAnalysisCalibrationBase;

@protocol WFHeartrateConnectionTICKRXDelegate <WFWahooActivitySessionManagementDelegate>

@optional
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didCompleteSetTapTapVibrationPattern:(BOOL)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didReceiveTapEvent:(unsigned int)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didCompleteFinishCalibrationModeRequest:(BOOL)arg2 activityTypeInEffect:(int)arg3 results:(NSDictionary *)arg4;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didCompleteBeginCalibrationModeRequest:(BOOL)arg2 activityTypeInEffect:(int)arg3;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didCompleteSetCalibrationOperation:(BOOL)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didCompleteGetCalibrationOperation:(WFWahooMotionAnalysisCalibrationBase *)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didReceiveCurrentSessionTimestamp:(NSDate *)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didReceiveSetTimeResponseWithSuccess:(BOOL)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didReceiveCurrentActivityTypeSetting:(int)arg2;
- (void)hrTICKRXConnection:(WFHeartrateConnection *)arg1 didDetectDeviceIsNewerThanSupported:(BOOL)arg2;
@end

