//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCalculatorWorkout.h"

@interface WFHeartrateCalculatorWorkout : WFCalculatorWorkout
{
}

- (void)setZoneCeiling:(int)arg1 zoneVal:(int)arg2;
- (void)configureBurn:(double)arg1 burst:(double)arg2 tolerance:(double)arg3;
- (void)configureZones1:(double)arg1 zone2:(double)arg2 zone3:(double)arg3 zone4:(double)arg4 zone5:(double)arg5;
- (void)configureUserAge:(int)arg1 isMale:(BOOL)arg2 weight:(float)arg3;
- (void)addHeartrateSample:(id)arg1;
- (id)configuredCalculator;
- (void)addSample:(id)arg1;
- (id)calculatorForLapNumber:(unsigned int)arg1;
- (id)previousLap;
- (id)lap;
- (id)workout;

@end

