//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPickerView.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class WFDistanceFormatter;

@interface WFHeightPicker : UIPickerView <UIPickerViewDataSource, UIPickerViewDelegate>
{
    id <WFHeightPickerDelegate> _heightDelegate;
    WFDistanceFormatter *_feetFormatter;
    WFDistanceFormatter *_inchesFormatter;
    double _height;
}

@property(retain, nonatomic) WFDistanceFormatter *inchesFormatter; // @synthesize inchesFormatter=_inchesFormatter;
@property(retain, nonatomic) WFDistanceFormatter *feetFormatter; // @synthesize feetFormatter=_feetFormatter;
@property(nonatomic) __weak id <WFHeightPickerDelegate> heightDelegate; // @synthesize heightDelegate=_heightDelegate;
@property(nonatomic) double height; // @synthesize height=_height;
- (void).cxx_destruct;
- (id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (id)init;

@end

