//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDistanceFormatter.h"

@interface WFHeightFormatter : WFDistanceFormatter
{
}

- (double)heightFromString:(id)arg1;
- (id)stringFromHeight:(double)arg1;
- (id)unitStringFromHeight:(double)arg1;
- (unsigned int)formatterUnitStyle;
- (unsigned int)formatterUnits;
- (id)numberFormatter;
- (id)formatterLocale;

@end

