//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WFHexParser : NSObject
{
    NSMutableArray *programLines;
    unsigned char versionMajor;
    unsigned char versionMinor;
    unsigned char versionRevision;
    unsigned short baseAddress;
}

@property(readonly, nonatomic) unsigned short baseAddress; // @synthesize baseAddress;
@property(readonly, nonatomic) unsigned char versionRevision; // @synthesize versionRevision;
@property(readonly, nonatomic) unsigned char versionMinor; // @synthesize versionMinor;
@property(readonly, nonatomic) unsigned char versionMajor; // @synthesize versionMajor;
@property(readonly, nonatomic) NSMutableArray *programLines; // @synthesize programLines;
- (void)parseVersionLine:(id)arg1;
- (BOOL)parseHexFile:(id)arg1;
- (id)init;
- (void)dealloc;

@end

