//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFHistoryCalendarScrollerCell.h"

@class UILabel, WFActivityBarGraphView;

@interface WFHistoryCalendarScrollerYearCell : WFHistoryCalendarScrollerCell
{
    WFActivityBarGraphView *_barGraphView;
    UILabel *_yearLabel;
}

@property(nonatomic) __weak UILabel *yearLabel; // @synthesize yearLabel=_yearLabel;
@property(nonatomic) __weak WFActivityBarGraphView *barGraphView; // @synthesize barGraphView=_barGraphView;
- (void).cxx_destruct;
- (void)setEndDate:(double)arg1;
- (void)setStartDate:(double)arg1;
- (void)awakeFromNib;

@end

