//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFHistoryDetailPageVC.h"

@class UIButton, UIImageView, UILabel, UISegmentedControl, UIView, WFBurnBurstPieChartView, WFHistoryValueLabel, WFSingleLineChartVC;

@interface WFHistoryDetailPageHeartrate : WFHistoryDetailPageVC
{
    WFSingleLineChartVC *_chart;
    int _viewMode;
    UIView *_burnBurstView;
    UIView *_zonesView;
    UISegmentedControl *_modeControl;
    WFBurnBurstPieChartView *_burnBurstPieChart;
    UILabel *_burnLabel;
    UIImageView *_burnIcon;
    UILabel *_burstLabel;
    UIImageView *_burstIcon;
    WFHistoryValueLabel *_totalTimeCell;
    WFHistoryValueLabel *_burnTimeCell;
    WFHistoryValueLabel *_burstTimeCell;
    WFHistoryValueLabel *_caloriesCell;
    WFHistoryValueLabel *_averageHRCell;
    WFHistoryValueLabel *_maxHRCell;
    UILabel *_notSetLabel;
    UIButton *_notSetButton;
    UIView *_notSetView;
    UIImageView *_notSetBlurredBackground;
}

@property(nonatomic) __weak UIImageView *notSetBlurredBackground; // @synthesize notSetBlurredBackground=_notSetBlurredBackground;
@property(nonatomic) __weak UIView *notSetView; // @synthesize notSetView=_notSetView;
@property(nonatomic) __weak UIButton *notSetButton; // @synthesize notSetButton=_notSetButton;
@property(nonatomic) __weak UILabel *notSetLabel; // @synthesize notSetLabel=_notSetLabel;
@property(nonatomic) __weak WFHistoryValueLabel *maxHRCell; // @synthesize maxHRCell=_maxHRCell;
@property(nonatomic) __weak WFHistoryValueLabel *averageHRCell; // @synthesize averageHRCell=_averageHRCell;
@property(nonatomic) __weak WFHistoryValueLabel *caloriesCell; // @synthesize caloriesCell=_caloriesCell;
@property(nonatomic) __weak WFHistoryValueLabel *burstTimeCell; // @synthesize burstTimeCell=_burstTimeCell;
@property(nonatomic) __weak WFHistoryValueLabel *burnTimeCell; // @synthesize burnTimeCell=_burnTimeCell;
@property(nonatomic) __weak WFHistoryValueLabel *totalTimeCell; // @synthesize totalTimeCell=_totalTimeCell;
@property(nonatomic) __weak UIImageView *burstIcon; // @synthesize burstIcon=_burstIcon;
@property(nonatomic) __weak UILabel *burstLabel; // @synthesize burstLabel=_burstLabel;
@property(nonatomic) __weak UIImageView *burnIcon; // @synthesize burnIcon=_burnIcon;
@property(nonatomic) __weak UILabel *burnLabel; // @synthesize burnLabel=_burnLabel;
@property(nonatomic) __weak WFBurnBurstPieChartView *burnBurstPieChart; // @synthesize burnBurstPieChart=_burnBurstPieChart;
@property(nonatomic) __weak UISegmentedControl *modeControl; // @synthesize modeControl=_modeControl;
@property(nonatomic) __weak UIView *zonesView; // @synthesize zonesView=_zonesView;
@property(nonatomic) __weak UIView *burnBurstView; // @synthesize burnBurstView=_burnBurstView;
@property(nonatomic) int viewMode; // @synthesize viewMode=_viewMode;
- (void).cxx_destruct;
- (void)notSetButtonTouched:(id)arg1;
- (void)populateDataFromWorkout:(id)arg1;
- (id)chart;
- (void)setWorkout:(id)arg1;
- (void)viewModeControlChanged:(id)arg1;
- (void)localize;
- (void)viewDidLoad;

@end

