//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFHistoryDetailPageTVC.h"

@class FKStravaLeaderboard, FKStravaSegmentEffort;

@interface WFHistoryStravaLeaderboardTVC : WFHistoryDetailPageTVC
{
    FKStravaSegmentEffort *_segmentEffort;
    FKStravaLeaderboard *_leaderboard;
}

@property(retain, nonatomic) FKStravaLeaderboard *leaderboard; // @synthesize leaderboard=_leaderboard;
@property(retain, nonatomic) FKStravaSegmentEffort *segmentEffort; // @synthesize segmentEffort=_segmentEffort;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)doneButtonTouched:(id)arg1;
- (void)reloadSegmentLeaderboard;
- (void)viewDidLoad;

@end

