//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFHistoryDetailPageVC.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, UILabel, UITableView, WFSpeedFormatter;

@interface WFHistoryDetailPageLapsVC : WFHistoryDetailPageVC <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    NSArray *_laps;
    UILabel *_distanceTitleLabel;
    UILabel *_paceTitleLabel;
    UILabel *_timeTitleLabel;
    UILabel *_hrTitleLabel;
    WFSpeedFormatter *_speedFormatter;
}

@property(retain, nonatomic) WFSpeedFormatter *speedFormatter; // @synthesize speedFormatter=_speedFormatter;
@property(nonatomic) __weak UILabel *hrTitleLabel; // @synthesize hrTitleLabel=_hrTitleLabel;
@property(nonatomic) __weak UILabel *timeTitleLabel; // @synthesize timeTitleLabel=_timeTitleLabel;
@property(nonatomic) __weak UILabel *paceTitleLabel; // @synthesize paceTitleLabel=_paceTitleLabel;
@property(nonatomic) __weak UILabel *distanceTitleLabel; // @synthesize distanceTitleLabel=_distanceTitleLabel;
@property(retain, nonatomic) NSArray *laps; // @synthesize laps=_laps;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)setupPaceLabel;
- (void)configureViewForWorkout;
- (void)setWorkout:(id)arg1;
- (id)formatterCentre;
- (void)localize;
- (void)viewDidLoad;

@end

