//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFHistoryDetailPageCadenceVC.h"

@class WFHistoryValueLabel;

@interface WFHistoryDetailPageRunningCadenceVC : WFHistoryDetailPageCadenceVC
{
    WFHistoryValueLabel *_groundContactCell;
    WFHistoryValueLabel *_oscillationCell;
}

@property(nonatomic) __weak WFHistoryValueLabel *oscillationCell; // @synthesize oscillationCell=_oscillationCell;
@property(nonatomic) __weak WFHistoryValueLabel *groundContactCell; // @synthesize groundContactCell=_groundContactCell;
- (void).cxx_destruct;
- (void)populateDataFromWorkout:(id)arg1;
- (unsigned int)cadenceUnits;
- (void)localize;
- (void)viewDidLoad;

@end

