//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFHistoryDetailPageVC.h"

@class UILabel, UIView, WFHistoryValueLabel, WFSpeedFormatter;

@interface WFHistoryDetailPageSmoothnessVC : WFHistoryDetailPageVC
{
    WFHistoryValueLabel *_averageSmoothnessCell;
    WFHistoryValueLabel *_minSmoothnessCell;
    WFHistoryValueLabel *_maxSmoothnessCell;
    UIView *_xBar;
    UIView *_yBar;
    UIView *_zBar;
    UILabel *_shockLabel;
    UILabel *_leftRightLabel;
    UILabel *_upDownLabel;
    UILabel *_forwardBackwardLabel;
    UILabel *_smoothnessLabel;
    WFSpeedFormatter *_paceFormatter;
}

@property(retain, nonatomic) WFSpeedFormatter *paceFormatter; // @synthesize paceFormatter=_paceFormatter;
@property(nonatomic) __weak UILabel *smoothnessLabel; // @synthesize smoothnessLabel=_smoothnessLabel;
@property(nonatomic) __weak UILabel *forwardBackwardLabel; // @synthesize forwardBackwardLabel=_forwardBackwardLabel;
@property(nonatomic) __weak UILabel *upDownLabel; // @synthesize upDownLabel=_upDownLabel;
@property(nonatomic) __weak UILabel *leftRightLabel; // @synthesize leftRightLabel=_leftRightLabel;
@property(nonatomic) __weak UILabel *shockLabel; // @synthesize shockLabel=_shockLabel;
@property(nonatomic) __weak UIView *zBar; // @synthesize zBar=_zBar;
@property(nonatomic) __weak UIView *yBar; // @synthesize yBar=_yBar;
@property(nonatomic) __weak UIView *xBar; // @synthesize xBar=_xBar;
@property(nonatomic) __weak WFHistoryValueLabel *maxSmoothnessCell; // @synthesize maxSmoothnessCell=_maxSmoothnessCell;
@property(nonatomic) __weak WFHistoryValueLabel *minSmoothnessCell; // @synthesize minSmoothnessCell=_minSmoothnessCell;
@property(nonatomic) __weak WFHistoryValueLabel *averageSmoothnessCell; // @synthesize averageSmoothnessCell=_averageSmoothnessCell;
- (void).cxx_destruct;
- (void)setFrameForBar:(id)arg1 smoothness:(double)arg2;
- (void)updateShockUIForSmoothness:(double)arg1 x:(double)arg2 y:(double)arg3 z:(double)arg4;
- (void)populateDataFromWorkout:(id)arg1;
- (void)setWorkout:(id)arg1;
- (void)localize;
- (void)viewDidLoad;

@end

