//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface WFHistoryDetailPageLapsCell : UITableViewCell
{
    UILabel *_lapNumberLabel;
    UILabel *_distanceLabel;
    UILabel *_speedLabel;
    UILabel *_timeLabel;
    UILabel *_hrLabel;
}

@property(nonatomic) __weak UILabel *hrLabel; // @synthesize hrLabel=_hrLabel;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *speedLabel; // @synthesize speedLabel=_speedLabel;
@property(nonatomic) __weak UILabel *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(nonatomic) __weak UILabel *lapNumberLabel; // @synthesize lapNumberLabel=_lapNumberLabel;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

