//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class UIButton, UILabel;

@interface WFHistoryDetailSharingHeaderView : UICollectionReusableView
{
    id <WFHistoryDetailSharingHeaderViewDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UIButton *_hideButton;
}

@property(nonatomic) __weak UIButton *hideButton; // @synthesize hideButton=_hideButton;
@property(nonatomic) __weak UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <WFHistoryDetailSharingHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)hideButtonTouched:(id)arg1;

@end

