//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton, UILabel, UIView, WFHomepagePVC;

@interface WFHomepageVC : UIViewController
{
    WFHomepagePVC *_pageViewController;
    UIButton *_sensorsButton;
    UIButton *_historyButton;
    UIButton *_settingsButton;
    UIButton *_workoutButton;
    UILabel *_sensorsLabel;
    UILabel *_historyLabel;
    UILabel *_settingsLabel;
    UILabel *_workoutLabel;
    UIView *_toobarView;
}

@property(nonatomic) __weak UIView *toobarView; // @synthesize toobarView=_toobarView;
@property(nonatomic) __weak UILabel *workoutLabel; // @synthesize workoutLabel=_workoutLabel;
@property(nonatomic) __weak UILabel *settingsLabel; // @synthesize settingsLabel=_settingsLabel;
@property(nonatomic) __weak UILabel *historyLabel; // @synthesize historyLabel=_historyLabel;
@property(nonatomic) __weak UILabel *sensorsLabel; // @synthesize sensorsLabel=_sensorsLabel;
@property(nonatomic) __weak UIButton *workoutButton; // @synthesize workoutButton=_workoutButton;
@property(nonatomic) __weak UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(nonatomic) __weak UIButton *historyButton; // @synthesize historyButton=_historyButton;
@property(nonatomic) __weak UIButton *sensorsButton; // @synthesize sensorsButton=_sensorsButton;
@property(nonatomic) __weak WFHomepagePVC *pageViewController; // @synthesize pageViewController=_pageViewController;
- (void).cxx_destruct;
- (void)infoButtonTapped:(id)arg1;
- (void)workoutButtonTapped:(id)arg1;
- (void)settingsButtonTapped:(id)arg1;
- (void)historyButtonTapped:(id)arg1;
- (void)sensorsButtonTapped:(id)arg1;
- (void)profileButtonTapped:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)updateColorPalette;
- (void)colorPaletteChanged;
- (void)presentFirstRunTutorialAnimated:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)localize;
- (void)presentHistoryViewControllerWithWorkout:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)viewDidLoad;

@end

