//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFPageViewController.h"

#import "WFPageViewControllerDataSource.h"

@interface WFHomepagePVC : WFPageViewController <WFPageViewControllerDataSource>
{
}

- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)storyboardIdentifiers;
- (BOOL)swipeEnabled;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

