//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class MHTextField, UIButton, UILabel, UITableViewCell, UITextView, UIView, WFBasicTableViewCell, WFSensorManager;

@interface WFHRBurnBurstLandingVC : WFStaticTableViewController <UIAlertViewDelegate, UITextFieldDelegate>
{
    UILabel *_heartRateHeaderLabel;
    UILabel *_yourResultsHeaderLabel;
    UILabel *_burnLabel;
    UILabel *_burstLabel;
    MHTextField *_burnValueField;
    MHTextField *_burstValueField;
    UILabel *_burnSubHeading;
    UILabel *_burstSubHeading;
    UIButton *_burnInfoButton;
    UIButton *_burstInfoButton;
    UITextView *_burnDetailedTextView;
    UITextView *_burstDetailedTextView;
    UITableViewCell *_learnMoreCell;
    UITableViewCell *_editMyNumbersCell;
    UITableViewCell *_takeTheTestCell;
    WFBasicTableViewCell *_trainingPlansCell;
    UITableViewCell *_zonesCell;
    WFBasicTableViewCell *_dismissCell;
    WFBasicTableViewCell *_viewCell;
    id <WFHRBurnBurstResultsDelegate> _resultsDelegate;
    UIView *_burnBurstView;
    WFSensorManager *_sensorManager;
}

@property(nonatomic) __weak WFSensorManager *sensorManager; // @synthesize sensorManager=_sensorManager;
@property(retain, nonatomic) UIView *burnBurstView; // @synthesize burnBurstView=_burnBurstView;
@property(nonatomic) __weak id <WFHRBurnBurstResultsDelegate> resultsDelegate; // @synthesize resultsDelegate=_resultsDelegate;
@property(nonatomic) __weak WFBasicTableViewCell *viewCell; // @synthesize viewCell=_viewCell;
@property(nonatomic) __weak WFBasicTableViewCell *dismissCell; // @synthesize dismissCell=_dismissCell;
@property(nonatomic) __weak UITableViewCell *zonesCell; // @synthesize zonesCell=_zonesCell;
@property(retain, nonatomic) WFBasicTableViewCell *trainingPlansCell; // @synthesize trainingPlansCell=_trainingPlansCell;
@property(retain, nonatomic) UITableViewCell *takeTheTestCell; // @synthesize takeTheTestCell=_takeTheTestCell;
@property(retain, nonatomic) UITableViewCell *editMyNumbersCell; // @synthesize editMyNumbersCell=_editMyNumbersCell;
@property(retain, nonatomic) UITableViewCell *learnMoreCell; // @synthesize learnMoreCell=_learnMoreCell;
@property(nonatomic) __weak UITextView *burstDetailedTextView; // @synthesize burstDetailedTextView=_burstDetailedTextView;
@property(nonatomic) __weak UITextView *burnDetailedTextView; // @synthesize burnDetailedTextView=_burnDetailedTextView;
@property(nonatomic) __weak UIButton *burstInfoButton; // @synthesize burstInfoButton=_burstInfoButton;
@property(nonatomic) __weak UIButton *burnInfoButton; // @synthesize burnInfoButton=_burnInfoButton;
@property(retain, nonatomic) UILabel *burstSubHeading; // @synthesize burstSubHeading=_burstSubHeading;
@property(retain, nonatomic) UILabel *burnSubHeading; // @synthesize burnSubHeading=_burnSubHeading;
@property(retain, nonatomic) MHTextField *burstValueField; // @synthesize burstValueField=_burstValueField;
@property(retain, nonatomic) MHTextField *burnValueField; // @synthesize burnValueField=_burnValueField;
@property(retain, nonatomic) UILabel *burstLabel; // @synthesize burstLabel=_burstLabel;
@property(retain, nonatomic) UILabel *burnLabel; // @synthesize burnLabel=_burnLabel;
@property(nonatomic) __weak UILabel *yourResultsHeaderLabel; // @synthesize yourResultsHeaderLabel=_yourResultsHeaderLabel;
@property(nonatomic) __weak UILabel *heartRateHeaderLabel; // @synthesize heartRateHeaderLabel=_heartRateHeaderLabel;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)showBurnBurstWebsite;
- (void)showOnlineTrainingPlans;
- (void)showOnlineTrainingPlansAlert;
- (BOOL)isHRMonitorConnected;
- (void)showAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)populateData;
- (void)burstInfoPressed:(id)arg1;
- (void)burnInfoPressed:(id)arg1;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)enableRightModalDismissButton;
- (void)viewDidLoad;

@end

