//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBurnBurstTestBaseVC.h"

#import "UIAlertViewDelegate.h"

@class UBERUser, UIButton, UILabel, WFSensorHeartrate;

@interface WFHRBurnBurstRestingVC : WFBurnBurstTestBaseVC <UIAlertViewDelegate>
{
    BOOL _testStarted;
    CDStruct_e25eb2d1 _formatOptions;
    UILabel *_heartRateHeaderLabel;
    UILabel *_heartRateLabel;
    UILabel *_instructionLabel;
    UILabel *_countdownLabel;
    UIButton *_skipButton;
    UIButton *_startButton;
    int _restingHR;
    int _startAccumBeats;
    int _seconds;
    WFSensorHeartrate *_heartRateSensor;
}

@property(nonatomic) CDStruct_e25eb2d1 formatOptions; // @synthesize formatOptions=_formatOptions;
@property(nonatomic) BOOL testStarted; // @synthesize testStarted=_testStarted;
@property(retain, nonatomic) WFSensorHeartrate *heartRateSensor; // @synthesize heartRateSensor=_heartRateSensor;
@property(nonatomic) int seconds; // @synthesize seconds=_seconds;
@property(nonatomic) int startAccumBeats; // @synthesize startAccumBeats=_startAccumBeats;
@property(nonatomic) int restingHR; // @synthesize restingHR=_restingHR;
@property(retain, nonatomic) UIButton *startButton; // @synthesize startButton=_startButton;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UILabel *countdownLabel; // @synthesize countdownLabel=_countdownLabel;
@property(retain, nonatomic) UILabel *instructionLabel; // @synthesize instructionLabel=_instructionLabel;
@property(retain, nonatomic) UILabel *heartRateLabel; // @synthesize heartRateLabel=_heartRateLabel;
@property(retain, nonatomic) UILabel *heartRateHeaderLabel; // @synthesize heartRateHeaderLabel=_heartRateHeaderLabel;
- (void).cxx_destruct;
- (void)endMeasurement;
- (void)startMeasurement;
- (void)countdown;
- (void)startTest;
- (void)updateHeartRate;
- (void)resetTest;
- (void)startButtonTouched:(id)arg1;
- (void)saveNumbers;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)skipButtonTouched:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) UBERUser *user;

@end

