//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFJSONCoder : NSObject
{
}

+ (id)valueTransformerForProperty:(id)arg1 inClass:(id)arg2;
+ (id)valueTransformerForClass:(Class)arg1;
+ (id)JSONKeyForProperty:(id)arg1 inClass:(Class)arg2;
+ (id)obejctWithJSONObject:(id)arg1 class:(Class)arg2;
+ (id)JSONObjectWithObject:(id)arg1;
+ (id)obejctWithJSONData:(id)arg1 class:(Class)arg2;
+ (id)JSONDataWithObject:(id)arg1;

@end

