//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@class NSString;

@interface WFJSONCodingTransformer : NSValueTransformer
{
    NSString *_objClassName;
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
+ (id)JSONCodingTranformerForClass:(Class)arg1;
@property(copy, nonatomic) NSString *objClassName; // @synthesize objClassName=_objClassName;
- (void).cxx_destruct;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;

@end

