//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSValueTransformer;

@protocol WFJSONCoding <NSObject>

@optional
+ (id)instanceForJSONObject:(id)arg1;
+ (Class)childClassForArrayWithKey:(NSString *)arg1;
+ (NSValueTransformer *)JSONValueTransformerForClass:(Class)arg1;
+ (NSValueTransformer *)JSONValueTransformerForKey:(NSString *)arg1;
+ (NSDictionary *)JSONKeyPathsByPropertyKey;
- (void)objectWillSerializeWithJSONCoder;
- (void)objectDidLoadWithJSONCoder;
@end

