//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UITextField;

@interface WFKickrBikeTypeCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_cLabelField;
    UITextField *_cTextField;
    UILabel *_crrLabelField;
    UITextField *_crrTextField;
}

@property(retain, nonatomic) UITextField *crrTextField; // @synthesize crrTextField=_crrTextField;
@property(retain, nonatomic) UILabel *crrLabelField; // @synthesize crrLabelField=_crrLabelField;
@property(retain, nonatomic) UITextField *cTextField; // @synthesize cTextField=_cTextField;
@property(retain, nonatomic) UILabel *cLabelField; // @synthesize cLabelField=_cLabelField;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

