//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

#import "WFBikeTrainerDelegate.h"
#import "WFCalibrationVCProtocol.h"
#import "WFSensorBikeTrainerDelegate.h"

@class UBERSensor, UIActivityIndicatorView, UIBarButtonItem, UIImageView, UILabel, UITextView, WFBasicTableViewCell, WFFormSheetController, WFSensorBikePower;

@interface WFKICKRCalibrationVC : WFStaticTableViewController <WFSensorBikeTrainerDelegate, WFBikeTrainerDelegate, WFCalibrationVCProtocol>
{
    BOOL _retry;
    UBERSensor *_sensor;
    WFFormSheetController *_formSheet;
    CDUnknownBlockType _dismissBlock;
    UILabel *_spindownCompleteLabel;
    UILabel *_speedLabel;
    UIActivityIndicatorView *_spindownIndicator;
    UIImageView *_checkMark;
    UITextView *_spindownInstructionsLabel;
    UITextView *_spindownSpeedInstructionsTextView;
    UILabel *_speedHeaderLabel;
    WFBasicTableViewCell *_performSpindownCell;
    WFBasicTableViewCell *_doneCell;
    UIBarButtonItem *_cancelButton;
    WFSensorBikePower *_trainerSensor;
}

@property(retain, nonatomic) WFSensorBikePower *trainerSensor; // @synthesize trainerSensor=_trainerSensor;
@property(nonatomic) BOOL retry; // @synthesize retry=_retry;
@property(nonatomic) __weak UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak WFBasicTableViewCell *doneCell; // @synthesize doneCell=_doneCell;
@property(nonatomic) __weak WFBasicTableViewCell *performSpindownCell; // @synthesize performSpindownCell=_performSpindownCell;
@property(nonatomic) __weak UILabel *speedHeaderLabel; // @synthesize speedHeaderLabel=_speedHeaderLabel;
@property(nonatomic) __weak UITextView *spindownSpeedInstructionsTextView; // @synthesize spindownSpeedInstructionsTextView=_spindownSpeedInstructionsTextView;
@property(nonatomic) __weak UITextView *spindownInstructionsLabel; // @synthesize spindownInstructionsLabel=_spindownInstructionsLabel;
@property(nonatomic) __weak UIImageView *checkMark; // @synthesize checkMark=_checkMark;
@property(nonatomic) __weak UIActivityIndicatorView *spindownIndicator; // @synthesize spindownIndicator=_spindownIndicator;
@property(nonatomic) __weak UILabel *speedLabel; // @synthesize speedLabel=_speedLabel;
@property(nonatomic) __weak UILabel *spindownCompleteLabel; // @synthesize spindownCompleteLabel=_spindownCompleteLabel;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(retain, nonatomic) WFFormSheetController *formSheet; // @synthesize formSheet=_formSheet;
@property(retain, nonatomic) UBERSensor *sensor; // @synthesize sensor=_sensor;
- (void).cxx_destruct;
- (id)speedInstructionText;
- (id)instructionText;
- (void)configureUIForRetry;
- (void)configureUIForComplete;
- (void)doneCellTouched;
- (double)spindownTargetSpeed;
- (void)workoutDidUpdateData;
- (void)disableSpindown;
- (void)kurtTimeout;
- (void)initSpindown;
- (void)cpmConnection:(id)arg1 didReceiveKurtSpindownResult:(unsigned long)arg2;
- (void)cpmConnection:(id)arg1 didReceiveKurtSetProFlywheelEnabled:(BOOL)arg2 spindownEnabled:(BOOL)arg3 response:(BOOL)arg4;
- (void)didReceiveCalibrationResponse:(unsigned char)arg1 offset:(unsigned short)arg2 temperature:(BOOL)arg3;
- (void)didCompleteSpindownWithTime:(float)arg1 temperature:(float)arg2 offset:(unsigned short)arg3;
- (void)didBeginSpindown;
- (void)prepareForUserCalibration;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)showAnimated:(BOOL)arg1;
- (void)cancelButtonTouched:(id)arg1;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

