//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class WFRoundProgressView;

@interface WFLockHUDView : UIView
{
    _Bool _canceled;
    id <WFLockHUDViewDelegate> _delegate;
    WFRoundProgressView *_progressBar;
}

@property(nonatomic) _Bool canceled; // @synthesize canceled=_canceled;
@property(nonatomic) __weak WFRoundProgressView *progressBar; // @synthesize progressBar=_progressBar;
@property(nonatomic) __weak id <WFLockHUDViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateProgress;
- (void)hide;
- (void)show;
- (id)init;

@end

