//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSample.h"

@class NSNumber;

@interface WFLocationSample : WFSample
{
}

+ (id)sampleFromData:(id)arg1 fromSensor:(id)arg2;
- (void)exportCSV:(id)arg1 forSegmentNumber:(int)arg2 workoutStart:(double)arg3;

// Remaining properties
@property(retain, nonatomic) NSNumber *accuracy; // @dynamic accuracy;
@property(retain, nonatomic) NSNumber *altitude; // @dynamic altitude;
@property(retain, nonatomic) NSNumber *distanceOffset; // @dynamic distanceOffset;
@property(retain, nonatomic) NSNumber *latitude; // @dynamic latitude;
@property(retain, nonatomic) NSNumber *longitude; // @dynamic longitude;
@property(retain, nonatomic) NSNumber *speed; // @dynamic speed;
@property(retain, nonatomic) NSNumber *totalDistance; // @dynamic totalDistance;

@end

