//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSTimer, UILabel, WFSpeedFormatter;

@interface WFManualSpeedEntryVC : UIViewController
{
    double speedInputMin;
    double speedInputMax;
    double speedInputStep;
    double speedVal;
    WFSpeedFormatter *speedFormatter;
    BOOL _isVisible;
    id <WFManualSpeedEntryVCDelegate> _delegate;
    UILabel *_labelSpeedHeading;
    UILabel *_labelSpeedValue;
    UILabel *_labelPaceHeading;
    UILabel *_labelPaceValue;
    int _targetButtonRepeatCount;
    NSTimer *_setTargetButtonRepeatTimer;
    double _targetMultiplier;
}

@property(retain, nonatomic) NSTimer *setTargetButtonRepeatTimer; // @synthesize setTargetButtonRepeatTimer=_setTargetButtonRepeatTimer;
@property(nonatomic) int targetButtonRepeatCount; // @synthesize targetButtonRepeatCount=_targetButtonRepeatCount;
@property(nonatomic) double targetMultiplier; // @synthesize targetMultiplier=_targetMultiplier;
@property(nonatomic) __weak UILabel *labelPaceValue; // @synthesize labelPaceValue=_labelPaceValue;
@property(nonatomic) __weak UILabel *labelPaceHeading; // @synthesize labelPaceHeading=_labelPaceHeading;
@property(nonatomic) __weak UILabel *labelSpeedValue; // @synthesize labelSpeedValue=_labelSpeedValue;
@property(nonatomic) __weak UILabel *labelSpeedHeading; // @synthesize labelSpeedHeading=_labelSpeedHeading;
@property(nonatomic) __weak id <WFManualSpeedEntryVCDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL isVisible; // @synthesize isVisible=_isVisible;
- (void).cxx_destruct;
- (void)notifyDelegateOfSpeedChange;
- (void)checkButtonState:(id)arg1;
- (void)stopButtonRepeatTimer;
- (void)startButtonRepeatTimer;
- (void)downButtonTouchDown:(id)arg1;
- (void)upButtonTouchDown:(id)arg1;
- (void)targetButtonTouchOutside:(id)arg1;
- (void)targetButtonTouchInside:(id)arg1;
- (void)changeTargetWithMultiplier:(double)arg1;
- (void)updateLabels;
- (id)speedFormatter;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

