//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, WFMKTileOverlay;

@protocol WFMKTileOverlayCacheSource <NSObject>
- (void)tileOverlay:(WFMKTileOverlay *)arg1 saveTileData:(NSData *)arg2 forPath:(CDStruct_9d955b4a)arg3;
- (void)tileOverlay:(WFMKTileOverlay *)arg1 loadTileAtPath:(CDStruct_9d955b4a)arg2 result:(void (^)(NSData *, NSError *))arg3;
- (BOOL)tileOverlay:(WFMKTileOverlay *)arg1 hasCacheDataAtPath:(CDStruct_9d955b4a)arg2;
@end

