//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKPolylineRenderer.h"

@interface WFMKMultiColorPolylineRenderer : MKPolylineRenderer
{
    BOOL _lowFidelity;
    id <WFMKMultiColorPolylineRendererDelegate> _delegate;
}

@property(nonatomic) BOOL lowFidelity; // @synthesize lowFidelity=_lowFidelity;
@property(nonatomic) id <WFMKMultiColorPolylineRendererDelegate> delegate; // @synthesize delegate=_delegate;
- (void)drawMapRect:(CDStruct_90e2a262)arg1 zoomScale:(float)arg2 inContext:(struct CGContext *)arg3;
- (void)drawCornerWithPoints:(struct CGPoint)arg1:(struct CGPoint)arg2:(struct CGPoint)arg3 width:(float)arg4 color:(id)arg5;
- (void)fillGradientSegmentFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2 fromColor:(id)arg3 toColor:(id)arg4 width:(float)arg5;
- (void)fillSegmentFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2 color:(id)arg3 width:(float)arg4;
- (void)fillCircleWithCenter:(struct CGPoint)arg1 diameter:(float)arg2 color:(id)arg3;
- (id)segmentFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2 width:(float)arg3;
- (id)colorAtIndex:(int)arg1;

@end

