//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSample.h"

@class NSNumber;

@interface WFMotionAnalysisSample : WFSample
{
}

+ (id)insertNewSampleInManagedObjectContext:(id)arg1;
+ (id)sampleFromSensor:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSNumber *cadenceInst; // @dynamic cadenceInst;
@property(retain, nonatomic) NSNumber *groundContactTime; // @dynamic groundContactTime;
@property(retain, nonatomic) NSNumber *motionCount; // @dynamic motionCount;
@property(retain, nonatomic) NSNumber *motionPowerX; // @dynamic motionPowerX;
@property(retain, nonatomic) NSNumber *motionPowerY; // @dynamic motionPowerY;
@property(retain, nonatomic) NSNumber *motionPowerZ; // @dynamic motionPowerZ;
@property(retain, nonatomic) NSNumber *runningSmoothness; // @dynamic runningSmoothness;
@property(retain, nonatomic) NSNumber *verticalOscillation; // @dynamic verticalOscillation;

@end

