//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFMusicLibraryExporter : NSObject
{
    id <WFMusicLibraryExporterDelegate> delegate;
}

- (void).cxx_destruct;
- (void)delegateFailedExport:(id)arg1;
- (void)delegateFininishExport:(id)arg1;
- (void)didFailToExportMediaItem:(id)arg1;
- (void)didFinishExportingMediaItem:(id)arg1 toPath:(id)arg2;
- (void)exportMediaItem:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

