//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBitFieldArray.h"

@interface WFNetworkTypeArray : WFBitFieldArray
{
}

+ (id)fromNetworkTypeEnum:(int)arg1;
- (int)nextNetworkType;
- (id)initWithNetworkTypeEnum:(int)arg1;
- (int)firstNetworkType;
- (void)dealloc;

@end

