//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface WFNewWorkoutDisplayWizardNC : UINavigationController
{
    id <WFNewWorkoutDisplayWizardDelegate> _wizardDelegate;
}

@property(nonatomic) id <WFNewWorkoutDisplayWizardDelegate> wizardDelegate; // @synthesize wizardDelegate=_wizardDelegate;
- (void)returnWithDisplay:(id)arg1;

@end

