//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFWorkoutProfileSelectTVC.h"

@class UIBarButtonItem, WFAnnouncement;

@interface WFNewAnnouncementSelectProfileTVC : WFWorkoutProfileSelectTVC
{
    WFAnnouncement *_announcement;
    UIBarButtonItem *_saveButton;
}

@property(nonatomic) __weak UIBarButtonItem *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) WFAnnouncement *announcement; // @synthesize announcement=_announcement;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)saveButtonTouched:(id)arg1;
- (void)viewDidLoad;

@end

