//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UISegmentedControl, UIToolbar;

@interface WFNewWorkoutProfileContainerVC : UIViewController
{
    UIToolbar *_toolbar;
    UISegmentedControl *_segmentedControl;
}

@property(nonatomic) __weak UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(nonatomic) __weak UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;
- (void)cancelButtonTouched:(id)arg1;
- (void)segmentedControlChanged:(id)arg1;
- (id)profileTVC;
- (void)viewDidLoad;

@end

