//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@interface WFNewAlertCh : WFCharacteristicDecoder
{
}

- (void)sendNewAlertWithCategory:(unsigned int)arg1 count:(unsigned char)arg2 message:(id)arg3;

@end

