//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

@class UBERWorkoutProfile, UIBarButtonItem, UILabel, UITextField;

@interface WFNewWorkoutProfileNameTVC : WFStaticTableViewController
{
    UBERWorkoutProfile *_workoutProfile;
    UILabel *_titleLabel;
    UITextField *_nameField;
    UIBarButtonItem *_nextButton;
}

@property(nonatomic) __weak UIBarButtonItem *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak UITextField *nameField; // @synthesize nameField=_nameField;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UBERWorkoutProfile *workoutProfile; // @synthesize workoutProfile=_workoutProfile;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)goToNextPage;
- (void)textFieldEditingDidEndOnExit:(id)arg1;
- (void)nextButtonTouched:(id)arg1;
- (void)updateColorPalette;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

