//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface WFNewWorkoutProfileWizardNC : UINavigationController
{
    id <WFNewWorkoutProfileWizardDelegate> _wizardDelegate;
}

@property(nonatomic) id <WFNewWorkoutProfileWizardDelegate> wizardDelegate; // @synthesize wizardDelegate=_wizardDelegate;
- (void)returnWithProfile:(id)arg1;

@end

