//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFNormalizedSample : NSObject
{
    int segmentNumber;
    int timeOffset;
    BOOL isWorkoutActive;
}

@property(nonatomic) BOOL isWorkoutActive; // @synthesize isWorkoutActive;
@property(nonatomic) int timeOffset; // @synthesize timeOffset;
@property(nonatomic) int segmentNumber; // @synthesize segmentNumber;

@end

