//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, WFNotificationBar, WFNotificationTask;

@interface WFNotificationController : NSObject
{
    BOOL _paused;
    WFNotificationBar *_statusBarNotification;
    WFNotificationBar *_navigationBarNotification;
    WFNotificationBar *_stickyStatusBarNotification;
    WFNotificationBar *_stickyNavigationBarNotification;
    NSMutableArray *_taskQueue;
    WFNotificationTask *_stickyStatusBarNotificationTask;
    WFNotificationTask *_stickyNotificationBarNotificationTask;
    WFNotificationTask *_currentNotificationTask;
}

+ (void)resumeNotifications;
+ (void)pauseNotifications;
+ (void)queueNotificationTask:(id)arg1;
+ (void)cancelCurrentNotificationTask;
+ (void)cancelAllNotificationTasks;
+ (void)cancelNotificationTask:(id)arg1;
+ (void)showStickyNotificationTask:(id)arg1;
+ (id)sharedController;
@property(nonatomic, getter=isPaused) BOOL paused; // @synthesize paused=_paused;
@property(retain, nonatomic) WFNotificationTask *currentNotificationTask; // @synthesize currentNotificationTask=_currentNotificationTask;
@property(retain, nonatomic) WFNotificationTask *stickyNotificationBarNotificationTask; // @synthesize stickyNotificationBarNotificationTask=_stickyNotificationBarNotificationTask;
@property(retain, nonatomic) WFNotificationTask *stickyStatusBarNotificationTask; // @synthesize stickyStatusBarNotificationTask=_stickyStatusBarNotificationTask;
@property(retain, nonatomic) NSMutableArray *taskQueue; // @synthesize taskQueue=_taskQueue;
@property(retain, nonatomic) WFNotificationBar *stickyNavigationBarNotification; // @synthesize stickyNavigationBarNotification=_stickyNavigationBarNotification;
@property(retain, nonatomic) WFNotificationBar *stickyStatusBarNotification; // @synthesize stickyStatusBarNotification=_stickyStatusBarNotification;
@property(retain, nonatomic) WFNotificationBar *navigationBarNotification; // @synthesize navigationBarNotification=_navigationBarNotification;
@property(retain, nonatomic) WFNotificationBar *statusBarNotification; // @synthesize statusBarNotification=_statusBarNotification;
- (void).cxx_destruct;
- (void)queueTask:(id)arg1;
- (void)checkQueue;
- (void)showTask:(id)arg1;
- (id)notificationBarForStyle:(int)arg1;
- (id)init;

@end

