//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WFOdometerHistory : NSObject
{
    unsigned long aulHistoryBuffer[52];
    float bikeWheelCircumference;
    unsigned long ulCurrentWheelRevolutions;
}

@property(nonatomic) unsigned long ulCurrentWheelRevolutions; // @synthesize ulCurrentWheelRevolutions;
@property(nonatomic) float bikeWheelCircumference; // @synthesize bikeWheelCircumference;
- (void)clearHistoryBuffer;
- (unsigned int *)historyBufferPtr;
- (unsigned long)getWheelRevolutionsForWeek:(unsigned char)arg1;
- (float)getOdometerForWeek:(unsigned char)arg1;
- (float)getDistanceForWeek:(unsigned char)arg1;
- (id)init;
- (void)dealloc;

@end

