//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPageViewControllerDataSource.h"
#import "UIPageViewControllerDelegate.h"

@class UIPageControl, UIPageViewController;

@interface WFPageViewController : UIViewController <UIPageViewControllerDelegate, UIPageViewControllerDataSource>
{
    UIPageControl *_pageControl;
    UIPageViewController *_pageViewController;
    id <WFPageViewControllerDataSource> _dataSource;
}

@property(nonatomic) __weak id <WFPageViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UIPageViewController *pageViewController; // @synthesize pageViewController=_pageViewController;
@property(nonatomic) __weak UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
- (void).cxx_destruct;
- (int)pageViewController:(id)arg1 spineLocationForInterfaceOrientation:(int)arg2;
- (void)pageViewController:(id)arg1 willTransitionToViewControllers:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (unsigned int)indexOfViewController:(id)arg1;
- (id)viewControllerAtIndex:(unsigned int)arg1 storyboard:(id)arg2;
- (void)pageControlChanged:(id)arg1;
- (void)updateViewControllers;
- (void)turnPageBackwards;
- (void)turnPageForwards;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

