//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor, WFPieChart;

@protocol WFPieChartDataSource <NSObject>
- (UIColor *)pieChart:(WFPieChart *)arg1 colorForSegmentAtIndex:(int)arg2;
- (double)pieChart:(WFPieChart *)arg1 valueForSegmentAtIndex:(int)arg2;
- (NSString *)pieChart:(WFPieChart *)arg1 titleForSegmentAtIndex:(int)arg2;
- (int)numberOfSegmentsInPieChart:(WFPieChart *)arg1;
@end

