//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSlidingSet.h"

@class WFDataSet;

@interface WFPowerSet : WFSlidingSet
{
    WFDataSet *normalizingAverages;
    double normalizedPower;
    double criticalPower;
    BOOL normalizedDataValid;
    double sumNormalizedData;
    double elapsedTimeNormalizer;
    double lastDataTime;
    CDStruct_c3b9c2ee *arrayPtr;
    int arraySize;
    int arrayCount;
}

@property(nonatomic) BOOL normalizedDataValid; // @synthesize normalizedDataValid;
@property(readonly, nonatomic) double sumNormalizedData; // @synthesize sumNormalizedData;
@property(readonly, nonatomic) double elapsedTimeNormalizer; // @synthesize elapsedTimeNormalizer;
@property(nonatomic) double criticalPower; // @synthesize criticalPower;
- (void).cxx_destruct;
- (double)intensityFactor;
- (double)tss:(double)arg1;
- (double)normalizedPower;
- (void)restoreNormalizer:(double)arg1 time:(unsigned char)arg2 valid:(BOOL)arg3;
- (void)onLevelCalculate:(unsigned char)arg1;
- (id)initWithPowerSet:(id)arg1;
- (id)init;
- (void)dealloc;
- (int)fillArrayForSize:(int)arg1 pointerToArrayPointer:(struct **)arg2;
- (BOOL)allocMemoryForSize:(int)arg1;

@end

