//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCalculator.h"

@class WFDataSet, WFPowerSet, WFZoneCalculator;

@interface WFPowerCalculator : WFCalculator
{
    unsigned int sampleCount;
    BOOL isWorkoutActive;
    BOOL lastIsWorkoutActive;
    double lastDataTime;
    double lastTimestamp;
    CDStruct_4dc97ad8 currentOffsets;
    CDStruct_4dc97ad8 prevOffsets;
    CDStruct_4dc97ad8 offsets;
    CDStruct_4dc97ad8 pauseOffsets;
    WFPowerSet *powerTimeCalculator;
    WFDataSet *dataSet;
    WFDataSet *torqueDataSet;
    WFDataSet *pedalContributionSet;
    WFZoneCalculator *zoneCalculator;
    double userCriticalPower;
}

@property(nonatomic) double userCriticalPower; // @synthesize userCriticalPower;
@property(readonly, nonatomic) WFZoneCalculator *zoneCalculator; // @synthesize zoneCalculator;
@property(readonly, nonatomic) WFDataSet *pedalContributionSet; // @synthesize pedalContributionSet;
@property(readonly, nonatomic) WFDataSet *torqueDataSet; // @synthesize torqueDataSet;
@property(readonly, nonatomic) WFDataSet *dataSet; // @synthesize dataSet;
@property(retain, nonatomic) WFPowerSet *powerTimeCalculator; // @synthesize powerTimeCalculator;
- (void).cxx_destruct;
- (double)pedalContributionAverage;
- (double)intensityFactor;
- (double)tss:(double)arg1;
- (double)normalizedPower;
- (CDStruct_c3b9c2ee)powerMeanMaxRangeForTime:(int)arg1;
- (int)powerMeanMaxForTime:(int)arg1;
- (int)powerAverageForTime:(int)arg1;
- (double)accumTorque;
- (void)createPowerTimeCalculator:(BOOL)arg1;
- (void)addBikePowerSample:(id)arg1;
- (void)addSample:(id)arg1;
- (id)init;

@end

