//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIColor;

@interface WFProximityRangeView : UIView
{
    UIColor *_onColor;
    UIColor *_offColor;
    NSArray *_bars;
    double _proximityRange;
}

@property(retain, nonatomic) NSArray *bars; // @synthesize bars=_bars;
@property(retain, nonatomic) UIColor *offColor; // @synthesize offColor=_offColor;
@property(retain, nonatomic) UIColor *onColor; // @synthesize onColor=_onColor;
@property(nonatomic) double proximityRange; // @synthesize proximityRange=_proximityRange;
- (void).cxx_destruct;
- (void)setBarHeight:(double)arg1 forBar:(id)arg2;
- (void)configureForNewRange;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

