//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensorData.h"

@class WFBTLECommonData;

@interface WFProximityData : WFSensorData
{
    WFBTLECommonData *btleCommonData;
    int alertLevel;
    int txPowerLevel;
}

@property(nonatomic) int txPowerLevel; // @synthesize txPowerLevel;
@property(nonatomic) int alertLevel; // @synthesize alertLevel;
@property(retain, nonatomic) WFBTLECommonData *btleCommonData; // @synthesize btleCommonData;
- (id)init;
- (void)dealloc;

@end

