//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDynamicTableViewController.h"

@class NSArray, WFSupportUtility;

@interface WFProductHelpTVC : WFDynamicTableViewController
{
    NSArray *_productNames;
    NSArray *_productKeys;
    WFSupportUtility *_supportEmailer;
}

@property(retain, nonatomic) WFSupportUtility *supportEmailer; // @synthesize supportEmailer=_supportEmailer;
@property(retain, nonatomic) NSArray *productKeys; // @synthesize productKeys=_productKeys;
@property(retain, nonatomic) NSArray *productNames; // @synthesize productNames=_productNames;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;

@end

