//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFSessionManagerListener.h"

@class WFNotificationTask;

@interface WFRatingNotificationController : NSObject <WFSessionManagerListener>
{
    WFNotificationTask *_ratingNotification;
}

+ (id)sharedController;
+ (void)load;
@property(retain, nonatomic) WFNotificationTask *ratingNotification; // @synthesize ratingNotification=_ratingNotification;
- (void).cxx_destruct;
- (id)productLinks;
- (void)rateAppStoreTouched:(id)arg1;
- (void)rateAmazonTouched:(id)arg1;
- (void)rateAppleTouched:(id)arg1;
- (void)openURLFromRatingNotificationForKey:(id)arg1;
- (id)shouldShowRatingViewForSensor;
- (void)openAppStoreRating;
- (id)shouldShowAppRatingView;
- (BOOL)tooSoonBetweenRatings;
- (double)acceptableTimeBetweenPrompts;
- (BOOL)shouldShowDebug;
- (void)setTimeOfRatingPrompt;
- (double)timeOfLastRatingPrompt;
- (void)setBool:(BOOL)arg1 withProductKey:(id)arg2 flag:(id)arg3;
- (BOOL)boolWithProductKey:(id)arg1 flag:(id)arg2;
- (id)appStoreProductKey;
- (double)firstWorkoutTime;
- (void)checkRatings;
- (void)sessionRecorder:(id)arg1 didSaveWorkout:(id)arg2;

@end

