//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface WFRoundProgressView : UIView
{
    BOOL _annular;
    float _progress;
    float _startAngle;
    UIColor *_trackColor;
    UIColor *_barColor;
}

@property(retain, nonatomic) UIColor *barColor; // @synthesize barColor=_barColor;
@property(retain, nonatomic) UIColor *trackColor; // @synthesize trackColor=_trackColor;
@property(nonatomic) float startAngle; // @synthesize startAngle=_startAngle;
@property(nonatomic, getter=isAnnular) BOOL annular; // @synthesize annular=_annular;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setDefaultValue;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

