//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@interface WFRSCMeasurementCh : WFCharacteristicDecoder
{
    BOOL hasInstStrideLength;
    BOOL hasTotalDistance;
    BOOL hasWalkingOrRunning;
    float fpInstSpeed;
    unsigned char ucInstCadence;
    float fpStrideLength;
    unsigned long ulAccumulatedDistance;
    unsigned long ulPrevDistance;
    double lastDataTime;
    unsigned long ulCalculatedStrideCount;
}

@property(readonly, nonatomic) double lastDataTime; // @synthesize lastDataTime;
@property(readonly, nonatomic) unsigned long ulCalculatedStrideCount; // @synthesize ulCalculatedStrideCount;
@property(readonly, nonatomic) unsigned long ulAccumulatedDistance; // @synthesize ulAccumulatedDistance;
@property(readonly, nonatomic) float fpStrideLength; // @synthesize fpStrideLength;
@property(readonly, nonatomic) unsigned char ucInstCadence; // @synthesize ucInstCadence;
@property(readonly, nonatomic) float fpInstSpeed; // @synthesize fpInstSpeed;
@property(readonly, nonatomic) BOOL hasWalkingOrRunning; // @synthesize hasWalkingOrRunning;
@property(readonly, nonatomic) BOOL hasTotalDistance; // @synthesize hasTotalDistance;
@property(readonly, nonatomic) BOOL hasInstStrideLength; // @synthesize hasInstStrideLength;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (id)init;
- (void)dealloc;

@end

