//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MZPageViewController.h"

#import "MZPageViewControllerDataSource.h"
#import "MZPageViewControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "WFScrollingTabBarControllerDataSource.h"
#import "WFScrollingTabBarControllerDelegate.h"

@class UICollectionView, UIColor, WFScrollingTabBarCell;

@interface WFScrollingTabBarController : MZPageViewController <MZPageViewControllerDataSource, MZPageViewControllerDelegate, UICollectionViewDelegate, UICollectionViewDataSource, WFScrollingTabBarControllerDataSource, WFScrollingTabBarControllerDelegate>
{
    UICollectionView *_scrollingTabBar;
    id <WFScrollingTabBarControllerDataSource> _tabBarDataSource;
    id <WFScrollingTabBarControllerDelegate> _tabBarDelegate;
    UIColor *_deselectedTabTintColor;
    UIColor *_tintColor;
    WFScrollingTabBarCell *_selectedCell;
}

@property(retain, nonatomic) WFScrollingTabBarCell *selectedCell; // @synthesize selectedCell=_selectedCell;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(retain, nonatomic) UIColor *deselectedTabTintColor; // @synthesize deselectedTabTintColor=_deselectedTabTintColor;
@property(nonatomic) __weak id <WFScrollingTabBarControllerDelegate> tabBarDelegate; // @synthesize tabBarDelegate=_tabBarDelegate;
@property(nonatomic) __weak id <WFScrollingTabBarControllerDataSource> tabBarDataSource; // @synthesize tabBarDataSource=_tabBarDataSource;
@property(nonatomic) __weak UICollectionView *scrollingTabBar; // @synthesize scrollingTabBar=_scrollingTabBar;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)tabBarController:(id)arg1 didSelectTabAtIndex:(int)arg2;
- (id)tabBarController:(id)arg1 selectedTintColorForTabAtIndex:(int)arg2;
- (id)tabBarController:(id)arg1 titleForTabAtIndex:(int)arg2;
- (id)tabBarController:(id)arg1 imageForTabAtIndex:(int)arg2;
- (int)numberOfTabsInTabBarController:(id)arg1;
- (void)pageViewController:(id)arg1 willChangeToViewController:(id)arg2;
- (void)pageViewController:(id)arg1 didChangeViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerForIndex:(unsigned int)arg2;
- (int)numberOfViewContollersInPageViewController:(id)arg1;
- (void)setCurrentPage:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)selectTabAtIndex:(int)arg1 animated:(BOOL)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

