//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFSensorManagerListenerProtocol.h"

@interface WFSensorFirmwareUpdateAlert : NSObject <WFSensorManagerListenerProtocol>
{
}

+ (void)sensorManager:(id)arg1 hasFirmwareUpdateForSensor:(id)arg2 required:(BOOL)arg3 withWahooUtilityAppURL:(id)arg4;

@end

