//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSURL, UILabel, WFSensor;

@interface WFSensorFirmwareNotificationView : UIView
{
    WFSensor *_sensor;
    NSURL *_updateURL;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
}

+ (id)senorFirmwareNotificationViewForSensor:(id)arg1 required:(BOOL)arg2 withWahooUtilityAppURL:(id)arg3;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSURL *updateURL; // @synthesize updateURL=_updateURL;
@property(nonatomic) __weak WFSensor *sensor; // @synthesize sensor=_sensor;
- (void).cxx_destruct;
- (void)updateButtonTouched:(id)arg1;
- (void)remindMeLaterButtonTouched:(id)arg1;

@end

