//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

#import "UITextFieldDelegate.h"

@class MHTextField, NSMutableArray, NSString, UBERAccount, UIActivityIndicatorView, UIBarButtonItem, UIButton, UILabel, UITableViewCell, WFBasicTableViewCell, WFShareActivity, WFSupportUtility;

@interface WFSettingsShareActivityTVC : WFStaticTableViewController <UITextFieldDelegate>
{
    id <WFSettingsShareActivityTVCDelegate> _delegate;
    WFShareActivity *_activity;
    NSString *_backButtonTitle;
    UITableViewCell *_nameCell;
    UITableViewCell *_usernameCell;
    UITableViewCell *_passwordCell;
    UITableViewCell *_authorizeCell;
    WFBasicTableViewCell *_subfolderCell;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_authorizeButton;
    UIBarButtonItem *_backButton;
    UILabel *_nameTitleLabel;
    UILabel *_nameLabel;
    UILabel *_usernameTitleLabel;
    MHTextField *_usernameTextField;
    UILabel *_passwordTitleLabel;
    MHTextField *_passwordTextField;
    UBERAccount *_tempAccount;
    NSMutableArray *_errors;
    WFSupportUtility *_supportEmailer;
}

@property(retain, nonatomic) WFSupportUtility *supportEmailer; // @synthesize supportEmailer=_supportEmailer;
@property(retain, nonatomic) NSMutableArray *errors; // @synthesize errors=_errors;
@property(retain, nonatomic) UBERAccount *tempAccount; // @synthesize tempAccount=_tempAccount;
@property(nonatomic) __weak MHTextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(nonatomic) __weak UILabel *passwordTitleLabel; // @synthesize passwordTitleLabel=_passwordTitleLabel;
@property(nonatomic) __weak MHTextField *usernameTextField; // @synthesize usernameTextField=_usernameTextField;
@property(nonatomic) __weak UILabel *usernameTitleLabel; // @synthesize usernameTitleLabel=_usernameTitleLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *nameTitleLabel; // @synthesize nameTitleLabel=_nameTitleLabel;
@property(retain, nonatomic) UIBarButtonItem *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak UIButton *authorizeButton; // @synthesize authorizeButton=_authorizeButton;
@property(nonatomic) __weak UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) __weak WFBasicTableViewCell *subfolderCell; // @synthesize subfolderCell=_subfolderCell;
@property(nonatomic) __weak UITableViewCell *authorizeCell; // @synthesize authorizeCell=_authorizeCell;
@property(nonatomic) __weak UITableViewCell *passwordCell; // @synthesize passwordCell=_passwordCell;
@property(nonatomic) __weak UITableViewCell *usernameCell; // @synthesize usernameCell=_usernameCell;
@property(nonatomic) __weak UITableViewCell *nameCell; // @synthesize nameCell=_nameCell;
@property(copy, nonatomic) NSString *backButtonTitle; // @synthesize backButtonTitle=_backButtonTitle;
@property(retain, nonatomic) WFShareActivity *activity; // @synthesize activity=_activity;
@property(nonatomic) id <WFSettingsShareActivityTVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)authorizeButtonTouched:(id)arg1;
- (void)subFolderDidChange:(id)arg1;
- (void)showAlertSuccess;
- (void)showErrorAlertWithError:(id)arg1;
- (void)backButtonTouched:(id)arg1;
- (void)enableUI;
- (void)disableUI;
- (void)updateUI;
- (void)updateUsernamePassword;
- (id)errorDetailString;
- (void)deleteCreditial;
- (void)saveCreditial:(id)arg1;
- (id)account;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

