//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDynamicTableViewController.h"

#import "WFSensorManagerListenerProtocol.h"

@class NSMutableArray, UILabel, WFSensorManager;

@interface WFSensorDiscoveryTVC : WFDynamicTableViewController <WFSensorManagerListenerProtocol>
{
    BOOL _helpTimeout;
    NSMutableArray *_discoveredDevices;
    NSMutableArray *_sensors;
    WFSensorManager *_sensorManager;
    UILabel *_searchingLabel;
}

@property(nonatomic) __weak UILabel *searchingLabel; // @synthesize searchingLabel=_searchingLabel;
@property(nonatomic) BOOL helpTimeout; // @synthesize helpTimeout=_helpTimeout;
@property(retain, nonatomic) WFSensorManager *sensorManager; // @synthesize sensorManager=_sensorManager;
@property(retain, nonatomic) NSMutableArray *sensors; // @synthesize sensors=_sensors;
@property(retain, nonatomic) NSMutableArray *discoveredDevices; // @synthesize discoveredDevices=_discoveredDevices;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)sensorManager:(id)arg1 didLoseDevice:(id)arg2;
- (void)sensorManager:(id)arg1 didDiscoverDevice:(id)arg2;
- (void)resetGUI;
- (void)applicaitonWillEnterForground;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)showHelpCell;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)localize;
- (void)viewDidLoad;

@end

