//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensor.h"

@class WFBikeSpeedConnection, WFBikeSpeedData, WFDataSet, WFSlidingSet;

@interface WFSensorBikeSpeed : WFSensor
{
    float wheelCircumference;
    CDStruct_c75e22b1 prevWheelData;
    CDStruct_c75e22b1 prevCrankData;
    CDStruct_b48bc849 currentOffsets;
    CDStruct_b48bc849 lapOffsets;
    CDStruct_b48bc849 prevLapOffsets;
    CDStruct_b48bc849 workoutOffsets;
    CDStruct_b48bc849 pauseOffsets;
    CDStruct_b48bc849 dataOffsets;
    WFDataSet *lapAverageSpeed;
    WFDataSet *prevLapAverageSpeed;
    WFDataSet *workoutAverageSpeed;
    WFSlidingSet *timeDistanceCalculator;
}

@property(nonatomic) float wheelCircumference; // @synthesize wheelCircumference;
- (void).cxx_destruct;
- (id)stringFromBikeSpeedCalories:(CDStruct_e25eb2d1 *)arg1;
- (id)stringFromBikeSpeed:(CDStruct_e25eb2d1 *)arg1 averagingType:(int)arg2 forDistance:(int)arg3 displayCell:(id)arg4;
- (id)formattedBikeSpeed:(CDStruct_e25eb2d1 *)arg1 averagingType:(int)arg2 forDistance:(int)arg3;
- (id)stringFromBikeSpeed:(CDStruct_e25eb2d1 *)arg1 averagingType:(int)arg2 forDuration:(int)arg3 displayCell:(id)arg4;
- (id)formattedBikeSpeed:(CDStruct_e25eb2d1 *)arg1 averagingType:(int)arg2 forDuration:(int)arg3;
- (id)stringFromBikeSpeed:(CDStruct_e25eb2d1 *)arg1 displayCell:(id)arg2;
- (id)formattedBikeSpeed:(CDStruct_e25eb2d1 *)arg1;
- (id)stringFromBikeDistance:(CDStruct_e25eb2d1 *)arg1 forDuration:(int)arg2 displayCell:(id)arg3;
- (id)formattedBikeDistance:(CDStruct_e25eb2d1 *)arg1 forDuration:(int)arg2;
- (void)createTimeDistanceCalculator:(BOOL)arg1;
@property(readonly, nonatomic) WFBikeSpeedData *bikeSpeedData;
@property(readonly, nonatomic) WFBikeSpeedConnection *bikeSpeedConnection;
- (void)writeSummaryForWorkout:(id)arg1;
- (void)writeSummaryForSegment:(id)arg1;
- (BOOL)shouldDisplayData:(id *)arg1 displaysWhenStale:(BOOL)arg2;
- (BOOL)resetOffsets;
- (void)resumeWorkout;
- (void)pauseWorkout;
- (void)processData:(id)arg1;
- (void)postConnectSetup;
- (void)endWorkout:(id)arg1;
- (void)endSegment:(id)arg1;
- (BOOL)beginWorkout:(id)arg1;
- (void)beginSegment;
- (id)init;

@end

