//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSensor.h"

#import "WFAudioControlDelegate.h"

@class NSTimer;

@interface WFSensorAudioControl : WFSensor <WFAudioControlDelegate>
{
    NSTimer *updateTimer;
}

- (void).cxx_destruct;
- (BOOL)stopSendingUpdates;
- (BOOL)startSendingUpdates;
- (void)stopUpdateTimer;
- (void)startUpdateTimer;
- (void)sendUpdate;
- (id)acConnection;
- (void)connection:(id)arg1 stateChanged:(int)arg2;
- (void)acVolumeUp;
- (void)acVolumeDown;
- (void)acStop;
- (void)acSkipToPrevious;
- (void)acSkipToNext;
- (void)acPlay;
- (void)acPause;
- (void)acCustomCommand:(unsigned char)arg1;
- (id)init;
- (void)dealloc;

@end

