//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

@class MHTextField, NSArray, UILabel;

@interface WFSettingsPowerTVC : WFStaticTableViewController
{
    UILabel *_criticalPowerLabel;
    UILabel *_zone5Label;
    UILabel *_zone4Label;
    UILabel *_zone3Label;
    UILabel *_zone2Label;
    UILabel *_zone1Label;
    MHTextField *_criticalPowerField;
    MHTextField *_zone5Field;
    MHTextField *_zone4Field;
    MHTextField *_zone3Field;
    MHTextField *_zone2Field;
    MHTextField *_zone1Field;
    NSArray *_labels;
    NSArray *_fields;
}

@property(retain, nonatomic) NSArray *fields; // @synthesize fields=_fields;
@property(retain, nonatomic) NSArray *labels; // @synthesize labels=_labels;
@property(nonatomic) __weak MHTextField *zone1Field; // @synthesize zone1Field=_zone1Field;
@property(nonatomic) __weak MHTextField *zone2Field; // @synthesize zone2Field=_zone2Field;
@property(nonatomic) __weak MHTextField *zone3Field; // @synthesize zone3Field=_zone3Field;
@property(nonatomic) __weak MHTextField *zone4Field; // @synthesize zone4Field=_zone4Field;
@property(nonatomic) __weak MHTextField *zone5Field; // @synthesize zone5Field=_zone5Field;
@property(nonatomic) __weak MHTextField *criticalPowerField; // @synthesize criticalPowerField=_criticalPowerField;
@property(nonatomic) __weak UILabel *zone1Label; // @synthesize zone1Label=_zone1Label;
@property(nonatomic) __weak UILabel *zone2Label; // @synthesize zone2Label=_zone2Label;
@property(nonatomic) __weak UILabel *zone3Label; // @synthesize zone3Label=_zone3Label;
@property(nonatomic) __weak UILabel *zone4Label; // @synthesize zone4Label=_zone4Label;
@property(nonatomic) __weak UILabel *zone5Label; // @synthesize zone5Label=_zone5Label;
@property(nonatomic) __weak UILabel *criticalPowerLabel; // @synthesize criticalPowerLabel=_criticalPowerLabel;
- (void).cxx_destruct;
- (void)doneButtonTouched:(id)arg1;
- (void)fieldEditingBegan:(id)arg1;
- (void)fieldEditingEnded:(id)arg1;
- (void)populateData;
- (BOOL)enableRightModalDismissButton;
- (void)viewDidLoad;

@end

