//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "WFUDPBroadcastManagerDelegate.h"

@class NSSet, UBERWorkoutProfile, WFSessionData, WFWorkout, WFWorkoutData;

@interface WFSession : NSManagedObject <WFUDPBroadcastManagerDelegate>
{
    WFSessionData *sessionData;
    WFWorkout *activeWorkout;
    WFWorkoutData *workoutData;
    int workoutState;
    UBERWorkoutProfile *workoutProfile;
}

+ (void)initialize;
@property(retain, nonatomic) UBERWorkoutProfile *workoutProfile; // @synthesize workoutProfile;
@property(retain, nonatomic) WFWorkout *activeWorkout; // @synthesize activeWorkout;
@property(nonatomic) __weak WFSessionData *sessionData; // @synthesize sessionData;
- (void).cxx_destruct;
- (void)shutdownSession;
- (void)resetWorkoutAndCloseConnections;
- (void)loadWorkoutProfile:(id)arg1;
@property(readonly, nonatomic) int workoutState; // @synthesize workoutState;
@property(readonly, nonatomic) WFWorkoutData *workoutData; // @synthesize workoutData;
- (id)deviceName;
- (id)dataForBroadcastManager:(id)arg1;
- (id)currentUser;
- (void)exportPWX:(id)arg1;
- (void)exportCSV:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSSet *workouts; // @dynamic workouts;

@end

