//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

#import "UIActionSheetDelegate.h"
#import "WFCalibrationFactorTVCDelegate.h"
#import "WFSensorCellDelegate.h"
#import "WFSensorManagerListenerProtocol.h"
#import "WFWheelCircumferenceTVCDelegate.h"
#import "WFWorkoutProfilesSelectTVCDelegate.h"

@class NSArray, NSMutableArray, UBERSensor, UISwitch, UITableViewCell, UIView, WFBasicTableViewCell, WFSensorCell, WFSensorManager, WFSession, WFWorkoutProfileIconsCell;

@interface WFSensorTVC : WFStaticTableViewController <WFWorkoutProfilesSelectTVCDelegate, WFWheelCircumferenceTVCDelegate, WFCalibrationFactorTVCDelegate, WFSensorManagerListenerProtocol, WFSensorCellDelegate, UIActionSheetDelegate>
{
    UBERSensor *_sensor;
    WFSensorCell *_sensorCell;
    WFSensorManager *_sensorManager;
    WFSession *_session;
    NSMutableArray *_wfSensors;
    int _combinedConnectionStatus;
    UIView *_sensorFooterView;
    UITableViewCell *_heartrateCell;
    UITableViewCell *_speedCell;
    UITableViewCell *_cadenceCell;
    UITableViewCell *_strideCell;
    UITableViewCell *_powerCell;
    UITableViewCell *_altitudeCell;
    UITableViewCell *_motionCell;
    NSArray *_dataCells;
    UITableViewCell *_wheelCircumferenceCell;
    UITableViewCell *_pageConfigurationsCell;
    UITableViewCell *_calibrationFactorCell;
    WFWorkoutProfileIconsCell *_profilesCell;
    WFBasicTableViewCell *_calibrateCell;
    WFBasicTableViewCell *_saveCell;
    WFBasicTableViewCell *_forgetCell;
    WFBasicTableViewCell *_helpCell;
    WFBasicTableViewCell *_tutorialCell;
    WFBasicTableViewCell *_debugCell;
    WFBasicTableViewCell *_flywheelCell;
    UISwitch *_debugSwitch;
}

@property(nonatomic) __weak UISwitch *debugSwitch; // @synthesize debugSwitch=_debugSwitch;
@property(nonatomic) __weak WFBasicTableViewCell *flywheelCell; // @synthesize flywheelCell=_flywheelCell;
@property(nonatomic) __weak WFBasicTableViewCell *debugCell; // @synthesize debugCell=_debugCell;
@property(nonatomic) __weak WFBasicTableViewCell *tutorialCell; // @synthesize tutorialCell=_tutorialCell;
@property(nonatomic) __weak WFBasicTableViewCell *helpCell; // @synthesize helpCell=_helpCell;
@property(nonatomic) __weak WFBasicTableViewCell *forgetCell; // @synthesize forgetCell=_forgetCell;
@property(nonatomic) __weak WFBasicTableViewCell *saveCell; // @synthesize saveCell=_saveCell;
@property(nonatomic) __weak WFBasicTableViewCell *calibrateCell; // @synthesize calibrateCell=_calibrateCell;
@property(nonatomic) __weak WFWorkoutProfileIconsCell *profilesCell; // @synthesize profilesCell=_profilesCell;
@property(nonatomic) __weak UITableViewCell *calibrationFactorCell; // @synthesize calibrationFactorCell=_calibrationFactorCell;
@property(nonatomic) __weak UITableViewCell *pageConfigurationsCell; // @synthesize pageConfigurationsCell=_pageConfigurationsCell;
@property(nonatomic) __weak UITableViewCell *wheelCircumferenceCell; // @synthesize wheelCircumferenceCell=_wheelCircumferenceCell;
@property(retain, nonatomic) NSArray *dataCells; // @synthesize dataCells=_dataCells;
@property(nonatomic) __weak UITableViewCell *motionCell; // @synthesize motionCell=_motionCell;
@property(nonatomic) __weak UITableViewCell *altitudeCell; // @synthesize altitudeCell=_altitudeCell;
@property(nonatomic) __weak UITableViewCell *powerCell; // @synthesize powerCell=_powerCell;
@property(nonatomic) __weak UITableViewCell *strideCell; // @synthesize strideCell=_strideCell;
@property(nonatomic) __weak UITableViewCell *cadenceCell; // @synthesize cadenceCell=_cadenceCell;
@property(nonatomic) __weak UITableViewCell *speedCell; // @synthesize speedCell=_speedCell;
@property(nonatomic) __weak UITableViewCell *heartrateCell; // @synthesize heartrateCell=_heartrateCell;
@property(retain, nonatomic) UIView *sensorFooterView; // @synthesize sensorFooterView=_sensorFooterView;
@property(nonatomic) int combinedConnectionStatus; // @synthesize combinedConnectionStatus=_combinedConnectionStatus;
@property(retain, nonatomic) NSMutableArray *wfSensors; // @synthesize wfSensors=_wfSensors;
@property(retain, nonatomic) WFSession *session; // @synthesize session=_session;
@property(retain, nonatomic) WFSensorManager *sensorManager; // @synthesize sensorManager=_sensorManager;
@property(nonatomic) __weak WFSensorCell *sensorCell; // @synthesize sensorCell=_sensorCell;
@property(retain, nonatomic) UBERSensor *sensor; // @synthesize sensor=_sensor;
- (void).cxx_destruct;
- (void)sensorCell:(id)arg1 didUpdateSensorDisplayName:(id)arg2;
- (void)workoutProfileSelectTVC:(id)arg1 didDismissWithSelectedProfiles:(id)arg2;
- (void)calibationFactorWillDismiss:(id)arg1;
- (void)sensorWheelSizeTVC:(id)arg1 didDismissWithSelectedWheelSize:(double)arg2;
- (void)calibrate;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (void)sensor:(id)arg1 didConnect:(BOOL)arg2;
- (void)sensorManager:(id)arg1 sensor:(id)arg2 rejectedByDeviceNamed:(id)arg3 appAlreadyConnected:(id)arg4;
- (void)sensorManager:(id)arg1 didLoseDevice:(id)arg2;
- (void)sensorManager:(id)arg1 didDiscoverDevice:(id)arg2;
- (void)sensorManagerHasData:(id)arg1;
- (void)populateDeviceCapabilities;
- (void)hideSensorFooterView;
- (void)updateConnectionUI;
- (void)updateSensorData;
- (id)stringFromSensorMotionAnalysis;
- (id)stringFromSensorElevation;
- (id)stringFromSensorStrideRate;
- (id)stringFromSensorBikePower;
- (id)stringFromSensorHeartrate;
- (id)stringFromSensorCadence;
- (id)stringFromSensorSpeed;
- (id)stringFromSensorSelector:(SEL)arg1;
- (void)stopHardwareStatusListener;
- (void)startHardwareStatusListener;
- (void)forgetSensor;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)forgetSensorTouched;
- (void)linkSensorToWorkoutProfiles:(id)arg1;
- (void)debugSwitchTouched:(id)arg1;
- (void)flywheelSwitchChanged:(id)arg1;
- (void)saveSensor;
- (void)saveSensorTouched;
- (void)configureActionCellVisibility;
- (void)configureDataCellVisibility;
- (void)configureCellVisibilityAnimated:(BOOL)arg1;
- (void)connectSensors;
- (void)setupSensors;
- (void)applicaitonWillEnterForground;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)localize;

@end

