//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFShareActivityModalVC.h"

#import "UITextViewDelegate.h"

@class UIButton, UITextView;

@interface WFShareDebugLogActivityVC : WFShareActivityModalVC <UITextViewDelegate>
{
    UITextView *_textView;
    UIButton *_nextButton;
}

@property(nonatomic) __weak UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)nextButtonTouched:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

