//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFShareLocalActivity.h"

#import "MFMailComposeViewControllerDelegate.h"

@interface WFShareEmailActivity : WFShareLocalActivity <MFMailComposeViewControllerDelegate>
{
}

- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)performActivityWithFiles:(id)arg1;
- (void)performActivity;
- (id)activityViewController;
- (id)init;

@end

