//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFShareLocalActivity.h"

#import "UIDocumentInteractionControllerDelegate.h"

@class NSString, UIDocumentInteractionController;

@interface WFShareOpenInActivity : WFShareLocalActivity <UIDocumentInteractionControllerDelegate>
{
    UIDocumentInteractionController *_docController;
    NSString *_applicationName;
}

@property(copy, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(retain, nonatomic) UIDocumentInteractionController *docController; // @synthesize docController=_docController;
- (void).cxx_destruct;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (void)documentInteractionController:(id)arg1 willBeginSendingToApplication:(id)arg2;
- (void)documentInteractionControllerDidDismissOpenInMenu:(id)arg1;
- (void)performActivityWithFiles:(id)arg1;
- (id)init;

@end

