//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSingleLineChart.h"

#import "WFSingleLineChartDataSource.h"

@class UIView, WFWorkout;

@interface WFSingleLineChartVC : WFSingleLineChart <WFSingleLineChartDataSource>
{
    WFWorkout *_workout;
    int _xAxisType;
    UIView *_elevationChartView;
    UIView *_cachedChartView;
}

@property(retain, nonatomic) UIView *cachedChartView; // @synthesize cachedChartView=_cachedChartView;
@property(retain, nonatomic) UIView *elevationChartView; // @synthesize elevationChartView=_elevationChartView;
@property(nonatomic) int xAxisType; // @synthesize xAxisType=_xAxisType;
@property(retain, nonatomic) WFWorkout *workout; // @synthesize workout=_workout;
- (void).cxx_destruct;
- (BOOL)showYAxisForLineChart:(id)arg1;
- (BOOL)showXAxisForLineChart:(id)arg1;
- (BOOL)showFillForLineChart:(id)arg1;
- (id)colorForLineInlineChart:(id)arg1;
- (struct CGPoint)lineChart:(id)arg1 valueForPointAtIndex:(unsigned int)arg2;
- (int)numberOfDataPointsInChart:(id)arg1;
- (id)locationSamples;
- (void)viewDidLoad;

@end

