//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle, NSString;

@interface WFSimpleLogWriter : NSObject
{
    NSFileHandle *_logFileHandle;
    NSString *_logFilePath;
}

@property(retain, nonatomic) NSString *logFilePath; // @synthesize logFilePath=_logFilePath;
@property(retain, nonatomic) NSFileHandle *logFileHandle; // @synthesize logFileHandle=_logFileHandle;
- (void)finishAndDiscardLog;
- (void)finishLog;
- (void)writeLines:(id)arg1;
- (void)writeLine:(id)arg1;
- (id)initWithFileName:(id)arg1;

@end

