//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, UIColor, WFSingleLineChart;

@protocol WFSingleLineChartDataSource <NSObject>
- (BOOL)showYAxisForLineChart:(WFSingleLineChart *)arg1;
- (BOOL)showXAxisForLineChart:(WFSingleLineChart *)arg1;
- (BOOL)showFillForLineChart:(WFSingleLineChart *)arg1;
- (UIColor *)colorForLineInlineChart:(WFSingleLineChart *)arg1;
- (struct CGPoint)lineChart:(WFSingleLineChart *)arg1 valueForPointAtIndex:(unsigned int)arg2;
- (int)numberOfDataPointsInChart:(WFSingleLineChart *)arg1;

@optional
- (NSNumber *)valueForAverageLine;
- (NSNumber *)yAxisMax;
- (NSNumber *)yAxisMin;
- (double)bottomPaddingForAxisOnLineChart:(WFSingleLineChart *)arg1;
- (double)topPaddingForAxisOnLineChart:(WFSingleLineChart *)arg1;
@end

