//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor, UIImageView;

@interface WFSingleBarView : UIView
{
    BOOL _pulsing;
    int _orientation;
    int _origin;
    UIColor *_color;
    UIView *_barView;
    UIImageView *_arrowImage;
    double _max;
    double _min;
    double _value;
    double _minFillFactor;
    double _pulseInterval;
    double _dutyCycle;
    double _overshoot;
}

@property(retain, nonatomic) UIImageView *arrowImage; // @synthesize arrowImage=_arrowImage;
@property(retain, nonatomic) UIView *barView; // @synthesize barView=_barView;
@property(readonly, nonatomic) BOOL pulsing; // @synthesize pulsing=_pulsing;
@property(nonatomic) double overshoot; // @synthesize overshoot=_overshoot;
@property(nonatomic) double dutyCycle; // @synthesize dutyCycle=_dutyCycle;
@property(nonatomic) double pulseInterval; // @synthesize pulseInterval=_pulseInterval;
@property(nonatomic) double minFillFactor; // @synthesize minFillFactor=_minFillFactor;
@property(nonatomic) double value; // @synthesize value=_value;
@property(nonatomic) double min; // @synthesize min=_min;
@property(nonatomic) double max; // @synthesize max=_max;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) int origin; // @synthesize origin=_origin;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
- (void).cxx_destruct;
- (void)pulseDown;
- (void)pulseUp;
- (void)stopPulsing;
- (void)startPulsingWithInterval:(double)arg1 dutyCycle:(double)arg2 overshoot:(double)arg3;
- (void)drawWithAnimationDuration:(double)arg1;
- (void)dealloc;
- (void)awakeFromNib;

@end

