//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"

@class AVAudioPlayer, NSMutableArray, NSOperationQueue;

@interface WFSoundPlayer : NSObject <AVAudioPlayerDelegate>
{
    AVAudioPlayer *currentPlayer;
    AVAudioPlayer *nextPlayer;
    NSMutableArray *playlistQueue;
    NSOperationQueue *queue;
    BOOL autoDuck;
    BOOL bResumeIPodWhenDone;
    BOOL isPlaying;
}

@property(nonatomic) BOOL autoDuck; // @synthesize autoDuck;
- (void).cxx_destruct;
- (BOOL)resumekMusic;
- (BOOL)isPlaying;
- (void)playFilesWithOperation:(id)arg1;
- (void)playFiles:(id)arg1;
- (void)stopPlayingAllFiles;
- (void)preLoadFiles:(id)arg1;
- (BOOL)duckMusic;
- (id)init;

@end

