//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCalculatorWorkout.h"

@interface WFSpeedCalculatorWorkout : WFCalculatorWorkout
{
}

- (void)configureUserIsMetric:(BOOL)arg1;
- (void)addBikePowerSample:(id)arg1;
- (void)addBikeSpeedSample:(id)arg1;
- (id)configuredCalculator;
- (void)addSample:(id)arg1;
- (id)calculatorForLapNumber:(unsigned int)arg1;
- (id)previousLap;
- (id)lap;
- (id)workout;

@end

