//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailComposeViewControllerDelegate.h"

@class UIViewController;

@interface WFSupportUtility : NSObject <MFMailComposeViewControllerDelegate>
{
    UIViewController *_hostViewController;
}

+ (id)webBrowserWithProductInstructionsForKey:(id)arg1;
+ (id)webBrowserWithKnowledgeBasePageForForKey:(id)arg1;
+ (id)webBrowserWithSupportPage;
+ (id)webBrowserWithStorePage;
+ (id)productInstructionsURLForKey:(id)arg1;
+ (id)knowledgeBaseURLForKey:(id)arg1;
+ (id)emailSupportInViewHost:(id)arg1;
+ (id)emailSupportWithFitFile:(id)arg1 error:(id)arg2 inViewHost:(id)arg3;
+ (id)emailSupportWithShareErrors:(id)arg1 shareName:(id)arg2 description:(id)arg3 hostViewController:(id)arg4;
+ (id)supportMailComposeViewController;
+ (id)supportEmailAddress;
+ (BOOL)canSendMail;
+ (id)supportAppInfo;
@property(retain, nonatomic) UIViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
- (void).cxx_destruct;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;

@end

