//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFThemeV4.h"

@class UIImage;

@interface WFThemeV4_iPhone : WFThemeV4
{
    UIImage *_blurredBackgroundImage;
}

- (void)setBlurredBackgroundImage:(id)arg1;
- (void).cxx_destruct;
- (id)blurredBackgroundImage;
- (id)navBarBackgroundImage;
- (void)setPredefinedColorPalette:(int)arg1;
- (void)applyAppearanceProxies;
- (id)instantiateWorkoutViewController;
- (id)instantiateStartViewController;

@end

