//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFThemeV4_iPhone.h"

@interface WFThemeV4_iPhoneOS7 : WFThemeV4_iPhone
{
}

- (void)applyThemeToPageControl:(id)arg1;
- (void)applyAppearanceProxies;
- (id)instantiateWorkoutViewController;

@end

