//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFThemeProtocol.h"

@interface WFTheme : NSObject <WFThemeProtocol>
{
}

+ (id)theme;
- (void)applyStandardStyleToHeaderLabel:(id)arg1 inTableView:(id)arg2;
- (void)applyStandardStyleToTableView:(id)arg1;
- (void)applyThemeToViewForWorkoutWidget:(id)arg1;
- (void)applyThemeToPageControl:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)stringTermForLap;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableViewHeaderSize;
- (id)tableViewHeaderBackgroundViewForStyle:(int)arg1;
- (id)tableViewHeaderBackgroundColorForStyle:(int)arg1;
- (int)tableViewStandardStyle;
- (id)tableViewBackgroundColor;
- (id)tableViewCellDetailTextColor;
- (id)tableViewCellTextColor;
- (id)tableViewCellBackgroundColor;
- (id)workoutBackButtonImageHighlighted;
- (id)workoutBackButtonImage;
- (id)workoutBackButtonTitle;
- (id)workoutLapButtonImageHighlighted;
- (id)workoutLapButtonImage;
- (id)workoutLapButtonTitle;
- (id)workoutStartButtonImageHighlighted;
- (id)workoutStartButtonImage;
- (id)workoutStartButtonTitle;
- (id)workoutStopButtonImageHighlighted;
- (id)workoutStopButtonImage;
- (id)workoutStopButtonTitle;
- (id)workoutResumeButtonImageHighlighted;
- (id)workoutResumeButtonImage;
- (id)workoutResumeButtonTitle;
- (id)workoutPauseButtonImageHighlighted;
- (id)workoutPauseButtonImage;
- (id)workoutPauseButtonTitle;
- (id)workoutPausedOverlayImage1;
- (id)workoutPausedOverlayImage;
- (id)workoutScrollViewBackgroundImage;
- (id)workoutScrollViewBackgroundColor;
- (id)navBarSensorBarViewController;
- (BOOL)navBarSensorBarVisable;
- (id)navBarBackgroundImage;
- (id)navBarLockButtonLapImage;
- (id)navBarLockButtonImage;
- (id)navBarLockButtonTitle;
- (BOOL)navBarLockButtonVisable;
- (id)navBarSettingImage;
- (BOOL)navBarSettingButtonVisable;
- (id)noSensorKeyWarningText;
- (id)noSensorKeyWarningTitle;
- (id)navBarTintColorLocked;
- (id)navBarTintColor;
- (id)navBarCenterImageLocked;
- (id)navBarCenterImage;
- (id)splashScreenImage;
- (id)navControllerBackgroundColor;
- (void)globalThemeSetup;
- (id)instantiateWorkoutViewController;
- (id)instantiateStartViewController;
- (id)instantiateApplicationWindow;

@end

