//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFThemeProtocol.h"

@class UIImage, WFColorPalette;

@interface WFThemeV4 : NSObject <WFThemeProtocol>
{
    UIImage *_blurredBackgroundImage;
    WFColorPalette *_colorPalette;
}

+ (id)theme;
@property(retain, nonatomic) WFColorPalette *colorPalette; // @synthesize colorPalette=_colorPalette;
@property(retain, nonatomic) UIImage *blurredBackgroundImage; // @synthesize blurredBackgroundImage=_blurredBackgroundImage;
- (void).cxx_destruct;
- (void)applyThemeToPageControl:(id)arg1;
- (id)navBarCenterImage;
- (id)workoutPausedOverlayImage1;
- (id)workoutPausedOverlayImage;
- (id)workoutBackButtonImageHighlighted;
- (id)workoutBackButtonImage;
- (id)workoutBackButtonTitle;
- (id)workoutLapButtonImageHighlighted;
- (id)workoutLapButtonImage;
- (id)workoutLapButtonTitle;
- (id)workoutStartButtonImageHighlighted;
- (id)workoutStartButtonImage;
- (id)workoutStartButtonTitle;
- (id)workoutStopButtonImageHighlighted;
- (id)workoutStopButtonImage;
- (id)workoutStopButtonTitle;
- (id)workoutResumeButtonImageHighlighted;
- (id)workoutResumeButtonImage;
- (id)workoutResumeButtonTitle;
- (id)workoutPauseButtonImageHighlighted;
- (id)workoutPauseButtonImage;
- (id)workoutPauseButtonTitle;
- (void)applyAppearanceProxies;
- (void)setPredefinedColorPalette:(int)arg1;
- (id)splashScreenImage;
- (id)instantiateWorkoutViewController;
- (id)instantiateStartViewController;
- (id)instantiateApplicationWindow;

@end

