//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "WFManualSpeedEntryVCDelegate.h"

@class UIButton, UILabel, UIView;

@interface WFTICKRRUNSpeedEntryVC : UIViewController <WFManualSpeedEntryVCDelegate>
{
    double speedVal;
    id <WFTICKRRUNSpeedEntryVCDelegate> _delegate;
    UIButton *_okButton;
    UIView *_containerView;
    UILabel *_howFastDidYouRunLabel;
}

@property(nonatomic) __weak UILabel *howFastDidYouRunLabel; // @synthesize howFastDidYouRunLabel=_howFastDidYouRunLabel;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak UIButton *okButton; // @synthesize okButton=_okButton;
@property(nonatomic) __weak id <WFTICKRRUNSpeedEntryVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)manualSpeedEntryVC:(id)arg1 didSelectSpeed:(double)arg2;
- (void)onNavCancelButtonPressed:(id)arg1;
- (void)okButtonTouched:(id)arg1;
- (void)viewDidLoad;

@end

