//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, WFTimescaleMusicPlayer;

@protocol WFTimescaleMusicPlayerDelegate
- (void)tsPlayer:(WFTimescaleMusicPlayer *)arg1 didLoadFileAtPath:(NSString *)arg2 beatsPerMinute:(float)arg3;
- (void)tsPlayer:(WFTimescaleMusicPlayer *)arg1 didFinishPlaying:(BOOL)arg2;
@end

