//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFHeartrateConnectionTICKRXCalibrationDelegate.h"

@class UBERSensor, WFHeartrateConnection, WFSensorHeartrate;

@interface WFTICKRRUNCalibrationConnection : NSObject <WFHeartrateConnectionTICKRXCalibrationDelegate>
{
    UBERSensor *_sensor;
    WFSensorHeartrate *_sensorHeartrate;
    int _calibrationUpdateType;
}

@property(nonatomic) int calibrationUpdateType; // @synthesize calibrationUpdateType=_calibrationUpdateType;
@property(retain, nonatomic) WFSensorHeartrate *sensorHeartrate; // @synthesize sensorHeartrate=_sensorHeartrate;
@property(retain, nonatomic) UBERSensor *sensor; // @synthesize sensor=_sensor;
- (void).cxx_destruct;
@property(readonly, retain, nonatomic) WFHeartrateConnection *tickrRunConnection;
- (void)heartrateSensor:(id)arg1 didCompleteGetCalibrationOperation:(id)arg2;
- (void)heartrateSensor:(id)arg1 didCompleteSetCalibrationOperation:(BOOL)arg2;
- (void)updateCalibrationObject:(id)arg1 withXValue:(id)arg2 andYvalue:(id)arg3;
- (void)sendMotionAnalysisCalibrationToDevice:(id)arg1;
- (void)getMotionAnalysisCalibrationForActivityType:(int)arg1;
- (void)setDefaultCalibrationValuesforActivityType:(int)arg1 overwriteExisting:(BOOL)arg2;
- (id)initWithSensor:(id)arg1;

@end

