//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFAUPlayerDelegate.h"
#import "WFMusicLibraryExporterDelegate.h"

@class MPMediaItem, NSString, WFAUPlayer, WFMusicLibraryExporter;

@interface WFTimescaleMusicPlayer : NSObject <WFMusicLibraryExporterDelegate, WFAUPlayerDelegate>
{
    NSString *musicFilePath;
    WFAUPlayer *auPlayer;
    WFMusicLibraryExporter *libExporter;
    id <WFTimescaleMusicPlayerDelegate> delegate;
    float beatsPerMinute;
    float nativeBPM;
    MPMediaItem *mediaItem;
}

@property(retain, nonatomic) MPMediaItem *mediaItem; // @synthesize mediaItem;
@property(nonatomic) float nativeBPM; // @synthesize nativeBPM;
@property(readonly, nonatomic) NSString *musicFilePath; // @synthesize musicFilePath;
- (void).cxx_destruct;
- (double)remainingTime;
- (double)currentTime;
- (double)playbackDuration;
- (BOOL)isPlaying;
- (void)pauseSong;
- (void)startPlayingSong;
- (void)stopPlayingSong;
@property float beatsPerMinute;
- (float)getBeatsPerMinute;
- (void)diracPlayerDidFinishPlaying:(id)arg1 successfully:(BOOL)arg2;
- (void)auPlayerDidFinishPlayingFile:(id)arg1;
- (void)libExporter:(id)arg1 didFailToExportMediaItem:(id)arg2;
- (void)libExporter:(id)arg1 didFinishExportingMediaItem:(id)arg2 toPath:(id)arg3;
- (id)initWithDelegate:(id)arg1 mediaItem:(id)arg2;
- (id)initWithDelegate:(id)arg1 mediaItem:(id)arg2 useDirac:(BOOL)arg3;
- (id)init;
- (void)dealloc;

@end

