//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCalibrationFormsheetNC.h"

#import "UIAlertViewDelegate.h"

@interface WFTICKRRunCalibrationNC : WFCalibrationFormsheetNC <UIAlertViewDelegate>
{
}

- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)exit;
- (void)promptBeforeExit;

@end

