//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFUserDetailsTVC.h"

@class UILabel;

@interface WFUserDetailsTutorialTVC : WFUserDetailsTVC
{
    UILabel *_unitsHeaderLabel;
    UILabel *_genderHeaderLabel;
    UILabel *_weightHeaderLabel;
    UILabel *_heightHeaderLabel;
    UILabel *_dobHeaderLabel;
}

@property(nonatomic) __weak UILabel *dobHeaderLabel; // @synthesize dobHeaderLabel=_dobHeaderLabel;
@property(nonatomic) __weak UILabel *heightHeaderLabel; // @synthesize heightHeaderLabel=_heightHeaderLabel;
@property(nonatomic) __weak UILabel *weightHeaderLabel; // @synthesize weightHeaderLabel=_weightHeaderLabel;
@property(nonatomic) __weak UILabel *genderHeaderLabel; // @synthesize genderHeaderLabel=_genderHeaderLabel;
@property(nonatomic) __weak UILabel *unitsHeaderLabel; // @synthesize unitsHeaderLabel=_unitsHeaderLabel;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)viewDidLoad;

@end

