//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFWahooMotionAnalysisCalibrationBase.h"

@interface WFWahooMotionAnalysisCalibration_Swimming : WFWahooMotionAnalysisCalibrationBase
{
}

- (BOOL)parseDeviceCalibrationData:(id)arg1 forPart:(unsigned char)arg2;
- (id)getDeviceCalibrationDataForPart:(unsigned char)arg1;
- (unsigned char)getDeviceCalibrationPartsCount;
- (int)activityType;

@end

