//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCPMPowerMeasurementCh.h"

@interface WFWahooCPMLegacyPowerCh : WFCPMPowerMeasurementCh
{
}

- (void)updateCalculatedValues:(unsigned short)arg1;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (id)init;
- (void)dealloc;

@end

