//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WFWahooSensorDebugDataLogger;

@protocol WFWahooSensorDebugDataLoggerDelegate <NSObject>
- (void)wahooSensorDebugDataLogger:(WFWahooSensorDebugDataLogger *)arg1 debugRXNowStale:(_Bool)arg2;
- (void)wahooSensorDebugDataLogger:(WFWahooSensorDebugDataLogger *)arg1 didStartLogging:(_Bool)arg2;
- (void)wahooSensorDebugDataLogger:(WFWahooSensorDebugDataLogger *)arg1 didUpdatDebugRateHz:(double)arg2;
@end

