//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface WFWahooHRActivitySessionMarker : NSObject
{
    NSDate *_markerTimestamp;
    int _markerType;
}

@property(nonatomic) int markerType; // @synthesize markerType=_markerType;
@property(retain, nonatomic) NSDate *markerTimestamp; // @synthesize markerTimestamp=_markerTimestamp;

@end

