//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WFWBFirmwareInfo : NSObject
{
    unsigned char ucVendor;
    unsigned char ucMajor;
    unsigned char ucMinor;
    unsigned char ucBuild;
    BOOL chFormat;
}

@property(nonatomic) unsigned char ucBuild; // @synthesize ucBuild;
@property(nonatomic) unsigned char ucMinor; // @synthesize ucMinor;
@property(nonatomic) unsigned char ucMajor; // @synthesize ucMajor;
@property(nonatomic) unsigned char ucVendor; // @synthesize ucVendor;
- (id)initWithFormat:(BOOL)arg1;
@property(readonly, nonatomic) NSString *versionString;

@end

