//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFFormatter.h"

@class NSLocale, NSNumberFormatter, NSString;

@interface WFWeightFormatter : WFFormatter
{
    NSLocale *_locale;
    unsigned int _units;
    NSString *_invalidWeightSymbol;
    NSNumberFormatter *_numberFormatter;
}

@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(copy, nonatomic) NSString *invalidWeightSymbol; // @synthesize invalidWeightSymbol=_invalidWeightSymbol;
@property(nonatomic) unsigned int units; // @synthesize units=_units;
@property(copy, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
- (void).cxx_destruct;
- (BOOL)getObjectValue:(out id *)arg1 forString:(id)arg2 errorDescription:(out id *)arg3;
- (id)stringForObjectValue:(id)arg1;
- (double)weightFromString:(id)arg1;
- (id)stringFromWeight:(double)arg1 unitStyle:(unsigned int)arg2;
- (id)stringFromWeight:(double)arg1;
- (id)unitStringFromWeight:(double)arg1 unitStyle:(unsigned int)arg2;
- (id)unitStringFromWeight:(double)arg1;
- (unsigned int)formatterUnitStyle;
- (unsigned int)formatterUnits;
- (id)formatterLocale;

@end

