//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_WFWeightScaleDelegate.h"

@class NSArray, WFBTLEWeightScaleUser, WFWeightScaleConnection;

@protocol WFWeightScaleDelegate <_WFWeightScaleDelegate>
- (void)wsConnection:(WFWeightScaleConnection *)arg1 didAddNewUserRecord:(WFBTLEWeightScaleUser *)arg2;
- (void)wsConnection:(WFWeightScaleConnection *)arg1 userProfileRejected:(WFBTLEWeightScaleUser *)arg2 forOverlappingWith:(WFBTLEWeightScaleUser *)arg3;
- (void)wsConnection:(WFWeightScaleConnection *)arg1 didReceiveUserRecords:(NSArray *)arg2;
- (void)wsConnection:(WFWeightScaleConnection *)arg1 didReceiveWeightHistory:(NSArray *)arg2;

@optional
- (void)wsConnection:(WFWeightScaleConnection *)arg1 didReceiveUserId:(int)arg2;
@end

