//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFCharacteristicDecoder.h"

@interface WFWeightScaleMeasurementCh : WFCharacteristicDecoder
{
    BOOL hasTimestamp;
    BOOL hasUserId;
    BOOL hasBmi;
    BOOL isWeightStabilized;
    float weight;
    double timestamp;
    unsigned char ucUserId;
    float bmi;
}

@property(readonly, nonatomic) BOOL isWeightStabilized; // @synthesize isWeightStabilized;
@property(readonly, nonatomic) BOOL hasBmi; // @synthesize hasBmi;
@property(readonly, nonatomic) BOOL hasUserId; // @synthesize hasUserId;
@property(readonly, nonatomic) BOOL hasTimestamp; // @synthesize hasTimestamp;
@property(readonly, nonatomic) float bmi; // @synthesize bmi;
@property(readonly, nonatomic) unsigned char ucUserId; // @synthesize ucUserId;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp;
@property(readonly, nonatomic) float weight; // @synthesize weight;
- (float)bytesToFloat_legacy:(char *)arg1;
- (void)reset;
- (BOOL)decodeCharacteristicData;
- (id)init;
- (void)dealloc;

@end

