//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLLocation;

@protocol WFWorkoutMapControlerDelegate <NSObject>
- (void)workoutMapControllerDidClearAll;
- (void)workoutMapControllerDidAddRouteOverlay:(id <MKOverlay>)arg1;
- (void)workoutMapControllerDidAddRouteAnnotation:(id <MKAnnotation>)arg1;
- (void)workotuMapControllerDidUpdateMapRect:(CDStruct_90e2a262)arg1;
- (void)workotuMapControllerDidUpdateLocation:(CLLocation *)arg1;
@end

