//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFStaticTableViewController.h"

@class UBERWorkoutDisplay, UILabel, UISwitch, UITableViewCell;

@interface WFWorkoutDisplaySettingsTVC : WFStaticTableViewController
{
    UBERWorkoutDisplay *_workoutDisplay;
    UISwitch *_invertColorsSwitch;
    UISwitch *_backlightSwitch;
    UILabel *_invertColorsLabel;
    UILabel *_backlightSwitchLabel;
    UILabel *_batteryLifeLabel;
    UILabel *_autoScrollLabel;
    UISwitch *_autoScrollSwitch;
    UITableViewCell *_invertColorsCell;
    UITableViewCell *_backlightOnButtonCell;
    UISwitch *_backlightOnButtonSwitch;
    UILabel *_backlightButtonPressedLabel;
    UILabel *_backlightShowsLabel;
}

@property(nonatomic) __weak UILabel *backlightShowsLabel; // @synthesize backlightShowsLabel=_backlightShowsLabel;
@property(nonatomic) __weak UILabel *backlightButtonPressedLabel; // @synthesize backlightButtonPressedLabel=_backlightButtonPressedLabel;
@property(nonatomic) __weak UISwitch *backlightOnButtonSwitch; // @synthesize backlightOnButtonSwitch=_backlightOnButtonSwitch;
@property(nonatomic) __weak UITableViewCell *backlightOnButtonCell; // @synthesize backlightOnButtonCell=_backlightOnButtonCell;
@property(retain, nonatomic) UITableViewCell *invertColorsCell; // @synthesize invertColorsCell=_invertColorsCell;
@property(retain, nonatomic) UISwitch *autoScrollSwitch; // @synthesize autoScrollSwitch=_autoScrollSwitch;
@property(retain, nonatomic) UILabel *autoScrollLabel; // @synthesize autoScrollLabel=_autoScrollLabel;
@property(retain, nonatomic) UILabel *batteryLifeLabel; // @synthesize batteryLifeLabel=_batteryLifeLabel;
@property(retain, nonatomic) UILabel *backlightSwitchLabel; // @synthesize backlightSwitchLabel=_backlightSwitchLabel;
@property(retain, nonatomic) UILabel *invertColorsLabel; // @synthesize invertColorsLabel=_invertColorsLabel;
@property(retain, nonatomic) UISwitch *backlightSwitch; // @synthesize backlightSwitch=_backlightSwitch;
@property(retain, nonatomic) UISwitch *invertColorsSwitch; // @synthesize invertColorsSwitch=_invertColorsSwitch;
@property(retain, nonatomic) UBERWorkoutDisplay *workoutDisplay; // @synthesize workoutDisplay=_workoutDisplay;
- (void).cxx_destruct;
- (void)backlightOnButtonChanged:(id)arg1;
- (void)autoScrollChanged:(id)arg1;
- (void)backlightChanged:(id)arg1;
- (void)inverColorsChanged:(id)arg1;
- (void)viewDidLoad;
- (void)awakeFromNib;

@end

