//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UBERWorkoutDisplayPage, WFWorkoutDisplayPagesTVC;

@protocol WFWorkoutDisplayPagesTVCDelegate <NSObject>
- (void)workoutDisplayPagesTVC:(WFWorkoutDisplayPagesTVC *)arg1 didSelectDisplayPage:(UBERWorkoutDisplayPage *)arg2;
@end

