//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate;

@interface WFWorkoutFilter : NSObject
{
    NSDate *_fromDate;
    NSDate *_toDate;
    NSArray *_workoutTypes;
}

+ (id)workoutFilterFromDate:(id)arg1 toDate:(id)arg2 workoutTypes:(id)arg3;
+ (id)workoutFilterFromDate:(id)arg1 toDate:(id)arg2;
+ (id)workoutFilterFromDate:(id)arg1;
@property(retain, nonatomic) NSArray *workoutTypes; // @synthesize workoutTypes=_workoutTypes;
@property(retain, nonatomic) NSDate *toDate; // @synthesize toDate=_toDate;
@property(retain, nonatomic) NSDate *fromDate; // @synthesize fromDate=_fromDate;
- (void).cxx_destruct;
- (id)predicateWithKeyPathPrefix:(id)arg1;
- (id)predicate;

@end

