//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFMKMapSnapshotter.h"

@class WFWorkout;

@interface WFWorkoutMapSnapshotter : WFMKMapSnapshotter
{
    WFWorkout *_workout;
}

@property(retain, nonatomic) WFWorkout *workout; // @synthesize workout=_workout;
- (void).cxx_destruct;
- (id)mapView:(id)arg1 rendererForOverlay:(id)arg2;
- (void)configureMapViewForSnapshot;

@end

