//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class WFWorkoutPageBaseVC;

@protocol WFWorkoutPageDelegate
- (BOOL)workoutPageIsLast:(WFWorkoutPageBaseVC *)arg1;
- (BOOL)workoutPageIsFirst:(WFWorkoutPageBaseVC *)arg1;
- (BOOL)workoutPageIsNearlyVisable:(WFWorkoutPageBaseVC *)arg1;
- (BOOL)workoutPageIsVisable:(WFWorkoutPageBaseVC *)arg1;
@end

