//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFDynamicTableViewController.h"

#import "WFNewWorkoutDisplayWizardDelegate.h"

@class NSArray, UBERWorkoutDisplay;

@interface WFWorkoutDisplaysTVC : WFDynamicTableViewController <WFNewWorkoutDisplayWizardDelegate>
{
    unsigned int _displayType;
    int _workoutType;
    UBERWorkoutDisplay *_selectedDisplay;
    id <WFWorkoutDisplaysTVCDelegate> _delegate;
    NSArray *_workoutDisplays;
}

@property(retain, nonatomic) NSArray *workoutDisplays; // @synthesize workoutDisplays=_workoutDisplays;
@property(nonatomic) __weak id <WFWorkoutDisplaysTVCDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UBERWorkoutDisplay *selectedDisplay; // @synthesize selectedDisplay=_selectedDisplay;
@property(nonatomic) int workoutType; // @synthesize workoutType=_workoutType;
@property(nonatomic) unsigned int displayType; // @synthesize displayType=_displayType;
- (void).cxx_destruct;
- (void)newWorkoutDisplayWizard:(id)arg1 didReturnWithDisplay:(id)arg2;
- (void)createConfigTouched;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)titleForLeftModalDismissButton;
- (BOOL)enableLeftModalDismissButton;
- (void)viewDidLoad;

@end

