//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WFSessionManagerListener.h"

@class UILabel;

@interface WorkoutCountdown : UIView <WFSessionManagerListener>
{
    BOOL _musicDucked;
    BOOL _skipNextNumber;
    UILabel *_countdownLabel;
}

@property(nonatomic) BOOL skipNextNumber; // @synthesize skipNextNumber=_skipNextNumber;
@property(nonatomic) BOOL musicDucked; // @synthesize musicDucked=_musicDucked;
@property(retain) UILabel *countdownLabel; // @synthesize countdownLabel=_countdownLabel;
- (void).cxx_destruct;
- (void)sessionRecorderDidEndCountdown:(id)arg1;
- (void)sessionRecorder:(id)arg1 countdownTick:(double)arg2;
- (void)sayTimeRemaining:(double)arg1;
- (void)finalAnimationDidStop:(id)arg1;
- (void)stop;
- (void)setCountdownLabelText:(id)arg1;
- (void)countdownButtonTouched:(id)arg1;
- (void)show;
- (id)init;

@end

