//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDate, NSMutableData, NSString;

@interface ZKCDHeader : NSObject
{
    unsigned long _magicNumber;
    unsigned long _versionMadeBy;
    unsigned long _versionNeededToExtract;
    unsigned long _generalPurposeBitFlag;
    unsigned long _compressionMethod;
    NSDate *_lastModDate;
    unsigned long _crc;
    unsigned long _filenameLength;
    unsigned long _extraFieldLength;
    unsigned long _commentLength;
    unsigned long _diskNumberStart;
    unsigned long _internalFileAttributes;
    unsigned long _externalFileAttributes;
    NSString *_filename;
    NSData *_extraField;
    NSString *_comment;
    NSMutableData *_cachedData;
    unsigned long long _compressedSize;
    unsigned long long _uncompressedSize;
    unsigned long long _localHeaderOffset;
}

+ (id)recordWithArchivePath:(id)arg1 atOffset:(unsigned long long)arg2;
+ (id)recordWithData:(id)arg1 atOffset:(unsigned long long)arg2;
@property(retain) NSMutableData *cachedData; // @synthesize cachedData=_cachedData;
@property(copy) NSString *comment; // @synthesize comment=_comment;
@property(retain) NSData *extraField; // @synthesize extraField=_extraField;
@property(copy) NSString *filename; // @synthesize filename=_filename;
@property unsigned long long localHeaderOffset; // @synthesize localHeaderOffset=_localHeaderOffset;
@property unsigned long externalFileAttributes; // @synthesize externalFileAttributes=_externalFileAttributes;
@property unsigned long internalFileAttributes; // @synthesize internalFileAttributes=_internalFileAttributes;
@property unsigned long diskNumberStart; // @synthesize diskNumberStart=_diskNumberStart;
@property unsigned long commentLength; // @synthesize commentLength=_commentLength;
@property unsigned long extraFieldLength; // @synthesize extraFieldLength=_extraFieldLength;
@property unsigned long filenameLength; // @synthesize filenameLength=_filenameLength;
@property unsigned long long uncompressedSize; // @synthesize uncompressedSize=_uncompressedSize;
@property unsigned long long compressedSize; // @synthesize compressedSize=_compressedSize;
@property unsigned long crc; // @synthesize crc=_crc;
@property(retain) NSDate *lastModDate; // @synthesize lastModDate=_lastModDate;
@property unsigned long compressionMethod; // @synthesize compressionMethod=_compressionMethod;
@property unsigned long generalPurposeBitFlag; // @synthesize generalPurposeBitFlag=_generalPurposeBitFlag;
@property unsigned long versionNeededToExtract; // @synthesize versionNeededToExtract=_versionNeededToExtract;
@property unsigned long versionMadeBy; // @synthesize versionMadeBy=_versionMadeBy;
@property unsigned long magicNumber; // @synthesize magicNumber=_magicNumber;
- (void).cxx_destruct;
- (BOOL)isResourceFork;
- (BOOL)isSymLink;
- (BOOL)isDirectory;
- (id)posixPermissions;
- (id)description;
- (BOOL)useZip64Extensions;
- (unsigned int)length;
- (id)zip64ExtraField;
- (void)parseZip64ExtraField;
- (id)data;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)removeObservers;
- (id)init;

@end

