//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZKCDTrailer64Locator : NSObject
{
    unsigned long _magicNumber;
    unsigned long _diskNumberWithStartOfCentralDirectory;
    unsigned long _numberOfDisks;
    unsigned long long _offsetOfStartOfCentralDirectoryTrailer64;
}

+ (id)recordWithArchivePath:(id)arg1 andCDTrailerLength:(unsigned int)arg2;
+ (id)recordWithData:(id)arg1 atOffset:(unsigned long long)arg2;
@property unsigned long numberOfDisks; // @synthesize numberOfDisks=_numberOfDisks;
@property unsigned long long offsetOfStartOfCentralDirectoryTrailer64; // @synthesize offsetOfStartOfCentralDirectoryTrailer64=_offsetOfStartOfCentralDirectoryTrailer64;
@property unsigned long diskNumberWithStartOfCentralDirectory; // @synthesize diskNumberWithStartOfCentralDirectory=_diskNumberWithStartOfCentralDirectory;
@property unsigned long magicNumber; // @synthesize magicNumber=_magicNumber;
- (id)description;
- (unsigned int)length;
- (id)data;
- (id)init;

@end

